# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ApplyWrites.Create do
  @moduledoc """
  **create** (object/record)

  Operation which creates a new record.
  """

  @enforce_keys [:collection, :value]
  defstruct collection: nil, rkey: nil, value: nil

  @type t :: %__MODULE__{
          collection: String.t(),
          rkey: String.t(),
          value: any()
        }
end
