# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ApplyWrites.Delete do
  @moduledoc """
  **delete** (object/record)

  Operation which deletes an existing record.
  """

  @enforce_keys [:collection, :rkey]
  defstruct collection: nil, rkey: nil

  @type t :: %__MODULE__{
          collection: String.t(),
          rkey: String.t()
        }
end
