# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ApplyWrites.Main do
  @moduledoc """
  **main** (procedure)

  Apply a batch transaction of repository creates, updates, and deletes. Requires auth, implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
