# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ApplyWrites.Update do
  @moduledoc """
  **update** (object/record)

  Operation which updates an existing record.
  """

  @enforce_keys [:collection, :rkey, :value]
  defstruct collection: nil, rkey: nil, value: nil

  @type t :: %__MODULE__{
          collection: String.t(),
          rkey: String.t(),
          value: any()
        }
end
