# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.Migrate do
  @moduledoc """
  **migrate** (object/record)

  DEPRECATED -- Use #account event instead
  """

  @enforce_keys [:seq, :did, :migrateTo, :time]
  defstruct did: nil, migrateTo: nil, seq: nil, time: nil

  @type t :: %__MODULE__{
          did: String.t(),
          migrateTo: String.t() | nil,
          seq: integer(),
          time: String.t()
        }
end
