# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Moderation.GetActorMetadata.Metadata do
  @moduledoc """
  Generated schema for metadata

  **Description**: No description provided.
  """

  @enforce_keys [:messages_sent, :messages_received, :convos, :convos_started]
  defstruct convos: nil, convos_started: nil, messages_received: nil, messages_sent: nil

  @type t :: %__MODULE__{
          convos: integer(),
          convos_started: integer(),
          messages_received: integer(),
          messages_sent: integer()
        }
end
