# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonOther do
  @moduledoc """
  Token type for reasonOther

  **Description**: Other: reports not falling under another report category
  """

  @type t :: atom()
end
