# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonAppeal do
  @moduledoc """
  Token type for reasonAppeal

  **Description**: Appeal: appeal a previously taken moderation action
  """

  @type t :: atom()
end
