# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonRude do
  @moduledoc """
  Token type for reasonRude

  **Description**: Rude, harassing, explicit, or otherwise unwelcoming behavior
  """

  @type t :: atom()
end
