# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonSpam do
  @moduledoc """
  Token type for reasonSpam

  **Description**: Spam: frequent unwanted promotion, replies, mentions
  """

  @type t :: atom()
end
