# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonSexual do
  @moduledoc """
  Token type for reasonSexual

  **Description**: Unwanted or mislabeled sexual content
  """

  @type t :: atom()
end
