# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonType do
  @moduledoc """
  Generated schema for reasonType

  **Description**: No description provided.
  """

  @type t ::
          :"com.atproto.moderation.defs#reasonSpam"
          | :"com.atproto.moderation.defs#reasonViolation"
          | :"com.atproto.moderation.defs#reasonMisleading"
          | :"com.atproto.moderation.defs#reasonSexual"
          | :"com.atproto.moderation.defs#reasonRude"
          | :"com.atproto.moderation.defs#reasonOther"
          | :"com.atproto.moderation.defs#reasonAppeal"
end
