# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonMisleading do
  @moduledoc """
  Token type for reasonMisleading

  **Description**: Misleading identity, affiliation, or content
  """

  @type t :: atom()
end
