# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.Defs.ReasonViolation do
  @moduledoc """
  Token type for reasonViolation

  **Description**: Direct violation of server rules, laws, terms of service
  """

  @type t :: atom()
end
