# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.SearchPostsSkeleton.Main do
  @moduledoc """
  **main** (query)

  Backend Posts search, returns only skeleton
  """

  @type input :: any()
  @type output :: any()
end
