# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.Defs.CommitMeta do
  @moduledoc """
  Generated schema for commitMeta

  **Description**: No description provided.
  """

  @enforce_keys [:cid, :rev]
  defstruct cid: nil, rev: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          rev: String.t()
        }
end
