# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.GetServices.Main do
  @moduledoc """
  **main** (query)

  Get information about a list of labeler services.
  """

  @type input :: any()
  @type output :: any()
end
