# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.EmitEvent.MainErrorSubjectHasAction do
  @moduledoc """
  Generated schema for mainErrorSubjectHasAction

  **Description**: No description provided.
  """

  @type t :: any()
end
