# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAppPassword.AppPassword do
  @moduledoc """
  **appPassword** (object/record)

  No description.
  """

  @enforce_keys [:name, :password, :createdAt]
  defstruct createdAt: nil, name: nil, password: nil, privileged: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          name: String.t(),
          password: String.t(),
          privileged: boolean()
        }
end
