# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAppPassword.Main do
  @moduledoc """
  **main** (procedure)

  Create an App Password.
  """

  @type input :: any()
  @type output :: any()
end
