# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.AddMember do
  @moduledoc """
  Generated procedure module for main

  **Description**: Add a member to the ozone team. Requires admin role.
  """

  @type output :: ProtoRune.Tools.Ozone.Team.Defs.Member.t()
  @type input :: %{
          did: String.t(),
          role:
            :"tools.ozone.team.defs#roleAdmin"
            | :"tools.ozone.team.defs#roleModerator"
            | :"tools.ozone.team.defs#roleTriage"
        }
  @type error :: ProtoRune.Tools.Ozone.Team.AddMember.MainErrorMemberAlreadyExists.t()
end
