# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.DeleteMember do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete a member from ozone team. Requires admin role.
  """

  @type input :: %{did: String.t()}
  @type error ::
          ProtoRune.Tools.Ozone.Team.DeleteMember.MainErrorMemberNotFound.t()
          | ProtoRune.Tools.Ozone.Team.DeleteMember.MainErrorCannotDeleteSelf.t()
end
