# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.ListMembers do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cursor: String.t(), limit: integer()}
end
