# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.UpdateMember do
  @moduledoc """
  Generated procedure module for main

  **Description**: Update a member in the ozone service. Requires admin role.
  """

  @type output :: ProtoRune.Tools.Ozone.Team.Defs.Member.t()
  @type input :: %{
          did: String.t(),
          disabled: boolean(),
          role:
            :"tools.ozone.team.defs#roleAdmin"
            | :"tools.ozone.team.defs#roleModerator"
            | :"tools.ozone.team.defs#roleTriage"
        }
  @type error :: ProtoRune.Tools.Ozone.Team.UpdateMember.MainErrorMemberNotFound.t()
end
