# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.Defs.CommitMeta do
  @moduledoc """
  **commitMeta** (object/record)

  No description.
  """

  @enforce_keys [:cid, :rev]
  defstruct cid: nil, rev: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          rev: String.t()
        }
end
