# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.DeleteRecord do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete a repository record, or ensure it doesn't exist. Requires auth, implemented by PDS.
  """

  @type output :: %{commit: ProtoRune.Com.Atproto.Repo.Defs.CommitMeta.t()}
  @type input :: %{
          collection: String.t(),
          repo: String.t(),
          rkey: String.t(),
          swap_commit: String.t(),
          swap_record: String.t()
        }
  @type error :: ProtoRune.Com.Atproto.Repo.DeleteRecord.MainErrorInvalidSwap.t()
end
