# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.DescribeRepo do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{repo: String.t()}
end
