# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.GetRecord do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cid: String.t(), collection: String.t(), repo: String.t(), rkey: String.t()}
end
