# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ImportRepo do
  @moduledoc """
  Generated procedure module for main

  **Description**: Import a repo in the form of a CAR file. Requires Content-Length HTTP header to be set.
  """

  @type input :: any()
end
