# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ListRecords do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          collection: String.t(),
          cursor: String.t(),
          limit: integer(),
          repo: String.t(),
          reverse: boolean(),
          rkey_end: String.t(),
          rkey_start: String.t()
        }
end
