# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.UploadBlob do
  @moduledoc """
  Generated procedure module for main

  **Description**: Upload a new blob, to be referenced from a repository record. The blob will be deleted if it is not referenced within a time window (eg, minutes). Blob restrictions (mimetype, size, etc) are enforced when the reference is created. Requires auth, implemented by PDS.
  """

  @type output :: %{blob: binary()}
  @type input :: any()
end
