# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.Defs.JobStatus do
  @moduledoc """
  **jobStatus** (object/record)

  No description.
  """

  @enforce_keys [:jobId, :did, :state]
  defstruct blob: nil, did: nil, error: nil, jobId: nil, message: nil, progress: nil, state: nil

  @type t :: %__MODULE__{
          blob: binary(),
          did: String.t(),
          error: String.t(),
          jobId: String.t(),
          message: String.t(),
          progress: integer(),
          state: :JOB_STATE_COMPLETED | :JOB_STATE_FAILED
        }
end
