# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.ListTemplates.Main do
  @moduledoc """
  **main** (query)

  Get list of all communication templates.
  """

  @type input :: any()
  @type output :: any()
end
