# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.DeleteMessageForSelf do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView.t()
  @type input :: %{convo_id: String.t(), message_id: String.t()}
end
