# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.GetMessages do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{convo_id: String.t(), cursor: String.t(), limit: integer()}
end
