# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.GetConvoForMembers do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{members: list(String.t())}
end
