# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.LeaveConvo do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: %{convo_id: String.t(), rev: String.t()}
  @type input :: %{convo_id: String.t()}
end
