# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.MuteConvo do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: %{convo: ProtoRune.Chat.Bsky.Convo.Defs.ConvoView.t()}
  @type input :: %{convo_id: String.t()}
end
