# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.SendMessageBatch do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: %{items: list(ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t())}
  @type input :: %{items: list(ProtoRune.Chat.Bsky.Convo.SendMessageBatch.BatchItem.t())}
end
