# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.SendMessage do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t()
  @type input :: %{convo_id: String.t(), message: ProtoRune.Chat.Bsky.Convo.Defs.MessageInput.t()}
end
