# File generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Types do
  @moduledoc """
  Central module holding all basic (non-struct) types from Lexicon schemas.
  Generated automatically by `mix gen_schemas`.
  """

  @typedoc """
  labelValue (com.atproto.label.defs)
  No description.
  """
  @type com_atproto_label_defs_label_value ::
          :"!hide"
          | :"!no-promote"
          | :"!warn"
          | :"!no-unauthenticated"
          | :"dmca-violation"
          | :doxxing
          | :porn
          | :sexual
          | :nudity
          | :nsfl
          | :gore

  @typedoc """
  modlist (app.bsky.graph.defs)
  A list of actors to apply an aggregate moderation action (mute/block) on.
  """
  @type app_bsky_graph_defs_modlist :: atom()

  @typedoc """
  reasonType (com.atproto.moderation.defs)
  No description.
  """
  @type com_atproto_moderation_defs_reason_type ::
          :"com.atproto.moderation.defs#reasonSpam"
          | :"com.atproto.moderation.defs#reasonViolation"
          | :"com.atproto.moderation.defs#reasonMisleading"
          | :"com.atproto.moderation.defs#reasonSexual"
          | :"com.atproto.moderation.defs#reasonRude"
          | :"com.atproto.moderation.defs#reasonOther"
          | :"com.atproto.moderation.defs#reasonAppeal"

  @typedoc """
  interactionSeen (app.bsky.feed.defs)
  Feed item was seen by user
  """
  @type app_bsky_feed_defs_interaction_seen :: atom()

  @typedoc """
  reasonOther (com.atproto.moderation.defs)
  Other: reports not falling under another report category
  """
  @type com_atproto_moderation_defs_reason_other :: atom()

  @typedoc """
  roleAdmin (tools.ozone.team.defs)
  Admin role. Highest level of access, can perform all actions.
  """
  @type tools_ozone_team_defs_role_admin :: atom()

  @typedoc """
  referencelist (app.bsky.graph.defs)
  A list of actors used for only for reference purposes such as within a starter pack.
  """
  @type app_bsky_graph_defs_referencelist :: atom()

  @typedoc """
  reviewEscalated (tools.ozone.moderation.defs)
  Moderator review status of a subject: Escalated. Indicates that the subject was escalated for review by a moderator
  """
  @type tools_ozone_moderation_defs_review_escalated :: atom()

  @typedoc """
  requestLess (app.bsky.feed.defs)
  Request that less content like the given feed item be shown in the feed
  """
  @type app_bsky_feed_defs_request_less :: atom()

  @typedoc """
  interactionReply (app.bsky.feed.defs)
  User replied to the feed item
  """
  @type app_bsky_feed_defs_interaction_reply :: atom()

  @typedoc """
  interactionLike (app.bsky.feed.defs)
  User liked the feed item
  """
  @type app_bsky_feed_defs_interaction_like :: atom()

  @typedoc """
  clickthroughReposter (app.bsky.feed.defs)
  User clicked through to the reposter of the feed item
  """
  @type app_bsky_feed_defs_clickthrough_reposter :: atom()

  @typedoc """
  reasonRude (com.atproto.moderation.defs)
  Rude, harassing, explicit, or otherwise unwelcoming behavior
  """
  @type com_atproto_moderation_defs_reason_rude :: atom()

  @typedoc """
  reviewOpen (tools.ozone.moderation.defs)
  Moderator review status of a subject: Open. Indicates that the subject needs to be reviewed by a moderator
  """
  @type tools_ozone_moderation_defs_review_open :: atom()

  @typedoc """
  main (com.atproto.label.subscribeLabels)
  Subscribe to stream of labels (and negations). Public endpoint implemented by mod services. Uses same sequencing scheme as repo event stream.
  """
  @type com_atproto_label_subscribe_labels_main :: any()

  @typedoc """
  contentModeUnspecified (app.bsky.feed.defs)
  Declares the feed generator returns any types of posts.
  """
  @type app_bsky_feed_defs_content_mode_unspecified :: atom()

  @typedoc """
  clickthroughAuthor (app.bsky.feed.defs)
  User clicked through to the author of the feed item
  """
  @type app_bsky_feed_defs_clickthrough_author :: atom()

  @typedoc """
  contentModeVideo (app.bsky.feed.defs)
  Declares the feed generator returns posts containing app.bsky.embed.video embeds.
  """
  @type app_bsky_feed_defs_content_mode_video :: atom()

  @typedoc """
  reviewNone (tools.ozone.moderation.defs)
  Moderator review status of a subject: Unnecessary. Indicates that the subject does not need a review at the moment but there is probably some moderation related metadata available for it
  """
  @type tools_ozone_moderation_defs_review_none :: atom()

  @typedoc """
  preferences (app.bsky.actor.defs)
  No description.
  """
  @type app_bsky_actor_defs_preferences ::
          list(
            ProtoRune.App.Bsky.Actor.Defs.AdultContentPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.ContentLabelPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPrefV2.t()
            | ProtoRune.App.Bsky.Actor.Defs.PersonalDetailsPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.FeedViewPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.ThreadViewPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.InterestsPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.MutedWordsPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.HiddenPostsPref.t()
            | ProtoRune.App.Bsky.Actor.Defs.BskyAppStatePref.t()
            | ProtoRune.App.Bsky.Actor.Defs.LabelersPref.t()
          )

  @typedoc """
  reviewClosed (tools.ozone.moderation.defs)
  Moderator review status of a subject: Closed. Indicates that the subject was already reviewed and resolved by a moderator
  """
  @type tools_ozone_moderation_defs_review_closed :: atom()

  @typedoc """
  reasonSpam (com.atproto.moderation.defs)
  Spam: frequent unwanted promotion, replies, mentions
  """
  @type com_atproto_moderation_defs_reason_spam :: atom()

  @typedoc """
  reasonMisleading (com.atproto.moderation.defs)
  Misleading identity, affiliation, or content
  """
  @type com_atproto_moderation_defs_reason_misleading :: atom()

  @typedoc """
  clickthroughItem (app.bsky.feed.defs)
  User clicked through to the feed item
  """
  @type app_bsky_feed_defs_clickthrough_item :: atom()

  @typedoc """
  main (com.atproto.sync.subscribeRepos)
  Repository event stream, aka Firehose endpoint. Outputs repo commits with diff data, and identity update events, for all repositories on the current server. See the atproto specifications for details around stream sequencing, repo versioning, CAR diff format, and more. Public and does not require auth; implemented by PDS and Relay.
  """
  @type com_atproto_sync_subscribe_repos_main :: any()

  @typedoc """
  roleModerator (tools.ozone.team.defs)
  Moderator role. Can perform most actions.
  """
  @type tools_ozone_team_defs_role_moderator :: atom()

  @typedoc """
  requestMore (app.bsky.feed.defs)
  Request that more content like the given feed item be shown in the feed
  """
  @type app_bsky_feed_defs_request_more :: atom()

  @typedoc """
  subjectReviewState (tools.ozone.moderation.defs)
  No description.
  """
  @type tools_ozone_moderation_defs_subject_review_state ::
          :"#reviewOpen" | :"#reviewEscalated" | :"#reviewClosed" | :"#reviewNone"

  @typedoc """
  clickthroughEmbed (app.bsky.feed.defs)
  User clicked through to the embedded content of the feed item
  """
  @type app_bsky_feed_defs_clickthrough_embed :: atom()

  @typedoc """
  interactionShare (app.bsky.feed.defs)
  User shared the feed item
  """
  @type app_bsky_feed_defs_interaction_share :: atom()

  @typedoc """
  interactionRepost (app.bsky.feed.defs)
  User reposted the feed item
  """
  @type app_bsky_feed_defs_interaction_repost :: atom()

  @typedoc """
  roleTriage (tools.ozone.team.defs)
  Triage role. Mostly intended for monitoring and escalating issues.
  """
  @type tools_ozone_team_defs_role_triage :: atom()

  @typedoc """
  curatelist (app.bsky.graph.defs)
  A list of actors used for curation purposes such as list feeds or interaction gating.
  """
  @type app_bsky_graph_defs_curatelist :: atom()

  @typedoc """
  reasonViolation (com.atproto.moderation.defs)
  Direct violation of server rules, laws, terms of service
  """
  @type com_atproto_moderation_defs_reason_violation :: atom()

  @typedoc """
  mutedWordTarget (app.bsky.actor.defs)
  No description.
  """
  @type app_bsky_actor_defs_muted_word_target :: :content | :tag

  @typedoc """
  reasonAppeal (com.atproto.moderation.defs)
  Appeal: appeal a previously taken moderation action
  """
  @type com_atproto_moderation_defs_reason_appeal :: atom()

  @typedoc """
  interactionQuote (app.bsky.feed.defs)
  User quoted the feed item
  """
  @type app_bsky_feed_defs_interaction_quote :: atom()

  @typedoc """
  reasonSexual (com.atproto.moderation.defs)
  Unwanted or mislabeled sexual content
  """
  @type com_atproto_moderation_defs_reason_sexual :: atom()

  @typedoc """
  listPurpose (app.bsky.graph.defs)
  No description.
  """
  @type app_bsky_graph_defs_list_purpose ::
          :"app.bsky.graph.defs#modlist"
          | :"app.bsky.graph.defs#curatelist"
          | :"app.bsky.graph.defs#referencelist"
end
