# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.RequestPlcOperationSignature.Main do
  @moduledoc """
  **main** (procedure)

  Request an email with a code to in order to request a signed PLC operation. Requires Auth.
  """

  @type input :: any()
  @type output :: any()
end
