defmodule ProtoRune.Atproto.OAuth do
  @moduledoc """
  AT Protocol OAuth 2.0 authorization flow.

  Implements the authorization code flow with PAR (Pushed Authorization
  Requests), PKCE and DPoP as described in
  https://atproto.com/specs/oauth, as an alternative to app password
  authentication (`ProtoRune.login/3`).

  Only public clients are supported: the client authenticates with a
  `client_id` URL pointing to its client metadata document, and every
  authorization server request carries a DPoP proof signed with an ES256
  key generated locally (see `ProtoRune.Atproto.OAuth.DPoP`). No external
  JWT dependency is required.

  ## Flow overview

      alias ProtoRune.Atproto.OAuth
      alias ProtoRune.Atproto.OAuth.Client

      {:ok, client} =
        Client.new(
          client_id: "https://myapp.example.com/oauth/client-metadata.json",
          redirect_uri: "https://myapp.example.com/oauth/callback"
        )

      # 1. Send the user to the authorization server
      {:ok, url, pending} = OAuth.authorization_url(client, "alice.bsky.social")
      # redirect the user to `url`, persist `pending` (e.g. in the session)

      # 2. Handle the callback with the received query params
      {:ok, session} = OAuth.exchange_code(client, pending, callback_params)

      # 3. Refresh when the access token expires
      {:ok, fresh_session} = OAuth.refresh(client, session)

      # 4. Revoke the refresh token on logout
      {:ok, :revoked} = OAuth.revoke(session, client_id: client.client_id)

  The `pending` map holds the flow state (PKCE verifier, state, DPoP
  nonce) and must be kept between steps 1 and 2. It contains the DPoP
  private key, so persist it securely.

  ## Scope of this implementation

  Issued access tokens are DPoP-bound. OAuth sessions implement the
  `ProtoRune.Session` behaviour, so they can be passed to any XRPC or DSL
  function; the session attaches the required DPoP proof to each request.
  For long-running applications, `ProtoRune.Atproto.OAuth.SessionManager`
  keeps a session fresh automatically. Confidential clients
  (`private_key_jwt`) and client metadata document serving are out of
  scope.
  """

  alias ProtoRune.Atproto.Identity
  alias ProtoRune.Atproto.OAuth.Client
  alias ProtoRune.Atproto.OAuth.DPoP
  alias ProtoRune.Atproto.OAuth.PKCE
  alias ProtoRune.Atproto.OAuth.Session
  alias ProtoRune.HTTPClient

  @typedoc """
  Flow state produced by `authorization_url/3` and consumed by
  `exchange_code/3`.
  """
  @type pending :: %{
          did: String.t(),
          handle: String.t() | nil,
          service_url: String.t(),
          issuer: String.t(),
          state: String.t(),
          code_verifier: String.t(),
          dpop_key: DPoP.private_key(),
          dpop_jwk: DPoP.jwk(),
          dpop_nonce: String.t() | nil,
          token_endpoint: String.t()
        }

  @type error :: {:error, term()}

  @doc """
  Starts the authorization flow and returns the URL to send the user to.

  Resolves the account's PDS from its handle or DID, discovers the
  authorization server through the OAuth metadata documents and pushes the
  authorization request (PAR) with PKCE and DPoP.

  Returns `{:ok, url, pending}`. Redirect the user to `url` and keep
  `pending` until the callback is exchanged with `exchange_code/3`.

  ## Options

  - `:state` - Explicit state value (a random one is generated by default).
  - `:dpop_nonce` - DPoP nonce from a previous interaction with the
    authorization server.
  """
  @spec authorization_url(Client.t(), String.t(), keyword()) ::
          {:ok, String.t(), pending()} | error()
  def authorization_url(%Client{} = client, identifier, opts \\ []) when is_binary(identifier) do
    with {:ok, did, handle} <- resolve_account(identifier),
         {:ok, pds} <- resolve_pds(did),
         {:ok, issuer} <- protected_resource_issuer(pds),
         {:ok, metadata} <- authorization_server_metadata(issuer),
         {:ok, par} <- push_authorization_request(client, metadata, identifier, opts) do
      query = URI.encode_query(%{"client_id" => client.client_id, "request_uri" => par.request_uri})

      pending = %{
        did: did,
        handle: handle,
        service_url: pds,
        issuer: metadata.issuer,
        state: par.state,
        code_verifier: par.code_verifier,
        dpop_key: client.dpop_key,
        dpop_jwk: client.dpop_jwk,
        dpop_nonce: par.nonce,
        token_endpoint: metadata.token_endpoint
      }

      {:ok, metadata.authorization_endpoint <> "?" <> query, pending}
    end
  end

  @doc """
  Exchanges the authorization code received on the callback for tokens.

  `params` is the query string params map of the callback request (string
  or atom keys). The `state` param must match the one in `pending` and,
  when present, `iss` must match the discovered authorization server.

  Returns an OAuth `Session` with DPoP-bound tokens.
  """
  @spec exchange_code(Client.t(), pending(), map()) :: {:ok, Session.t()} | error()
  def exchange_code(%Client{} = client, pending, params) when is_map(pending) and is_map(params) do
    with :ok <- verify_state(pending, params),
         :ok <- verify_issuer(pending, params),
         {:ok, code} <- fetch_code(params),
         {:ok, data, nonce} <- exchange_request(client, pending, code) do
      Session.parse(data, %{
        handle: pending.handle,
        service_url: pending.service_url,
        issuer: pending.issuer,
        token_endpoint: pending.token_endpoint,
        dpop_key: client.dpop_key,
        dpop_jwk: client.dpop_jwk,
        dpop_nonce: nonce
      })
    end
  end

  @doc """
  Refreshes an OAuth session using its refresh token.

  Follows refresh token rotation: when the server issues a new refresh
  token it replaces the old one, otherwise the previous one is kept.
  """
  @spec refresh(Client.t(), Session.t()) :: {:ok, Session.t()} | error()
  def refresh(%Client{}, %Session{refresh_token: nil}), do: {:error, :missing_refresh_token}

  def refresh(%Client{} = client, %Session{} = session) do
    form = %{
      "grant_type" => "refresh_token",
      "refresh_token" => session.refresh_token,
      "client_id" => client.client_id
    }

    # The DPoP proof and the refreshed session use the session's key,
    # not the client's: the grant is bound (via the access token's
    # cnf.jkt) to the key the session was issued with, and a host that
    # restored a persisted session may hold a Client built with a
    # fresh key.
    with {:ok, data, nonce} <- dpop_post(session.token_endpoint, form, session, session.dpop_nonce),
         {:ok, fresh} <-
           Session.parse(data, %{
             handle: session.handle,
             service_url: session.service_url,
             issuer: session.issuer,
             token_endpoint: session.token_endpoint,
             dpop_key: session.dpop_key,
             dpop_jwk: session.dpop_jwk,
             dpop_nonce: nonce
           }) do
      {:ok, %{fresh | refresh_token: fresh.refresh_token || session.refresh_token}}
    end
  end

  @doc """
  Revokes the session's refresh token at the authorization server.

  Discovers the `revocation_endpoint` from the authorization server
  metadata (RFC 7009) of the session's `issuer` and posts a public-client
  revocation request carrying a DPoP proof, bound to the session's access
  token via the `ath` claim like the token endpoint calls.

  Per RFC 7009 the server answers 200 even for unknown or already invalid
  tokens, so `{:ok, :revoked}` means the token is gone, not that it was
  still valid.

  ## Options

  - `:client_id` - Required. The `client_id` the session was issued to,
    as configured on the `Client` that ran the flow.

  Returns `{:error, :revocation_not_supported}` when the authorization
  server declares no revocation endpoint; no revocation request is made
  in that case.
  """
  @spec revoke(Session.t(), keyword()) :: {:ok, :revoked} | error()
  def revoke(session, opts \\ [])

  def revoke(%Session{refresh_token: nil}, _opts), do: {:error, :missing_refresh_token}

  def revoke(%Session{} = session, opts) do
    with {:ok, client_id} <- fetch_client_id(opts),
         {:ok, endpoint} <- revocation_endpoint(session) do
      form = %{"token" => session.refresh_token, "client_id" => client_id}

      case dpop_post(endpoint, form, session, session.dpop_nonce, true, session.access_token) do
        {:ok, _body, _nonce} -> {:ok, :revoked}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  defp fetch_client_id(opts) do
    case Keyword.get(opts, :client_id) do
      client_id when is_binary(client_id) -> {:ok, client_id}
      _other -> {:error, :missing_client_id}
    end
  end

  defp revocation_endpoint(%Session{issuer: nil}), do: {:error, :revocation_not_supported}

  defp revocation_endpoint(%Session{issuer: issuer}) do
    with {:ok, metadata} <- authorization_server_metadata(issuer) do
      case metadata.revocation_endpoint do
        url when is_binary(url) -> {:ok, url}
        _other -> {:error, :revocation_not_supported}
      end
    end
  end

  # Identity resolution

  defp resolve_account(identifier) do
    cond do
      Identity.valid_did?(identifier) ->
        {:ok, identifier, nil}

      Identity.valid_handle?(identifier) ->
        case Identity.resolve_handle(identifier) do
          {:ok, did} -> {:ok, did, identifier}
          {:error, reason} -> {:error, reason}
        end

      true ->
        {:error, :invalid_identifier}
    end
  end

  defp resolve_pds(did) do
    with {:ok, doc} <- Identity.resolve_did(did) do
      # Note: Identity returns DID documents normalized by Case.snakelize_enum/1,
      # where nested maps become keyword lists. Key access works for both.
      doc
      |> Map.get(:service, [])
      |> Enum.find(fn service -> service[:type] == "AtprotoPersonalDataServer" end)
      |> case do
        nil -> {:error, :pds_not_found}
        service -> pds_endpoint(service[:service_endpoint])
      end
    end
  end

  defp pds_endpoint(url) when is_binary(url), do: {:ok, url}
  defp pds_endpoint(_other), do: {:error, :pds_not_found}

  # Authorization server discovery

  defp protected_resource_issuer(pds) do
    url = String.trim_trailing(pds, "/") <> "/.well-known/oauth-protected-resource"

    case fetch_json(url) do
      {:ok, %{"authorization_servers" => [issuer | _]}} when is_binary(issuer) -> {:ok, issuer}
      {:ok, _other} -> {:error, :invalid_protected_resource_metadata}
      {:error, reason} -> {:error, reason}
    end
  end

  @required_metadata_fields [
    "issuer",
    "authorization_endpoint",
    "token_endpoint",
    "pushed_authorization_request_endpoint"
  ]

  defp authorization_server_metadata(issuer) do
    url = String.trim_trailing(issuer, "/") <> "/.well-known/oauth-authorization-server"

    with {:ok, metadata} <- fetch_json(url),
         :ok <- require_fields(metadata, @required_metadata_fields),
         :ok <- verify_metadata_issuer(metadata, issuer) do
      {:ok,
       %{
         issuer: metadata["issuer"],
         authorization_endpoint: metadata["authorization_endpoint"],
         token_endpoint: metadata["token_endpoint"],
         par_endpoint: metadata["pushed_authorization_request_endpoint"],
         revocation_endpoint: metadata["revocation_endpoint"]
       }}
    end
  end

  defp require_fields(metadata, fields) do
    if Enum.all?(fields, &(is_binary(metadata[&1]) and metadata[&1] != "")) do
      :ok
    else
      {:error, :invalid_authorization_server_metadata}
    end
  end

  defp verify_metadata_issuer(%{"issuer" => found}, expected) do
    if String.trim_trailing(found, "/") == String.trim_trailing(expected, "/") do
      :ok
    else
      {:error, :issuer_mismatch}
    end
  end

  # PAR and token requests

  defp push_authorization_request(client, metadata, identifier, opts) do
    state = Keyword.get(opts, :state) || random_state()
    {verifier, challenge} = PKCE.generate()

    form = %{
      "response_type" => "code",
      "client_id" => client.client_id,
      "redirect_uri" => client.redirect_uri,
      "scope" => client.scope,
      "state" => state,
      "code_challenge" => challenge,
      "code_challenge_method" => "S256",
      "login_hint" => identifier
    }

    case dpop_post(metadata.par_endpoint, form, client, Keyword.get(opts, :dpop_nonce)) do
      {:ok, %{"request_uri" => request_uri}, nonce} ->
        {:ok, %{request_uri: request_uri, state: state, code_verifier: verifier, nonce: nonce}}

      {:ok, _other, _nonce} ->
        {:error, :invalid_par_response}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp exchange_request(client, pending, code) do
    form = %{
      "grant_type" => "authorization_code",
      "code" => code,
      "redirect_uri" => client.redirect_uri,
      "client_id" => client.client_id,
      "code_verifier" => pending.code_verifier
    }

    dpop_post(pending.token_endpoint, form, client, pending.dpop_nonce)
  end

  # Performs a form POST with a DPoP proof, retrying once with the
  # server-provided nonce when the response demands it. `keys` is any
  # struct carrying the DPoP key material (a `Client` or a `Session`);
  # `access_token`, when given, binds the proof via the `ath` claim.
  defp dpop_post(url, form, keys, nonce, allow_retry \\ true, access_token \\ nil) do
    proof =
      DPoP.proof(keys.dpop_key, keys.dpop_jwk, :post, url, nonce: nonce, access_token: access_token)

    headers = [{"dpop", proof}, {"accept", "application/json"}]

    :post
    |> HTTPClient.request(url, form: form, headers: headers)
    |> handle_dpop_response(url, form, keys, nonce, allow_retry, access_token)
  end

  # The HTTP adapter returns raw bodies: decode JSON before matching on
  # error payloads like "use_dpop_nonce". Non-JSON bodies (the revocation
  # endpoint answers 200 with an empty body) pass through as-is.
  defp handle_dpop_response({:ok, %{status: status, body: body} = resp}, url, form, keys, nonce, retry, access_token)
       when is_binary(body) do
    case JSON.decode(body) do
      {:ok, decoded} when is_map(decoded) ->
        handle_dpop_response(
          {:ok, %{resp | body: decoded}},
          url,
          form,
          keys,
          nonce,
          retry,
          access_token
        )

      _ when status in 200..299 ->
        {:ok, body, get_header(resp.headers, "dpop-nonce") || nonce}

      _ ->
        {:error, {:oauth_error, status, body}}
    end
  end

  # Success responses carry any body shape: the token endpoints answer
  # JSON while the revocation endpoint (RFC 7009) answers 200 with an
  # empty body. Callers validate the payload they expect.
  defp handle_dpop_response(
         {:ok, %{status: status, body: body, headers: resp_headers}},
         _url,
         _form,
         _keys,
         nonce,
         _retry,
         _access_token
       )
       when status in 200..299 do
    {:ok, body, get_header(resp_headers, "dpop-nonce") || nonce}
  end

  defp handle_dpop_response(
         {:ok, %{status: status, body: %{"error" => "use_dpop_nonce"} = body, headers: resp_headers}},
         url,
         form,
         keys,
         _nonce,
         true,
         access_token
       )
       when status in [400, 401] do
    case get_header(resp_headers, "dpop-nonce") do
      nil -> {:error, {:oauth_error, status, body}}
      new_nonce -> dpop_post(url, form, keys, new_nonce, false, access_token)
    end
  end

  defp handle_dpop_response({:ok, %{status: status, body: body}}, _url, _form, _keys, _nonce, _retry, _access_token) do
    {:error, {:oauth_error, status, body}}
  end

  defp handle_dpop_response({:error, reason}, _url, _form, _keys, _nonce, _retry, _access_token) do
    {:error, reason}
  end

  defp fetch_json(url) do
    case HTTPClient.request(:get, url, headers: [{"accept", "application/json"}]) do
      {:ok, %{status: status, body: body}} when status in 200..299 ->
        decode_json_body(body)

      {:ok, %{status: status}} ->
        {:error, {:http_error, status}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # The HTTP adapter returns raw bodies; JSON decoding happens at the call
  # site, like the XRPC client and the DID resolver do.
  defp decode_json_body(body) when is_map(body), do: {:ok, body}

  defp decode_json_body(body) when is_binary(body) do
    case JSON.decode(body) do
      {:ok, decoded} when is_map(decoded) -> {:ok, decoded}
      _ -> {:error, :invalid_json}
    end
  end

  # Callback param validation

  defp verify_state(pending, params) do
    if get_param(params, "state") == pending.state do
      :ok
    else
      {:error, :state_mismatch}
    end
  end

  defp verify_issuer(pending, params) do
    case get_param(params, "iss") do
      nil -> :ok
      iss when iss == pending.issuer -> :ok
      _other -> {:error, :issuer_mismatch}
    end
  end

  defp fetch_code(params) do
    case get_param(params, "code") do
      code when is_binary(code) -> {:ok, code}
      _other -> {:error, :missing_code}
    end
  end

  # Accepts both string and atom keys so callers can pass query params as-is
  defp get_param(params, key) when is_map(params) do
    Map.get(params, key) || Map.get(params, String.to_existing_atom(key))
  rescue
    ArgumentError -> Map.get(params, key)
  end

  defp get_header(headers, name) when is_map(headers) do
    # Req responses carry headers as a downcased string map with list values
    case Map.get(headers, name) do
      [value | _] -> value
      value -> value
    end
  end

  defp get_header(headers, name) when is_list(headers) do
    Enum.find_value(headers, fn {key, value} ->
      if String.downcase(to_string(key)) == name, do: value
    end)
  end

  defp get_header(_headers, _name), do: nil

  defp random_state do
    32
    |> :crypto.strong_rand_bytes()
    |> Base.url_encode64(padding: false)
  end
end
