defmodule ProtoRune.Atproto.Repo do
  @moduledoc """
  Low-level `com.atproto.repo` operations.

  Create, read, update, delete, and list records in a repository.
  Write operations require an authenticated `ProtoRune.Atproto.Session`;
  read operations (`get_record`, `list_records`) accept an optional session.

  For common Bluesky actions (posting, liking, reposting) prefer the
  high-level `ProtoRune` API, which wraps these calls with the right
  collections and record schemas.
  """

  import ProtoRune.XRPC.DSL

  alias ProtoRune.Session
  alias ProtoRune.XRPC.Client
  alias ProtoRune.XRPC.Config
  alias ProtoRune.XRPC.Procedure

  @collections [:generator, :like, :post, :postgate, :repost, :threadgate]

  @strong_ref_t %{uri: {:required, :string}, cid: {:required, :string}}

  @like_t %{
    "$type": {:required, :string},
    subject: {:required, @strong_ref_t},
    created_at: :string
  }

  @repost_t %{
    "$type": {:required, :string},
    subject: {:required, @strong_ref_t},
    created_at: :string
  }

  @byte_slice_t %{
    byte_start: {:required, {:integer, {:gte, 0}}},
    byte_end: {:required, {:integer, {:gte, 0}}}
  }
  @link_t %{"$type": {:required, :string}, uri: {:required, :string}}
  @tag_t %{"$type": {:required, :string}, tag: {:required, {:string, {:max, 640}}}}
  @mention_t %{"$type": {:required, :string}, did: {:required, :string}}
  @facet_t %{
    index: {:required, @byte_slice_t},
    features: {:required, {:list, {:oneof, [@link_t, @tag_t, @mention_t]}}}
  }
  @self_label_t %{val: {:required, {:string, {:max, 128}}}}
  @post_t %{
    "$type": {:required, :string},
    text: {:required, {:string, {:max, 300}}},
    reply: %{root: {:required, @strong_ref_t}, parent: {:required, @strong_ref_t}},
    langs: {:list, :string},
    facets: {:list, @facet_t},
    tags: {:list, {:string, {:max, 640}}},
    labels: {:list, %{values: {:list, @self_label_t}}},
    created_at: :string
  }

  # Built-in record schemas keyed by full NSID, applied when the collection
  # is given as a string.
  @builtin_schemas %{
    "app.bsky.feed.post" => @post_t,
    "app.bsky.feed.like" => @like_t,
    "app.bsky.feed.repost" => @repost_t
  }

  @create_record_t %{
    repo: {:required, :string},
    collection: {:required, :any},
    rkey: {:string, {:max, 15}},
    validate: :boolean,
    swap_commit: :string,
    record: {:required, :any}
  }

  @put_record_t %{
    repo: {:required, :string},
    collection: {:required, :any},
    rkey: {:required, :string},
    validate: :boolean,
    record: {:required, :any},
    swap_record: :string,
    swap_commit: :string
  }

  @doc """
  Create a single new repository record. Requires auth, implemented by PDS.

  The `:collection` param accepts any collection NSID:

    * As an atom (`:post`, `:like`, `:repost`), it must be one of the
      built-in Bluesky collections: it is encoded as `"app.bsky.feed.<name>"`
      and the record is validated against the built-in schema. Any other
      atom fails with `{:error, {:unsupported_collection, collection}}`.
    * As a string, the NSID passes through as-is, so custom-lexicon
      collections work out of the box. The known Bluesky NSIDs
      (`"app.bsky.feed.post"`, `"app.bsky.feed.like"`,
      `"app.bsky.feed.repost"`) are still validated against the built-in
      schemas; records for any other collection are sent unvalidated.

  ## Options

    * `:schema` - a Peri schema used to validate the record before sending,
      for any collection. Overrides the built-in validation when both apply.
      Schema modules generated by `mix proto_rune.gen.lexicons` can be
      passed here directly.

  https://docs.bsky.app/docs/api/com-atproto-repo-create-record
  """
  @spec create_record(map(), map() | keyword(), keyword()) :: {:ok, map()} | {:error, term()}
  def create_record(session, params, opts \\ [])

  def create_record(%{access_jwt: access_token} = session, params, opts) do
    execute_write("com.atproto.repo.createRecord", @create_record_t, session, access_token, params, opts)
  end

  @doc """
  Get a single record from a repository. Does not require auth.

  https://docs.bsky.app/docs/api/com-atproto-repo-get-record
  """
  defquery "com.atproto.repo.getRecord", authenticated: :optional do
    param :repo, {:required, :string}
    param :collection, {:required, :string}
    param :rkey, {:required, :string}
    param :cid, :string
  end

  @doc """
  Write a repository record, creating or updating it as needed. Requires auth, implemented by PDS.

  The `:collection` param follows the same rules as `create_record/3`: atoms
  are restricted to the built-in Bluesky collections, while any NSID string
  passes through as-is. Records for unknown string collections are sent
  unvalidated unless the `:schema` option is given.

  ## Options

    * `:schema` - a Peri schema used to validate the record before sending,
      for any collection. Overrides the built-in validation when both apply.

  https://docs.bsky.app/docs/api/com-atproto-repo-put-record
  """
  @spec put_record(map(), map() | keyword(), keyword()) :: {:ok, map()} | {:error, term()}
  def put_record(session, params, opts \\ [])

  def put_record(%{access_jwt: access_token} = session, params, opts) do
    execute_write("com.atproto.repo.putRecord", @put_record_t, session, access_token, params, opts)
  end

  @doc """
  Delete a repository record, or ensure it doesn't exist. Requires auth, implemented by PDS.

  https://docs.bsky.app/docs/api/com-atproto-repo-delete-record
  """
  defprocedure "com.atproto.repo.deleteRecord", authenticated: true do
    param :repo, {:required, :string}
    param :collection, {:required, :string}
    param :rkey, {:required, :string}
    param :swap_record, :string
    param :swap_commit, :string
  end

  @doc """
  List a range of records in a repository, matching a specific collection. Does not require auth.

  https://docs.bsky.app/docs/api/com-atproto-repo-list-records
  """
  defquery "com.atproto.repo.listRecords", authenticated: :optional do
    param :repo, {:required, :string}
    param :collection, {:required, :string}
    param :limit, {:integer, {:range, {1, 100}}}
    param :cursor, :string
    param :reverse, :boolean
  end

  def encode_collection(col), do: "app.bsky.feed.#{col}"

  def parse_record_schema(%{collection: :post}), do: {:ok, @post_t}
  def parse_record_schema(%{collection: :like}), do: {:ok, @like_t}
  def parse_record_schema(%{collection: :repost}), do: {:ok, @repost_t}

  def parse_record_schema(%{collection: collection}), do: {:error, {:unsupported_collection, collection}}

  defp execute_write(method, schema, session, access_token, params, opts) do
    base_url = Map.get(session, :service_url)
    proc = Procedure.new(method, from: schema, base_url: base_url)

    with {:ok, proc} <- Procedure.put_body(proc, Map.new(params)),
         {:ok, collection, record} <- resolve_collection_and_record(proc.body, opts) do
      %{proc | body: %{proc.body | collection: collection, record: record}}
      |> Procedure.put_header(:authorization, "Bearer #{access_token}")
      |> Client.execute()
    end
  end

  defp resolve_collection_and_record(%{collection: collection, record: record}, opts) do
    do_resolve(collection, record, Keyword.get(opts, :schema))
  end

  # Atom collections keep the closed-enum behavior: only the built-in Bluesky
  # collections are accepted and the record is validated against the built-in
  # schema. A caller-supplied schema overrides the built-in one.
  defp do_resolve(collection, record, nil) when is_atom(collection) do
    with {:ok, schema} <- parse_record_schema(%{collection: collection}),
         {:ok, record} <- Peri.validate(schema, record) do
      {:ok, encode_collection(collection), record}
    end
  end

  defp do_resolve(collection, record, schema) when is_atom(collection) do
    if collection in @collections do
      with {:ok, record} <- Peri.validate(schema, record) do
        {:ok, encode_collection(collection), record}
      end
    else
      {:error, {:unsupported_collection, collection}}
    end
  end

  # String collections pass through as-is. Known Bluesky NSIDs keep the
  # built-in validation; anything else is sent unvalidated by default.
  defp do_resolve(collection, record, nil) when is_binary(collection) do
    case Map.get(@builtin_schemas, collection) do
      nil ->
        {:ok, collection, record}

      schema ->
        with {:ok, record} <- Peri.validate(schema, record) do
          {:ok, collection, record}
        end
    end
  end

  defp do_resolve(collection, record, schema) when is_binary(collection) do
    with {:ok, record} <- Peri.validate(schema, record) do
      {:ok, collection, record}
    end
  end

  defp do_resolve(collection, _record, _schema), do: {:error, {:unsupported_collection, collection}}

  @doc """
  Upload a blob of binary data to be stored with the account, for later
  reference in repository records (for example, a profile avatar).
  Requires auth, implemented by PDS.

  Returns `{:ok, %{blob: blob}}` where `blob` is a blob reference map
  suitable for embedding in a record.

  https://docs.bsky.app/docs/api/com-atproto-repo-upload-blob

  ## Examples

      {:ok, %{blob: blob}} = Repo.upload_blob(session, image_data, "image/png")
  """
  @spec upload_blob(Session.t(), binary(), String.t()) :: {:ok, map()} | {:error, term()}
  def upload_blob(session, data, content_type) when is_binary(data) and is_binary(content_type) do
    base_url = Session.service_url(session) || Config.default_base_url()
    url = Path.join(base_url, "com.atproto.repo.uploadBlob")

    with {:ok, headers, session} <- Session.authorization_headers(session, "POST", url) do
      "com.atproto.repo.uploadBlob"
      |> Procedure.new(base_url: base_url)
      |> Procedure.put_raw_body(data)
      |> Procedure.put_header("content-type", content_type)
      |> then(&%{&1 | headers: Map.merge(&1.headers, headers)})
      |> Client.execute(session: session)
    end
  end
end
