# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestAccountDelete.Main do
  @moduledoc """
  **main** (procedure)

  Initiate a user account deletion via email.
  """

  @type input :: any()
  @type output :: any()
end
