# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.SendMessageBatch.BatchItem do
  @moduledoc """
  **batchItem** (object/record)

  No description.
  """

  @enforce_keys [:convoId, :message]
  defstruct convoId: nil, message: nil

  @type t :: %__MODULE__{
          convoId: String.t(),
          message: ProtoRune.Chat.Bsky.Convo.Defs.MessageInput.t()
        }
end
