# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.SendMessageBatch.Main do
  @moduledoc """
  **main** (procedure)

  No description.
  """

  @type input :: any()
  @type output :: any()
end
