# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetFollows.Main do
  @moduledoc """
  **main** (query)

  Enumerates accounts which a specified account (actor) follows.
  """

  @type input :: any()
  @type output :: any()
end
