# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.View do
  @moduledoc """
  **view** (object/record)

  No description.
  """

  @enforce_keys [:record]
  defstruct record: nil

  @type t :: %__MODULE__{
          record:
            ProtoRune.App.Bsky.Embed.Record.ViewRecord.t()
            | ProtoRune.App.Bsky.Embed.Record.ViewNotFound.t()
            | ProtoRune.App.Bsky.Embed.Record.ViewBlocked.t()
            | ProtoRune.App.Bsky.Embed.Record.ViewDetached.t()
            | ProtoRune.App.Bsky.Feed.Defs.GeneratorView.t()
            | ProtoRune.App.Bsky.Graph.Defs.ListView.t()
            | ProtoRune.App.Bsky.Labeler.Defs.LabelerView.t()
            | ProtoRune.App.Bsky.Graph.Defs.StarterPackViewBasic.t()
        }
end
