# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewDetached do
  @moduledoc """
  **viewDetached** (object/record)

  No description.
  """

  @enforce_keys [:uri, :detached]
  defstruct detached: nil, uri: nil

  @type t :: %__MODULE__{
          detached: boolean(),
          uri: String.t()
        }
end
