# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewBlocked do
  @moduledoc """
  **viewBlocked** (object/record)

  No description.
  """

  @enforce_keys [:uri, :blocked, :author]
  defstruct author: nil, blocked: nil, uri: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Feed.Defs.BlockedAuthor.t(),
          blocked: boolean(),
          uri: String.t()
        }
end
