# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewRecord do
  @moduledoc """
  **viewRecord** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :author, :value, :indexedAt]
  defstruct author: nil,
            cid: nil,
            embeds: nil,
            indexedAt: nil,
            labels: nil,
            likeCount: nil,
            quoteCount: nil,
            replyCount: nil,
            repostCount: nil,
            uri: nil,
            value: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          cid: String.t(),
          embeds:
            list(
              ProtoRune.App.Bsky.Embed.Images.View.t()
              | ProtoRune.App.Bsky.Embed.Video.View.t()
              | ProtoRune.App.Bsky.Embed.External.View.t()
              | ProtoRune.App.Bsky.Embed.Record.View.t()
              | ProtoRune.App.Bsky.Embed.RecordWithMedia.View.t()
            ),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          likeCount: integer(),
          quoteCount: integer(),
          replyCount: integer(),
          repostCount: integer(),
          uri: String.t(),
          value: any()
        }
end
