# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewNotFound do
  @moduledoc """
  **viewNotFound** (object/record)

  No description.
  """

  @enforce_keys [:uri, :notFound]
  defstruct notFound: nil, uri: nil

  @type t :: %__MODULE__{
          notFound: boolean(),
          uri: String.t()
        }
end
