# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Block.Main do
  @moduledoc """
  **main** (object/record)

  Record declaring a 'block' relationship against another account. NOTE: blocks are public in Bluesky; see blog posts for details.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
