# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetBlocks.Main do
  @moduledoc """
  **main** (query)

  Enumerates which accounts the requesting account is currently blocking. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
