# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CheckAccountStatus.Main do
  @moduledoc """
  **main** (query)

  Returns the status of an account, especially as pertaining to import or recovery. Can be called many times over the course of an account migration. Requires auth and can only be called pertaining to oneself.
  """

  @type input :: any()
  @type output :: any()
end
