# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ActivateAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: Activates a currently deactivated account. Used to finalize account migration after the account's repo is imported and identity is setup.
  """
end
