# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CheckAccountStatus do
  @moduledoc """
  Generated query module for main

  **Description**: Returns the status of an account, especially as pertaining to import or recovery. Can be called many times over the course of an account migration. Requires auth and can only be called pertaining to oneself.
  """

  @type output :: %{
          activated: boolean(),
          expected_blobs: integer(),
          imported_blobs: integer(),
          indexed_records: integer(),
          private_state_values: integer(),
          repo_blocks: integer(),
          repo_commit: String.t(),
          repo_rev: String.t(),
          valid_did: boolean()
        }
end
