# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ConfirmEmail do
  @moduledoc """
  Generated procedure module for main

  **Description**: Confirm an email using a token from com.atproto.server.requestEmailConfirmation.
  """

  @type input :: %{email: String.t(), token: String.t()}
  @type error ::
          ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorAccountNotFound.t()
          | ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorExpiredToken.t()
          | ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorInvalidToken.t()
          | ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorInvalidEmail.t()
end
