# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAppPassword do
  @moduledoc """
  Generated procedure module for main

  **Description**: Create an App Password.
  """

  @type output :: ProtoRune.Com.Atproto.Server.CreateAppPassword.AppPassword.t()
  @type input :: %{name: String.t(), privileged: boolean()}
  @type error :: ProtoRune.Com.Atproto.Server.CreateAppPassword.MainErrorAccountTakedown.t()
end
