# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateInviteCode do
  @moduledoc """
  Generated procedure module for main

  **Description**: Create an invite code.
  """

  @type output :: %{code: String.t()}
  @type input :: %{for_account: String.t(), use_count: integer()}
end
