# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: Create an account. Implemented by PDS.
  """

  @type output :: %{
          access_jwt: String.t(),
          did: String.t(),
          did_doc: any(),
          handle: String.t(),
          refresh_jwt: String.t()
        }
  @type input :: %{
          did: String.t(),
          email: String.t(),
          handle: String.t(),
          invite_code: String.t(),
          password: String.t(),
          plc_op: any(),
          recovery_key: String.t(),
          verification_code: String.t(),
          verification_phone: String.t()
        }
  @type error ::
          ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidHandle.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidPassword.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidInviteCode.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorHandleNotAvailable.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorUnsupportedDomain.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorUnresolvableDid.t()
          | ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorIncompatibleDidDoc.t()
end
