# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeactivateAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: Deactivates a currently active account. Stops serving of repo, and future writes to repo until reactivated. Used to finalize account migration with the old host after the account has been activated on the new host.
  """

  @type input :: %{delete_after: String.t()}
end
