# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeleteAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete an actor's account with a token and password. Can only be called after requesting a deletion token. Requires auth.
  """

  @type input :: %{did: String.t(), password: String.t(), token: String.t()}
  @type error ::
          ProtoRune.Com.Atproto.Server.DeleteAccount.MainErrorExpiredToken.t()
          | ProtoRune.Com.Atproto.Server.DeleteAccount.MainErrorInvalidToken.t()
end
