# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeleteSession do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete the current session. Requires auth.
  """
end
