# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DescribeServer do
  @moduledoc """
  Generated query module for main

  **Description**: Describes the server's account creation requirements and capabilities. Implemented by PDS.
  """

  @type output :: %{
          available_user_domains: list(String.t()),
          contact: ProtoRune.Com.Atproto.Server.DescribeServer.Contact.t(),
          did: String.t(),
          invite_code_required: boolean(),
          links: ProtoRune.Com.Atproto.Server.DescribeServer.Links.t(),
          phone_verification_required: boolean()
        }
end
