# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetServiceAuth do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{aud: String.t(), exp: integer(), lxm: String.t()}
end
