# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetAccountInviteCodes do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{create_available: boolean(), include_used: boolean()}
end
