# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetSession do
  @moduledoc """
  Generated query module for main

  **Description**: Get information about the current auth session. Requires auth.
  """

  @type output :: %{
          active: boolean(),
          did: String.t(),
          did_doc: any(),
          email: String.t(),
          email_auth_factor: boolean(),
          email_confirmed: boolean(),
          handle: String.t(),
          status: :takendown | :suspended | :deactivated
        }
end
