# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ListAppPasswords do
  @moduledoc """
  Generated query module for main

  **Description**: List all App Passwords.
  """

  @type output :: %{
          passwords: list(ProtoRune.Com.Atproto.Server.ListAppPasswords.AppPassword.t())
        }
  @type error :: ProtoRune.Com.Atproto.Server.ListAppPasswords.MainErrorAccountTakedown.t()
end
