# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RefreshSession do
  @moduledoc """
  Generated procedure module for main

  **Description**: Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
  """

  @type output :: %{
          access_jwt: String.t(),
          active: boolean(),
          did: String.t(),
          did_doc: any(),
          handle: String.t(),
          refresh_jwt: String.t(),
          status: :takendown | :suspended | :deactivated
        }
  @type error :: ProtoRune.Com.Atproto.Server.RefreshSession.MainErrorAccountTakedown.t()
end
