# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestEmailUpdate do
  @moduledoc """
  Generated procedure module for main

  **Description**: Request a token in order to update email.
  """

  @type output :: %{token_required: boolean()}
end
