# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestEmailConfirmation do
  @moduledoc """
  Generated procedure module for main

  **Description**: Request an email with a code to confirm ownership of email.
  """
end
