# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestPasswordReset do
  @moduledoc """
  Generated procedure module for main

  **Description**: Initiate a user account password reset via email.
  """

  @type input :: %{email: String.t()}
end
