# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestAccountDelete do
  @moduledoc """
  Generated procedure module for main

  **Description**: Initiate a user account deletion via email.
  """
end
