# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ResetPassword do
  @moduledoc """
  Generated procedure module for main

  **Description**: Reset a user account password using a token.
  """

  @type input :: %{password: String.t(), token: String.t()}
  @type error ::
          ProtoRune.Com.Atproto.Server.ResetPassword.MainErrorExpiredToken.t()
          | ProtoRune.Com.Atproto.Server.ResetPassword.MainErrorInvalidToken.t()
end
