# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RevokeAppPassword do
  @moduledoc """
  Generated procedure module for main

  **Description**: Revoke an App Password by name.
  """

  @type input :: %{name: String.t()}
end
