# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetRepostedBy.Main do
  @moduledoc """
  **main** (query)

  Get a list of reposts for a given post.
  """

  @type input :: any()
  @type output :: any()
end
