# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Setting.UpsertOption.Main do
  @moduledoc """
  **main** (procedure)

  Create or update setting option
  """

  @type input :: any()
  @type output :: any()
end
