# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewDetached do
  @moduledoc """
  Generated schema for viewDetached

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :detached]
  defstruct detached: nil, uri: nil

  @type t :: %__MODULE__{
          detached: boolean(),
          uri: String.t()
        }
end
