# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record.ViewNotFound do
  @moduledoc """
  Generated schema for viewNotFound

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :not_found]
  defstruct not_found: nil, uri: nil

  @type t :: %__MODULE__{
          not_found: boolean(),
          uri: String.t()
        }
end
