# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetPosts.Main do
  @moduledoc """
  **main** (query)

  Gets post views for a specified list of posts (by AT-URI). This is sometimes referred to as 'hydrating' a 'feed skeleton'.
  """

  @type input :: any()
  @type output :: any()
end
