# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListViewBasic do
  @moduledoc """
  **listViewBasic** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :name, :purpose]
  defstruct avatar: nil,
            cid: nil,
            indexedAt: nil,
            labels: nil,
            listItemCount: nil,
            name: nil,
            purpose: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          avatar: String.t(),
          cid: String.t(),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          listItemCount: integer(),
          name: String.t(),
          purpose: ProtoRune.Types.app_bsky_graph_defs_list_purpose(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Graph.Defs.ListViewerState.t()
        }
end
