# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListView do
  @moduledoc """
  **listView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :creator, :name, :purpose, :indexedAt]
  defstruct avatar: nil,
            cid: nil,
            creator: nil,
            description: nil,
            descriptionFacets: nil,
            indexedAt: nil,
            labels: nil,
            listItemCount: nil,
            name: nil,
            purpose: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          avatar: String.t(),
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          description: String.t(),
          descriptionFacets: list(ProtoRune.App.Bsky.Richtext.Facet.Main.t()),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          listItemCount: integer(),
          name: String.t(),
          purpose: ProtoRune.Types.app_bsky_graph_defs_list_purpose(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Graph.Defs.ListViewerState.t()
        }
end
