# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListItemView do
  @moduledoc """
  **listItemView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :subject]
  defstruct subject: nil, uri: nil

  @type t :: %__MODULE__{
          subject: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          uri: String.t()
        }
end
