# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListViewerState do
  @moduledoc """
  **listViewerState** (object/record)

  No description.
  """

  defstruct blocked: nil, muted: nil

  @type t :: %__MODULE__{
          blocked: String.t(),
          muted: boolean()
        }
end
