# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.NotFoundActor do
  @moduledoc """
  **notFoundActor** (object/record)

  indicates that a handle or DID could not be resolved
  """

  @enforce_keys [:actor, :notFound]
  defstruct actor: nil, notFound: nil

  @type t :: %__MODULE__{
          actor: String.t(),
          notFound: boolean()
        }
end
