# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.StarterPackViewBasic do
  @moduledoc """
  **starterPackViewBasic** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :record, :creator, :indexedAt]
  defstruct cid: nil,
            creator: nil,
            indexedAt: nil,
            joinedAllTimeCount: nil,
            joinedWeekCount: nil,
            labels: nil,
            listItemCount: nil,
            record: nil,
            uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          indexedAt: String.t(),
          joinedAllTimeCount: integer(),
          joinedWeekCount: integer(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          listItemCount: integer(),
          record: any(),
          uri: String.t()
        }
end
