# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.StarterPackView do
  @moduledoc """
  **starterPackView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :record, :creator, :indexedAt]
  defstruct cid: nil,
            creator: nil,
            feeds: nil,
            indexedAt: nil,
            joinedAllTimeCount: nil,
            joinedWeekCount: nil,
            labels: nil,
            list: nil,
            listItemsSample: nil,
            record: nil,
            uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          feeds: list(ProtoRune.App.Bsky.Feed.Defs.GeneratorView.t()),
          indexedAt: String.t(),
          joinedAllTimeCount: integer(),
          joinedWeekCount: integer(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          list: ProtoRune.App.Bsky.Graph.Defs.ListViewBasic.t(),
          listItemsSample: list(ProtoRune.App.Bsky.Graph.Defs.ListItemView.t()),
          record: any(),
          uri: String.t()
        }
end
