# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.CheckSignupQueue.Main do
  @moduledoc """
  **main** (query)

  Check accounts location in signup queue.
  """

  @type input :: any()
  @type output :: any()
end
