# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.NotifyOfUpdate.Main do
  @moduledoc """
  **main** (procedure)

  Notify a crawling service of a recent update, and that crawling should resume. Intended use is after a gap between repo stream events caused the crawling service to disconnect. Does not require auth; implemented by Relay.
  """

  @type input :: any()
  @type output :: any()
end
