# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.QuerySets.Main do
  @moduledoc """
  **main** (query)

  Query available sets
  """

  @type input :: any()
  @type output :: any()
end
