# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Setting.RemoveOptions.Main do
  @moduledoc """
  **main** (procedure)

  Delete settings by key
  """

  @type input :: any()
  @type output :: any()
end
