# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.GetRecord.Main do
  @moduledoc """
  **main** (query)

  Get a single record from a repository. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
