# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetCheckout.Main do
  @moduledoc """
  **main** (query)

  DEPRECATED - please use com.atproto.sync.getRepo instead
  """

  @type input :: any()
  @type output :: any()
end
