# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.GetUnreadCount.Main do
  @moduledoc """
  **main** (query)

  Count the number of unread notifications for the requesting account. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
