# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.ListRepos.Main do
  @moduledoc """
  **main** (query)

  Enumerates all the DID, rev, and commit CID for all repos hosted by this service. Does not require auth; implemented by PDS and Relay.
  """

  @type input :: any()
  @type output :: any()
end
