# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ListAppPasswords.AppPassword do
  @moduledoc """
  **appPassword** (object/record)

  No description.
  """

  @enforce_keys [:name, :createdAt]
  defstruct createdAt: nil, name: nil, privileged: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          name: String.t(),
          privileged: boolean()
        }
end
