# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ListAppPasswords.Main do
  @moduledoc """
  **main** (query)

  List all App Passwords.
  """

  @type input :: any()
  @type output :: any()
end
