# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorUnsupportedDomain do
  @moduledoc """
  Generated schema for mainErrorUnsupportedDomain

  **Description**: No description provided.
  """

  @type t :: any()
end
