# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidHandle do
  @moduledoc """
  Generated schema for mainErrorInvalidHandle

  **Description**: No description provided.
  """

  @type t :: any()
end
