# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorIncompatibleDidDoc do
  @moduledoc """
  Generated schema for mainErrorIncompatibleDidDoc

  **Description**: No description provided.
  """

  @type t :: any()
end
