# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorUnresolvableDid do
  @moduledoc """
  Generated schema for mainErrorUnresolvableDid

  **Description**: No description provided.
  """

  @type t :: any()
end
