# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorHandleNotAvailable do
  @moduledoc """
  Generated schema for mainErrorHandleNotAvailable

  **Description**: No description provided.
  """

  @type t :: any()
end
