# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidPassword do
  @moduledoc """
  Generated schema for mainErrorInvalidPassword

  **Description**: No description provided.
  """

  @type t :: any()
end
