# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.MainErrorInvalidInviteCode do
  @moduledoc """
  Generated schema for mainErrorInvalidInviteCode

  **Description**: No description provided.
  """

  @type t :: any()
end
