# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetSuggestionsSkeleton.Main do
  @moduledoc """
  **main** (query)

  Get a skeleton of suggested actors. Intended to be called and then hydrated through app.bsky.actor.getSuggestions
  """

  @type input :: any()
  @type output :: any()
end
