# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Signature.Defs.SigDetail do
  @moduledoc """
  **sigDetail** (object/record)

  No description.
  """

  @enforce_keys [:property, :value]
  defstruct property: nil, value: nil

  @type t :: %__MODULE__{
          property: String.t(),
          value: String.t()
        }
end
