# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateAccount.Main do
  @moduledoc """
  **main** (procedure)

  Create an account. Implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
