# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RevokeAppPassword.Main do
  @moduledoc """
  **main** (procedure)

  Revoke an App Password by name.
  """

  @type input :: any()
  @type output :: any()
end
