# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Service.Main do
  @moduledoc """
  **main** (object/record)

  A declaration of the existence of labeler service.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
