# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.SearchAccounts.Main do
  @moduledoc """
  **main** (query)

  Get list of accounts that matches your search query.
  """

  @type input :: any()
  @type output :: any()
end
