# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetBlocks do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cids: list(String.t()), did: String.t()}
end
