# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetBlob do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cid: String.t(), did: String.t()}
end
