# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetRecord do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{collection: String.t(), commit: String.t(), did: String.t(), rkey: String.t()}
end
