# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.ListBlobs do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cursor: String.t(), did: String.t(), limit: integer(), since: String.t()}
end
