# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.RequestCrawl do
  @moduledoc """
  Generated procedure module for main

  **Description**: Request a service to persistently crawl hosted repos. Expected use is new PDS instances declaring their existence to Relays. Does not require auth.
  """

  @type input :: %{hostname: String.t()}
end
