# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.UpdateHandle.Main do
  @moduledoc """
  **main** (procedure)

  Updates the current account's handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
  """

  @type input :: any()
  @type output :: any()
end
