# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.CheckSignupQueue do
  @moduledoc """
  Generated query module for main

  **Description**: Check accounts location in signup queue.
  """

  @type output :: %{activated: boolean(), estimated_time_ms: integer(), place_in_queue: integer()}
end
