# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.FetchLabels do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{limit: integer(), since: integer()}
end
