# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.RequestPhoneVerification do
  @moduledoc """
  Generated procedure module for main

  **Description**: Request a verification code to be sent to the supplied phone number
  """

  @type input :: %{phone_number: String.t()}
end
