# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.AccountHosting do
  @moduledoc """
  **accountHosting** (object/record)

  No description.
  """

  @enforce_keys [:status]
  defstruct createdAt: nil,
            deactivatedAt: nil,
            deletedAt: nil,
            reactivatedAt: nil,
            status: nil,
            updatedAt: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          deactivatedAt: String.t(),
          deletedAt: String.t(),
          reactivatedAt: String.t(),
          status: :takendown | :suspended | :deleted | :deactivated | :unknown,
          updatedAt: String.t()
        }
end
