# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.BlobView do
  @moduledoc """
  **blobView** (object/record)

  No description.
  """

  @enforce_keys [:cid, :mimeType, :size, :createdAt]
  defstruct cid: nil, createdAt: nil, details: nil, mimeType: nil, moderation: nil, size: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          createdAt: String.t(),
          details:
            ProtoRune.Tools.Ozone.Moderation.Defs.ImageDetails.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.VideoDetails.t(),
          mimeType: String.t(),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.Moderation.t(),
          size: integer()
        }
end
