# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.IdentityEvent do
  @moduledoc """
  **identityEvent** (object/record)

  Logs identity related events on a repo subject. Normally captured by automod from the firehose and emitted to ozone for historical tracking.
  """

  @enforce_keys [:timestamp]
  defstruct comment: nil, handle: nil, pdsHost: nil, timestamp: nil, tombstone: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          handle: String.t(),
          pdsHost: String.t(),
          timestamp: String.t(),
          tombstone: boolean()
        }
end
