# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ImageDetails do
  @moduledoc """
  **imageDetails** (object/record)

  No description.
  """

  @enforce_keys [:width, :height]
  defstruct height: nil, width: nil

  @type t :: %__MODULE__{
          height: integer(),
          width: integer()
        }
end
