# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter do
  @moduledoc """
  **modEventUnmuteReporter** (object/record)

  Unmute incoming reports from an account
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
