# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel do
  @moduledoc """
  **modEventLabel** (object/record)

  Apply/Negate labels on a subject
  """

  @enforce_keys [:createLabelVals, :negateLabelVals]
  defstruct comment: nil, createLabelVals: nil, negateLabelVals: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          createLabelVals: list(String.t()),
          negateLabelVals: list(String.t())
        }
end
