# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventViewDetail do
  @moduledoc """
  **modEventViewDetail** (object/record)

  No description.
  """

  @enforce_keys [:id, :event, :subject, :subjectBlobs, :createdBy, :createdAt]
  defstruct createdAt: nil, createdBy: nil, event: nil, id: nil, subject: nil, subjectBlobs: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          createdBy: String.t(),
          event:
            ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReverseTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventComment.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEscalate.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventDivert.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTag.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.AccountEvent.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.IdentityEvent.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.RecordEvent.t(),
          id: integer(),
          subject:
            ProtoRune.Tools.Ozone.Moderation.Defs.RepoView.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.RepoViewNotFound.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.RecordView.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.RecordViewNotFound.t(),
          subjectBlobs: list(ProtoRune.Tools.Ozone.Moderation.Defs.BlobView.t())
        }
end
