# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport do
  @moduledoc """
  **modEventReport** (object/record)

  Report a subject
  """

  @enforce_keys [:reportType]
  defstruct comment: nil, isReporterMuted: nil, reportType: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          isReporterMuted: boolean(),
          reportType: ProtoRune.Types.com_atproto_moderation_defs_reason_type()
        }
end
