# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge do
  @moduledoc """
  **modEventAcknowledge** (object/record)

  No description.
  """

  defstruct acknowledgeAccountSubjects: nil, comment: nil

  @type t :: %__MODULE__{
          acknowledgeAccountSubjects: boolean(),
          comment: String.t()
        }
end
