# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEscalate do
  @moduledoc """
  **modEventEscalate** (object/record)

  No description.
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
