# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail do
  @moduledoc """
  **modEventEmail** (object/record)

  Keep a log of outgoing email to a user
  """

  @enforce_keys [:subjectLine]
  defstruct comment: nil, content: nil, subjectLine: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          content: String.t(),
          subjectLine: String.t()
        }
end
