# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventView do
  @moduledoc """
  **modEventView** (object/record)

  No description.
  """

  @enforce_keys [:id, :event, :subject, :subjectBlobCids, :createdBy, :createdAt]
  defstruct createdAt: nil,
            createdBy: nil,
            creatorHandle: nil,
            event: nil,
            id: nil,
            subject: nil,
            subjectBlobCids: nil,
            subjectHandle: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          createdBy: String.t(),
          creatorHandle: String.t(),
          event:
            ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReverseTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventComment.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEscalate.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventDivert.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTag.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.AccountEvent.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.IdentityEvent.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.RecordEvent.t(),
          id: integer(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.Main.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.MessageRef.t(),
          subjectBlobCids: list(String.t()),
          subjectHandle: String.t()
        }
end
