# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMuteReporter do
  @moduledoc """
  **modEventMuteReporter** (object/record)

  Mute incoming reports from an account
  """

  defstruct comment: nil, durationInHours: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          durationInHours: integer()
        }
end
