# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal do
  @moduledoc """
  **modEventResolveAppeal** (object/record)

  Resolve appeal on a subject
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
