# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventDivert do
  @moduledoc """
  **modEventDivert** (object/record)

  Divert a record's blobs to a 3rd party service for further scanning/tagging
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
