# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMute do
  @moduledoc """
  **modEventMute** (object/record)

  Mute incoming reports on a subject
  """

  @enforce_keys [:durationInHours]
  defstruct comment: nil, durationInHours: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          durationInHours: integer()
        }
end
