# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.Moderation do
  @moduledoc """
  **moderation** (object/record)

  No description.
  """

  defstruct subjectStatus: nil

  @type t :: %__MODULE__{
          subjectStatus: ProtoRune.Tools.Ozone.Moderation.Defs.SubjectStatusView.t()
        }
end
