# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModerationDetail do
  @moduledoc """
  **moderationDetail** (object/record)

  No description.
  """

  defstruct subjectStatus: nil

  @type t :: %__MODULE__{
          subjectStatus: ProtoRune.Tools.Ozone.Moderation.Defs.SubjectStatusView.t()
        }
end
