# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RecordsStats do
  @moduledoc """
  **recordsStats** (object/record)

  Statistics about a set of record subject items
  """

  defstruct appealedCount: nil,
            escalatedCount: nil,
            pendingCount: nil,
            processedCount: nil,
            reportedCount: nil,
            subjectCount: nil,
            takendownCount: nil,
            totalReports: nil

  @type t :: %__MODULE__{
          appealedCount: integer(),
          escalatedCount: integer(),
          pendingCount: integer(),
          processedCount: integer(),
          reportedCount: integer(),
          subjectCount: integer(),
          takendownCount: integer(),
          totalReports: integer()
        }
end
