# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RecordView do
  @moduledoc """
  **recordView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :value, :blobCids, :indexedAt, :moderation, :repo]
  defstruct blobCids: nil,
            cid: nil,
            indexedAt: nil,
            moderation: nil,
            repo: nil,
            uri: nil,
            value: nil

  @type t :: %__MODULE__{
          blobCids: list(String.t()),
          cid: String.t(),
          indexedAt: String.t(),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.Moderation.t(),
          repo: ProtoRune.Tools.Ozone.Moderation.Defs.RepoView.t(),
          uri: String.t(),
          value: any()
        }
end
