# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RecordHosting do
  @moduledoc """
  **recordHosting** (object/record)

  No description.
  """

  @enforce_keys [:status]
  defstruct createdAt: nil, deletedAt: nil, status: nil, updatedAt: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          deletedAt: String.t(),
          status: :deleted | :unknown,
          updatedAt: String.t()
        }
end
