# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RecordEvent do
  @moduledoc """
  **recordEvent** (object/record)

  Logs lifecycle event on a record subject. Normally captured by automod from the firehose and emitted to ozone for historical tracking.
  """

  @enforce_keys [:timestamp, :op]
  defstruct cid: nil, comment: nil, op: nil, timestamp: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          comment: String.t(),
          op: :create | :update | :delete,
          timestamp: String.t()
        }
end
