# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RepoView do
  @moduledoc """
  **repoView** (object/record)

  No description.
  """

  @enforce_keys [:did, :handle, :relatedRecords, :indexedAt, :moderation]
  defstruct deactivatedAt: nil,
            did: nil,
            email: nil,
            handle: nil,
            indexedAt: nil,
            inviteNote: nil,
            invitedBy: nil,
            invitesDisabled: nil,
            moderation: nil,
            relatedRecords: nil,
            threatSignatures: nil

  @type t :: %__MODULE__{
          deactivatedAt: String.t(),
          did: String.t(),
          email: String.t(),
          handle: String.t(),
          indexedAt: String.t(),
          inviteNote: String.t(),
          invitedBy: ProtoRune.Com.Atproto.Server.Defs.InviteCode.t(),
          invitesDisabled: boolean(),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.Moderation.t(),
          relatedRecords: list(any()),
          threatSignatures: list(ProtoRune.Com.Atproto.Admin.Defs.ThreatSignature.t())
        }
end
