# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RepoViewDetail do
  @moduledoc """
  **repoViewDetail** (object/record)

  No description.
  """

  alias ProtoRune.Com.Atproto.Server.Defs.InviteCode

  @enforce_keys [:did, :handle, :relatedRecords, :indexedAt, :moderation]
  defstruct deactivatedAt: nil,
            did: nil,
            email: nil,
            emailConfirmedAt: nil,
            handle: nil,
            indexedAt: nil,
            inviteNote: nil,
            invitedBy: nil,
            invites: nil,
            invitesDisabled: nil,
            labels: nil,
            moderation: nil,
            relatedRecords: nil,
            threatSignatures: nil

  @type t :: %__MODULE__{
          deactivatedAt: String.t(),
          did: String.t(),
          email: String.t(),
          emailConfirmedAt: String.t(),
          handle: String.t(),
          indexedAt: String.t(),
          inviteNote: String.t(),
          invitedBy: InviteCode.t(),
          invites: list(InviteCode.t()),
          invitesDisabled: boolean(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.ModerationDetail.t(),
          relatedRecords: list(any()),
          threatSignatures: list(ProtoRune.Com.Atproto.Admin.Defs.ThreatSignature.t())
        }
end
