# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.VideoDetails do
  @moduledoc """
  **videoDetails** (object/record)

  No description.
  """

  @enforce_keys [:width, :height, :length]
  defstruct height: nil, length: nil, width: nil

  @type t :: %__MODULE__{
          height: integer(),
          length: integer(),
          width: integer()
        }
end
