# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.RequestPhoneVerification.Main do
  @moduledoc """
  **main** (procedure)

  Request a verification code to be sent to the supplied phone number
  """

  @type input :: any()
  @type output :: any()
end
