# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetFeedGenerators.Main do
  @moduledoc """
  **main** (query)

  Get information about a list of feed generators.
  """

  @type input :: any()
  @type output :: any()
end
