# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.AddMember.Main do
  @moduledoc """
  **main** (procedure)

  Add a member to the ozone team. Requires admin role.
  """

  @type input :: any()
  @type output :: any()
end
