# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.AdultContentPref do
  @moduledoc """
  **adultContentPref** (object/record)

  No description.
  """

  @enforce_keys [:enabled]
  defstruct enabled: nil

  @type t :: %__MODULE__{
          enabled: boolean()
        }
end
