# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.BskyAppStatePref do
  @moduledoc """
  **bskyAppStatePref** (object/record)

  A grab bag of state that's specific to the bsky.app program. Third-party apps shouldn't use this.
  """

  defstruct activeProgressGuide: nil, nuxs: nil, queuedNudges: nil

  @type t :: %__MODULE__{
          activeProgressGuide: ProtoRune.App.Bsky.Actor.Defs.BskyAppProgressGuide.t(),
          nuxs: list(ProtoRune.App.Bsky.Actor.Defs.Nux.t()),
          queuedNudges: list(String.t())
        }
end
