# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ContentLabelPref do
  @moduledoc """
  **contentLabelPref** (object/record)

  No description.
  """

  @enforce_keys [:label, :visibility]
  defstruct label: nil, labelerDid: nil, visibility: nil

  @type t :: %__MODULE__{
          label: String.t(),
          labelerDid: String.t(),
          visibility: :ignore | :show | :warn | :hide
        }
end
