# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.FeedViewPref do
  @moduledoc """
  **feedViewPref** (object/record)

  No description.
  """

  @enforce_keys [:feed]
  defstruct feed: nil,
            hideQuotePosts: nil,
            hideReplies: nil,
            hideRepliesByLikeCount: nil,
            hideRepliesByUnfollowed: nil,
            hideReposts: nil

  @type t :: %__MODULE__{
          feed: String.t(),
          hideQuotePosts: boolean(),
          hideReplies: boolean(),
          hideRepliesByLikeCount: integer(),
          hideRepliesByUnfollowed: boolean(),
          hideReposts: boolean()
        }
end
