# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.HiddenPostsPref do
  @moduledoc """
  **hiddenPostsPref** (object/record)

  No description.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(String.t())
        }
end
