# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.InterestsPref do
  @moduledoc """
  **interestsPref** (object/record)

  No description.
  """

  @enforce_keys [:tags]
  defstruct tags: nil

  @type t :: %__MODULE__{
          tags: list(String.t())
        }
end
