# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.LabelersPref do
  @moduledoc """
  **labelersPref** (object/record)

  No description.
  """

  @enforce_keys [:labelers]
  defstruct labelers: nil

  @type t :: %__MODULE__{
          labelers: list(ProtoRune.App.Bsky.Actor.Defs.LabelerPrefItem.t())
        }
end
