# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.MutedWordsPref do
  @moduledoc """
  **mutedWordsPref** (object/record)

  No description.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(ProtoRune.App.Bsky.Actor.Defs.MutedWord.t())
        }
end
