# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.MutedWord do
  @moduledoc """
  **mutedWord** (object/record)

  A word that the account owner has muted.
  """

  @enforce_keys [:value, :targets]
  defstruct actorTarget: nil, expiresAt: nil, id: nil, targets: nil, value: nil

  @type t :: %__MODULE__{
          actorTarget: :all | :"exclude-following",
          expiresAt: String.t(),
          id: String.t(),
          targets: list(ProtoRune.Types.app_bsky_actor_defs_muted_word_target()),
          value: String.t()
        }
end
