# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.Nux do
  @moduledoc """
  **nux** (object/record)

  A new user experiences (NUX) storage object
  """

  @enforce_keys [:id, :completed]
  defstruct completed: nil, data: nil, expiresAt: nil, id: nil

  @type t :: %__MODULE__{
          completed: boolean(),
          data: String.t(),
          expiresAt: String.t(),
          id: String.t()
        }
end
