# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.PersonalDetailsPref do
  @moduledoc """
  **personalDetailsPref** (object/record)

  No description.
  """

  defstruct birthDate: nil

  @type t :: %__MODULE__{
          birthDate: String.t()
        }
end
