# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated do
  @moduledoc """
  **profileAssociated** (object/record)

  No description.
  """

  defstruct chat: nil, feedgens: nil, labeler: nil, lists: nil, starterPacks: nil

  @type t :: %__MODULE__{
          chat: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociatedChat.t(),
          feedgens: integer(),
          labeler: boolean(),
          lists: integer(),
          starterPacks: integer()
        }
end
