# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic do
  @moduledoc """
  **profileViewBasic** (object/record)

  No description.
  """

  @enforce_keys [:did, :handle]
  defstruct associated: nil,
            avatar: nil,
            createdAt: nil,
            did: nil,
            displayName: nil,
            handle: nil,
            labels: nil,
            viewer: nil

  @type t :: %__MODULE__{
          associated: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated.t(),
          avatar: String.t(),
          createdAt: String.t(),
          did: String.t(),
          displayName: String.t(),
          handle: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
