# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileViewDetailed do
  @moduledoc """
  **profileViewDetailed** (object/record)

  No description.
  """

  @enforce_keys [:did, :handle]
  defstruct associated: nil,
            avatar: nil,
            banner: nil,
            createdAt: nil,
            description: nil,
            did: nil,
            displayName: nil,
            followersCount: nil,
            followsCount: nil,
            handle: nil,
            indexedAt: nil,
            joinedViaStarterPack: nil,
            labels: nil,
            pinnedPost: nil,
            postsCount: nil,
            viewer: nil

  @type t :: %__MODULE__{
          associated: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated.t(),
          avatar: String.t(),
          banner: String.t(),
          createdAt: String.t(),
          description: String.t(),
          did: String.t(),
          displayName: String.t(),
          followersCount: integer(),
          followsCount: integer(),
          handle: String.t(),
          indexedAt: String.t(),
          joinedViaStarterPack: ProtoRune.App.Bsky.Graph.Defs.StarterPackViewBasic.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          pinnedPost: ProtoRune.Com.Atproto.Repo.StrongRef.Main.t(),
          postsCount: integer(),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
