# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPrefV2 do
  @moduledoc """
  **savedFeedsPrefV2** (object/record)

  No description.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(ProtoRune.App.Bsky.Actor.Defs.SavedFeed.t())
        }
end
