# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeed do
  @moduledoc """
  **savedFeed** (object/record)

  No description.
  """

  @enforce_keys [:id, :type, :value, :pinned]
  defstruct id: nil, pinned: nil, type: nil, value: nil

  @type t :: %__MODULE__{
          id: String.t(),
          pinned: boolean(),
          type: :feed | :list | :timeline,
          value: String.t()
        }
end
