# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPref do
  @moduledoc """
  **savedFeedsPref** (object/record)

  No description.
  """

  @enforce_keys [:pinned, :saved]
  defstruct pinned: nil, saved: nil, timelineIndex: nil

  @type t :: %__MODULE__{
          pinned: list(String.t()),
          saved: list(String.t()),
          timelineIndex: integer()
        }
end
