# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ThreadViewPref do
  @moduledoc """
  **threadViewPref** (object/record)

  No description.
  """

  defstruct prioritizeFollowedUsers: nil, sort: nil

  @type t :: %__MODULE__{
          prioritizeFollowedUsers: boolean(),
          sort: :oldest | :newest | :"most-likes" | :random | :hotness
        }
end
