# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ViewerState do
  @moduledoc """
  **viewerState** (object/record)

  Metadata about the requesting account's relationship with the subject account. Only has meaningful content for authed requests.
  """

  alias ProtoRune.App.Bsky.Graph.Defs.ListViewBasic

  defstruct blockedBy: nil,
            blocking: nil,
            blockingByList: nil,
            followedBy: nil,
            following: nil,
            knownFollowers: nil,
            muted: nil,
            mutedByList: nil

  @type t :: %__MODULE__{
          blockedBy: boolean(),
          blocking: String.t(),
          blockingByList: ListViewBasic.t(),
          followedBy: String.t(),
          following: String.t(),
          knownFollowers: ProtoRune.App.Bsky.Actor.Defs.KnownFollowers.t(),
          muted: boolean(),
          mutedByList: ListViewBasic.t()
        }
end
