# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetTrendingTopics.Main do
  @moduledoc """
  **main** (query)

  Get a list of trending topics
  """

  @type input :: any()
  @type output :: any()
end
