# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.CreateRecord.Main do
  @moduledoc """
  **main** (procedure)

  Create a single new repository record. Requires auth, implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
