# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.SearchActors.Main do
  @moduledoc """
  **main** (query)

  Find actors (profiles) matching search criteria. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
