# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetProfile.Main do
  @moduledoc """
  **main** (query)

  Get detailed profile view of an actor. Does not require auth, but contains relevant metadata with auth.
  """

  @type input :: any()
  @type output :: any()
end
