# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.CreateTemplate.Main do
  @moduledoc """
  **main** (procedure)

  Administrative action to create a new, re-usable communication (email for now) template.
  """

  @type input :: any()
  @type output :: any()
end
