# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.UpdateTemplate.MainErrorDuplicateTemplateName do
  @moduledoc """
  Generated schema for mainErrorDuplicateTemplateName

  **Description**: No description provided.
  """

  @type t :: any()
end
