# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate.FollowingRule do
  @moduledoc """
  Generated schema for followingRule

  **Description**: Allow replies from actors you follow.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
