# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate.MentionRule do
  @moduledoc """
  Generated schema for mentionRule

  **Description**: Allow replies from actors mentioned in your post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
