# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetRepoStatus.Main do
  @moduledoc """
  **main** (query)

  Get the hosting status for a repository, on this server. Expected to be implemented by PDS and Relay.
  """

  @type input :: any()
  @type output :: any()
end
