# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.Curatelist do
  @moduledoc """
  Token type for curatelist

  **Description**: A list of actors used for curation purposes such as list feeds or interaction gating.
  """

  @type t :: atom()
end
