# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListItemView do
  @moduledoc """
  Generated schema for listItemView

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :subject]
  defstruct subject: nil, uri: nil

  @type t :: %__MODULE__{
          subject: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          uri: String.t()
        }
end
