# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.ListPurpose do
  @moduledoc """
  Generated schema for listPurpose

  **Description**: No description provided.
  """

  @type t ::
          :"app.bsky.graph.defs#modlist"
          | :"app.bsky.graph.defs#curatelist"
          | :"app.bsky.graph.defs#referencelist"
end
