# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.Modlist do
  @moduledoc """
  Token type for modlist

  **Description**: A list of actors to apply an aggregate moderation action (mute/block) on.
  """

  @type t :: atom()
end
