# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.NotFoundActor do
  @moduledoc """
  Generated schema for notFoundActor

  **Description**: indicates that a handle or DID could not be resolved
  """

  @enforce_keys [:actor, :not_found]
  defstruct actor: nil, not_found: nil

  @type t :: %__MODULE__{
          actor: String.t(),
          not_found: boolean()
        }
end
