# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.Referencelist do
  @moduledoc """
  Token type for referencelist

  **Description**: A list of actors used for only for reference purposes such as within a starter pack.
  """

  @type t :: atom()
end
