# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.Relationship do
  @moduledoc """
  Generated schema for relationship

  **Description**: lists the bi-directional graph relationships between one actor (not indicated in the object), and the target actors (the DID included in the object)
  """

  @enforce_keys [:did]
  defstruct did: nil, followed_by: nil, following: nil

  @type t :: %__MODULE__{
          did: String.t(),
          followed_by: String.t(),
          following: String.t()
        }
end
