# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.StarterPackView do
  @moduledoc """
  Generated schema for starterPackView

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :cid, :record, :creator, :indexed_at]
  defstruct cid: nil,
            creator: nil,
            feeds: nil,
            indexed_at: nil,
            joined_all_time_count: nil,
            joined_week_count: nil,
            labels: nil,
            list: nil,
            list_items_sample: nil,
            record: nil,
            uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          feeds: list(ProtoRune.App.Bsky.Feed.Defs.GeneratorView.t()),
          indexed_at: String.t(),
          joined_all_time_count: integer(),
          joined_week_count: integer(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          list: ProtoRune.App.Bsky.Graph.Defs.ListViewBasic.t(),
          list_items_sample: list(ProtoRune.App.Bsky.Graph.Defs.ListItemView.t()),
          record: any(),
          uri: String.t()
        }
end
