# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Defs.StarterPackViewBasic do
  @moduledoc """
  Generated schema for starterPackViewBasic

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :cid, :record, :creator, :indexed_at]
  defstruct cid: nil,
            creator: nil,
            indexed_at: nil,
            joined_all_time_count: nil,
            joined_week_count: nil,
            labels: nil,
            list_item_count: nil,
            record: nil,
            uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          indexed_at: String.t(),
          joined_all_time_count: integer(),
          joined_week_count: integer(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          list_item_count: integer(),
          record: any(),
          uri: String.t()
        }
end
