# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Setting.Defs.Option do
  @moduledoc """
  **option** (object/record)

  No description.
  """

  @enforce_keys [:key, :value, :did, :scope, :createdBy, :lastUpdatedBy]
  defstruct createdAt: nil,
            createdBy: nil,
            description: nil,
            did: nil,
            key: nil,
            lastUpdatedBy: nil,
            managerRole: nil,
            scope: nil,
            updatedAt: nil,
            value: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          createdBy: String.t(),
          description: String.t(),
          did: String.t(),
          key: String.t(),
          lastUpdatedBy: String.t(),
          managerRole:
            :"tools.ozone.team.defs#roleModerator"
            | :"tools.ozone.team.defs#roleTriage"
            | :"tools.ozone.team.defs#roleAdmin",
          scope: :instance | :personal,
          updatedAt: String.t(),
          value: any()
        }
end
