# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.SearchPosts.Main do
  @moduledoc """
  **main** (query)

  Find posts matching search criteria, returning views of those posts.
  """

  @type input :: any()
  @type output :: any()
end
