# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.DescribeFeedGenerator.Feed do
  @moduledoc """
  **feed** (object/record)

  No description.
  """

  @enforce_keys [:uri]
  defstruct uri: nil

  @type t :: %__MODULE__{
          uri: String.t()
        }
end
