# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.DescribeFeedGenerator.Main do
  @moduledoc """
  **main** (query)

  Get information about a feed generator, including policies and offered feed URIs. Does not require auth; implemented by Feed Generator services (not App View).
  """

  @type input :: any()
  @type output :: any()
end
