# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Defs.LabelerPolicies do
  @moduledoc """
  **labelerPolicies** (object/record)

  No description.
  """

  @enforce_keys [:labelValues]
  defstruct labelValueDefinitions: nil, labelValues: nil

  @type t :: %__MODULE__{
          labelValueDefinitions: list(ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinition.t()),
          labelValues: list(ProtoRune.Types.com_atproto_label_defs_label_value())
        }
end
