# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Defs.LabelerView do
  @moduledoc """
  **labelerView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :creator, :indexedAt]
  defstruct cid: nil,
            creator: nil,
            indexedAt: nil,
            labels: nil,
            likeCount: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          likeCount: integer(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Labeler.Defs.LabelerViewerState.t()
        }
end
