# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Defs.LabelerViewerState do
  @moduledoc """
  **labelerViewerState** (object/record)

  No description.
  """

  defstruct like: nil

  @type t :: %__MODULE__{
          like: String.t()
        }
end
