# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.DeleteTemplate.Main do
  @moduledoc """
  **main** (procedure)

  Delete a communication template.
  """

  @type input :: any()
  @type output :: any()
end
