# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Listblock.Main do
  @moduledoc """
  **main** (object/record)

  Record representing a block relationship against an entire an entire list of accounts (actors).
  """

  defstruct []

  @type t :: %__MODULE__{}
end
