# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.MuteActor.Main do
  @moduledoc """
  **main** (procedure)

  Creates a mute relationship for the specified account. Mutes are private in Bluesky. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
