# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Moderation.GetActorMetadata.Metadata do
  @moduledoc """
  **metadata** (object/record)

  No description.
  """

  @enforce_keys [:messagesSent, :messagesReceived, :convos, :convosStarted]
  defstruct convos: nil, convosStarted: nil, messagesReceived: nil, messagesSent: nil

  @type t :: %__MODULE__{
          convos: integer(),
          convosStarted: integer(),
          messagesReceived: integer(),
          messagesSent: integer()
        }
end
