# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.SendInteractions.Main do
  @moduledoc """
  **main** (procedure)

  Send information about interactions with feed items back to the feed generator that served them.
  """

  @type input :: any()
  @type output :: any()
end
