# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.Label do
  @moduledoc """
  **label** (object/record)

  Metadata tag on an atproto resource (eg, repo or record).
  """

  @enforce_keys [:src, :uri, :val, :cts]
  defstruct cid: nil,
            cts: nil,
            exp: nil,
            neg: nil,
            sig: nil,
            src: nil,
            uri: nil,
            val: nil,
            ver: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          cts: String.t(),
          exp: String.t(),
          neg: boolean(),
          sig: binary(),
          src: String.t(),
          uri: String.t(),
          val: String.t(),
          ver: integer()
        }
end
