# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinition do
  @moduledoc """
  **labelValueDefinition** (object/record)

  Declares a label value and its expected interpretations and behaviors.
  """

  @enforce_keys [:identifier, :severity, :blurs, :locales]
  defstruct adultOnly: nil,
            blurs: nil,
            defaultSetting: nil,
            identifier: nil,
            locales: nil,
            severity: nil

  @type t :: %__MODULE__{
          adultOnly: boolean(),
          blurs: :content | :media | :none,
          defaultSetting: :ignore | :warn | :hide,
          identifier: String.t(),
          locales: list(ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinitionStrings.t()),
          severity: :inform | :alert | :none
        }
end
