# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.SelfLabel do
  @moduledoc """
  **selfLabel** (object/record)

  Metadata tag on an atproto record, published by the author within the record. Note that schemas should use #selfLabels, not #selfLabel.
  """

  @enforce_keys [:val]
  defstruct val: nil

  @type t :: %__MODULE__{
          val: String.t()
        }
end
