# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Richtext.Facet do
  @moduledoc """
  Generated schema for main

  **Description**: Annotation of a sub-string within rich text.
  """

  @enforce_keys [:index, :features]
  defstruct features: nil, index: nil

  @type t :: %__MODULE__{
          features:
            list(
              ProtoRune.App.Bsky.Richtext.Facet.Mention.t()
              | ProtoRune.App.Bsky.Richtext.Facet.Link.t()
              | ProtoRune.App.Bsky.Richtext.Facet.Tag.t()
            ),
          index: ProtoRune.App.Bsky.Richtext.Facet.ByteSlice.t()
        }
end
