# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.AdultContentPref do
  @moduledoc """
  Generated schema for adultContentPref

  **Description**: No description provided.
  """

  @enforce_keys [:enabled]
  defstruct enabled: nil

  @type t :: %__MODULE__{
          enabled: boolean()
        }
end
