# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.BskyAppStatePref do
  @moduledoc """
  Generated schema for bskyAppStatePref

  **Description**: A grab bag of state that's specific to the bsky.app program. Third-party apps shouldn't use this.
  """

  defstruct active_progress_guide: nil, nuxs: nil, queued_nudges: nil

  @type t :: %__MODULE__{
          active_progress_guide: ProtoRune.App.Bsky.Actor.Defs.BskyAppProgressGuide.t(),
          nuxs: list(ProtoRune.App.Bsky.Actor.Defs.Nux.t()),
          queued_nudges: list(String.t())
        }
end
