# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ContentLabelPref do
  @moduledoc """
  Generated schema for contentLabelPref

  **Description**: No description provided.
  """

  @enforce_keys [:label, :visibility]
  defstruct label: nil, labeler_did: nil, visibility: nil

  @type t :: %__MODULE__{
          label: String.t(),
          labeler_did: String.t(),
          visibility: :ignore | :show | :warn | :hide
        }
end
