# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.FeedViewPref do
  @moduledoc """
  Generated schema for feedViewPref

  **Description**: No description provided.
  """

  @enforce_keys [:feed]
  defstruct feed: nil,
            hide_quote_posts: nil,
            hide_replies: nil,
            hide_replies_by_like_count: nil,
            hide_replies_by_unfollowed: nil,
            hide_reposts: nil

  @type t :: %__MODULE__{
          feed: String.t(),
          hide_quote_posts: boolean(),
          hide_replies: boolean(),
          hide_replies_by_like_count: integer(),
          hide_replies_by_unfollowed: boolean(),
          hide_reposts: boolean()
        }
end
