# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.HiddenPostsPref do
  @moduledoc """
  Generated schema for hiddenPostsPref

  **Description**: No description provided.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(String.t())
        }
end
