# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.InterestsPref do
  @moduledoc """
  Generated schema for interestsPref

  **Description**: No description provided.
  """

  @enforce_keys [:tags]
  defstruct tags: nil

  @type t :: %__MODULE__{
          tags: list(String.t())
        }
end
