# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.KnownFollowers do
  @moduledoc """
  Generated schema for knownFollowers

  **Description**: The subject's followers whom you also follow
  """

  @enforce_keys [:count, :followers]
  defstruct count: nil, followers: nil

  @type t :: %__MODULE__{
          count: integer(),
          followers: list(ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t())
        }
end
