# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.LabelersPref do
  @moduledoc """
  Generated schema for labelersPref

  **Description**: No description provided.
  """

  @enforce_keys [:labelers]
  defstruct labelers: nil

  @type t :: %__MODULE__{
          labelers: list(ProtoRune.App.Bsky.Actor.Defs.LabelerPrefItem.t())
        }
end
