# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.MutedWordTarget do
  @moduledoc """
  Generated schema for mutedWordTarget

  **Description**: No description provided.
  """

  @type t :: :content | :tag
end
