# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.MutedWord do
  @moduledoc """
  Generated schema for mutedWord

  **Description**: A word that the account owner has muted.
  """

  @enforce_keys [:value, :targets]
  defstruct actor_target: nil, expires_at: nil, id: nil, targets: nil, value: nil

  @type t :: %__MODULE__{
          actor_target: :all | :"exclude-following",
          expires_at: String.t(),
          id: String.t(),
          targets: list(ProtoRune.App.Bsky.Actor.Defs.MutedWordTarget.t()),
          value: String.t()
        }
end
