# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.MutedWordsPref do
  @moduledoc """
  Generated schema for mutedWordsPref

  **Description**: No description provided.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(ProtoRune.App.Bsky.Actor.Defs.MutedWord.t())
        }
end
