# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.Nux do
  @moduledoc """
  Generated schema for nux

  **Description**: A new user experiences (NUX) storage object
  """

  @enforce_keys [:id, :completed]
  defstruct completed: nil, data: nil, expires_at: nil, id: nil

  @type t :: %__MODULE__{
          completed: boolean(),
          data: String.t(),
          expires_at: String.t(),
          id: String.t()
        }
end
