# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.PersonalDetailsPref do
  @moduledoc """
  Generated schema for personalDetailsPref

  **Description**: No description provided.
  """

  defstruct birth_date: nil

  @type t :: %__MODULE__{
          birth_date: String.t()
        }
end
