# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.Preferences do
  @moduledoc """
  Generated schema for preferences

  **Description**: No description provided.
  """

  @type t ::
          ProtoRune.App.Bsky.Actor.Defs.AdultContentPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.ContentLabelPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPrefV2.t()
          | ProtoRune.App.Bsky.Actor.Defs.PersonalDetailsPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.FeedViewPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.ThreadViewPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.InterestsPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.MutedWordsPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.HiddenPostsPref.t()
          | ProtoRune.App.Bsky.Actor.Defs.BskyAppStatePref.t()
          | ProtoRune.App.Bsky.Actor.Defs.LabelersPref.t()
end
