# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileView do
  @moduledoc """
  Generated schema for profileView

  **Description**: No description provided.
  """

  @enforce_keys [:did, :handle]
  defstruct associated: nil,
            avatar: nil,
            created_at: nil,
            description: nil,
            did: nil,
            display_name: nil,
            handle: nil,
            indexed_at: nil,
            labels: nil,
            viewer: nil

  @type t :: %__MODULE__{
          associated: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated.t(),
          avatar: String.t(),
          created_at: String.t(),
          description: String.t(),
          did: String.t(),
          display_name: String.t(),
          handle: String.t(),
          indexed_at: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
