# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileAssociatedChat do
  @moduledoc """
  Generated schema for profileAssociatedChat

  **Description**: No description provided.
  """

  @enforce_keys [:allow_incoming]
  defstruct allow_incoming: nil

  @type t :: %__MODULE__{
          allow_incoming: :all | :none | :following
        }
end
