# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileViewDetailed do
  @moduledoc """
  Generated schema for profileViewDetailed

  **Description**: No description provided.
  """

  @enforce_keys [:did, :handle]
  defstruct associated: nil,
            avatar: nil,
            banner: nil,
            created_at: nil,
            description: nil,
            did: nil,
            display_name: nil,
            followers_count: nil,
            follows_count: nil,
            handle: nil,
            indexed_at: nil,
            joined_via_starter_pack: nil,
            labels: nil,
            posts_count: nil,
            viewer: nil

  @type t :: %__MODULE__{
          associated: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated.t(),
          avatar: String.t(),
          banner: String.t(),
          created_at: String.t(),
          description: String.t(),
          did: String.t(),
          display_name: String.t(),
          followers_count: integer(),
          follows_count: integer(),
          handle: String.t(),
          indexed_at: String.t(),
          joined_via_starter_pack: ProtoRune.App.Bsky.Graph.Defs.StarterPackViewBasic.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          posts_count: integer(),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
