# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ProfileAssociated do
  @moduledoc """
  Generated schema for profileAssociated

  **Description**: No description provided.
  """

  defstruct chat: nil, feedgens: nil, labeler: nil, lists: nil, starter_packs: nil

  @type t :: %__MODULE__{
          chat: ProtoRune.App.Bsky.Actor.Defs.ProfileAssociatedChat.t(),
          feedgens: integer(),
          labeler: boolean(),
          lists: integer(),
          starter_packs: integer()
        }
end
