# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPrefV2 do
  @moduledoc """
  Generated schema for savedFeedsPrefV2

  **Description**: No description provided.
  """

  @enforce_keys [:items]
  defstruct items: nil

  @type t :: %__MODULE__{
          items: list(ProtoRune.App.Bsky.Actor.Defs.SavedFeed.t())
        }
end
