# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeedsPref do
  @moduledoc """
  Generated schema for savedFeedsPref

  **Description**: No description provided.
  """

  @enforce_keys [:pinned, :saved]
  defstruct pinned: nil, saved: nil, timeline_index: nil

  @type t :: %__MODULE__{
          pinned: list(String.t()),
          saved: list(String.t()),
          timeline_index: integer()
        }
end
