# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.SavedFeed do
  @moduledoc """
  Generated schema for savedFeed

  **Description**: No description provided.
  """

  @type t :: String.t()
end
