# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Defs.ThreadViewPref do
  @moduledoc """
  Generated schema for threadViewPref

  **Description**: No description provided.
  """

  defstruct prioritize_followed_users: nil, sort: nil

  @type t :: %__MODULE__{
          prioritize_followed_users: boolean(),
          sort: :oldest | :newest | :"most-likes" | :random
        }
end
