# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetPostThread.Main do
  @moduledoc """
  **main** (query)

  Get posts in a thread. Does not require auth, but additional metadata and filtering will be applied for authed requests.
  """

  @type input :: any()
  @type output :: any()
end
