# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestEmailConfirmation.Main do
  @moduledoc """
  **main** (procedure)

  Request an email with a code to confirm ownership of email.
  """

  @type input :: any()
  @type output :: any()
end
