# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Starterpack.FeedItem do
  @moduledoc """
  **feedItem** (object/record)

  No description.
  """

  @enforce_keys [:uri]
  defstruct uri: nil

  @type t :: %__MODULE__{
          uri: String.t()
        }
end
