# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Starterpack.Main do
  @moduledoc """
  **main** (object/record)

  Record defining a starter pack of actors and feeds for new users.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
