# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Actor.Declaration.Main do
  @moduledoc """
  **main** (object/record)

  A declaration of a Bluesky chat account.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
