# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.UploadVideo.Main do
  @moduledoc """
  **main** (procedure)

  Upload a video to be processed then stored on the PDS.
  """

  @type input :: any()
  @type output :: any()
end
