# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.ConvoView do
  @moduledoc """
  **convoView** (object/record)

  No description.
  """

  @enforce_keys [:id, :rev, :members, :muted, :unreadCount]
  defstruct id: nil,
            lastMessage: nil,
            members: nil,
            muted: nil,
            opened: nil,
            rev: nil,
            unreadCount: nil

  @type t :: %__MODULE__{
          id: String.t(),
          lastMessage:
            ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView.t(),
          members: list(ProtoRune.Chat.Bsky.Actor.Defs.ProfileViewBasic.t()),
          muted: boolean(),
          opened: boolean(),
          rev: String.t(),
          unreadCount: integer()
        }
end
