# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView do
  @moduledoc """
  **deletedMessageView** (object/record)

  No description.
  """

  @enforce_keys [:id, :rev, :sender, :sentAt]
  defstruct id: nil, rev: nil, sender: nil, sentAt: nil

  @type t :: %__MODULE__{
          id: String.t(),
          rev: String.t(),
          sender: ProtoRune.Chat.Bsky.Convo.Defs.MessageViewSender.t(),
          sentAt: String.t()
        }
end
