# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.LogBeginConvo do
  @moduledoc """
  **logBeginConvo** (object/record)

  No description.
  """

  @enforce_keys [:rev, :convoId]
  defstruct convoId: nil, rev: nil

  @type t :: %__MODULE__{
          convoId: String.t(),
          rev: String.t()
        }
end
