# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.LogDeleteMessage do
  @moduledoc """
  **logDeleteMessage** (object/record)

  No description.
  """

  @enforce_keys [:rev, :convoId, :message]
  defstruct convoId: nil, message: nil, rev: nil

  @type t :: %__MODULE__{
          convoId: String.t(),
          message:
            ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView.t(),
          rev: String.t()
        }
end
