# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageInput do
  @moduledoc """
  **messageInput** (object/record)

  No description.
  """

  @enforce_keys [:text]
  defstruct embed: nil, facets: nil, text: nil

  @type t :: %__MODULE__{
          embed: ProtoRune.App.Bsky.Embed.Record.Main.t(),
          facets: list(ProtoRune.App.Bsky.Richtext.Facet.Main.t()),
          text: String.t()
        }
end
