# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageView do
  @moduledoc """
  **messageView** (object/record)

  No description.
  """

  @enforce_keys [:id, :rev, :text, :sender, :sentAt]
  defstruct embed: nil, facets: nil, id: nil, rev: nil, sender: nil, sentAt: nil, text: nil

  @type t :: %__MODULE__{
          embed: ProtoRune.App.Bsky.Embed.Record.View.t(),
          facets: list(ProtoRune.App.Bsky.Richtext.Facet.Main.t()),
          id: String.t(),
          rev: String.t(),
          sender: ProtoRune.Chat.Bsky.Convo.Defs.MessageViewSender.t(),
          sentAt: String.t(),
          text: String.t()
        }
end
