# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageRef do
  @moduledoc """
  **messageRef** (object/record)

  No description.
  """

  @enforce_keys [:did, :messageId, :convoId]
  defstruct convoId: nil, did: nil, messageId: nil

  @type t :: %__MODULE__{
          convoId: String.t(),
          did: String.t(),
          messageId: String.t()
        }
end
