# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ActivateAccount.Main do
  @moduledoc """
  **main** (procedure)

  Activates a currently deactivated account. Used to finalize account migration after the account's repo is imported and identity is setup.
  """

  @type input :: any()
  @type output :: any()
end
