# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateSession.MainErrorAuthFactorTokenRequired do
  @moduledoc """
  Generated schema for mainErrorAuthFactorTokenRequired

  **Description**: No description provided.
  """

  @type t :: any()
end
