# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetFeedGenerator.Main do
  @moduledoc """
  **main** (query)

  Get information about a feed generator. Implemented by AppView.
  """

  @type input :: any()
  @type output :: any()
end
