# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetKnownFollowers.Main do
  @moduledoc """
  **main** (query)

  Enumerates accounts which follow a specified account (actor) and are followed by the viewer.
  """

  @type input :: any()
  @type output :: any()
end
