# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetAuthorFeed.Main do
  @moduledoc """
  **main** (query)

  Get a view of an actor's 'author feed' (post and reposts by the author). Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
