# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.Defs.InviteCodeUse do
  @moduledoc """
  **inviteCodeUse** (object/record)

  No description.
  """

  @enforce_keys [:usedBy, :usedAt]
  defstruct usedAt: nil, usedBy: nil

  @type t :: %__MODULE__{
          usedAt: String.t(),
          usedBy: String.t()
        }
end
