# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.Defs.InviteCode do
  @moduledoc """
  **inviteCode** (object/record)

  No description.
  """

  @enforce_keys [:code, :available, :disabled, :forAccount, :createdBy, :createdAt, :uses]
  defstruct available: nil,
            code: nil,
            createdAt: nil,
            createdBy: nil,
            disabled: nil,
            forAccount: nil,
            uses: nil

  @type t :: %__MODULE__{
          available: integer(),
          code: String.t(),
          createdAt: String.t(),
          createdBy: String.t(),
          disabled: boolean(),
          forAccount: String.t(),
          uses: list(ProtoRune.Com.Atproto.Server.Defs.InviteCodeUse.t())
        }
end
