# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Moderation.GetActorMetadata do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{actor: String.t()}
end
