# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Moderation.GetMessageContext do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{after: integer(), before: integer(), convo_id: String.t(), message_id: String.t()}
end
