# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Moderation.UpdateActorAccess do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type input :: %{actor: String.t(), allow_access: boolean(), ref: String.t()}
end
