# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ListAppPasswords.AppPassword do
  @moduledoc """
  Generated schema for appPassword

  **Description**: No description provided.
  """

  @enforce_keys [:name, :created_at]
  defstruct created_at: nil, name: nil, privileged: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          name: String.t(),
          privileged: boolean()
        }
end
