# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ListAppPasswords.MainErrorAccountTakedown do
  @moduledoc """
  Generated schema for mainErrorAccountTakedown

  **Description**: No description provided.
  """

  @type t :: any()
end
