# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.UpdateTemplate.Main do
  @moduledoc """
  **main** (procedure)

  Administrative action to update an existing communication template. Allows passing partial fields to patch specific fields only.
  """

  @type input :: any()
  @type output :: any()
end
