# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.UpdateEmail.MainErrorTokenRequired do
  @moduledoc """
  Generated schema for mainErrorTokenRequired

  **Description**: No description provided.
  """

  @type t :: any()
end
