# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetSuggestedFollowsByActor.Main do
  @moduledoc """
  **main** (query)

  Enumerates follows similar to a given account (actor). Expected use is to recommend additional accounts immediately after following one account.
  """

  @type input :: any()
  @type output :: any()
end
