# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.UpdateSeen.Main do
  @moduledoc """
  **main** (procedure)

  Notify server that the requesting account has seen notifications. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
