# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ListMissingBlobs.Main do
  @moduledoc """
  **main** (query)

  Returns a list of missing blobs for the requesting account. Intended to be used in the account migration flow.
  """

  @type input :: any()
  @type output :: any()
end
