# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ListMissingBlobs.RecordBlob do
  @moduledoc """
  **recordBlob** (object/record)

  No description.
  """

  @enforce_keys [:cid, :recordUri]
  defstruct cid: nil, recordUri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          recordUri: String.t()
        }
end
