# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.SearchRepos.Main do
  @moduledoc """
  **main** (query)

  Find repositories based on a search term.
  """

  @type input :: any()
  @type output :: any()
end
