# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.SearchStarterPacks.Main do
  @moduledoc """
  **main** (query)

  Find starter packs matching search criteria. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
