# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetPreferences.Main do
  @moduledoc """
  **main** (query)

  Get private preferences attached to the current account. Expected use is synchronization between multiple devices, and import/export during account migration. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
