# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.GetConvo.Main do
  @moduledoc """
  **main** (query)

  No description.
  """

  @type input :: any()
  @type output :: any()
end
