# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.PutRecord.MainErrorInvalidSwap do
  @moduledoc """
  Generated schema for mainErrorInvalidSwap

  **Description**: No description provided.
  """

  @type t :: any()
end
