# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DescribeServer.Contact do
  @moduledoc """
  **contact** (object/record)

  No description.
  """

  defstruct email: nil

  @type t :: %__MODULE__{
          email: String.t()
        }
end
