# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DescribeServer.Links do
  @moduledoc """
  **links** (object/record)

  No description.
  """

  defstruct privacyPolicy: nil, termsOfService: nil

  @type t :: %__MODULE__{
          privacyPolicy: String.t(),
          termsOfService: String.t()
        }
end
