# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DescribeServer.Main do
  @moduledoc """
  **main** (query)

  Describes the server's account creation requirements and capabilities. Implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
