# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetSubjectStatus.Main do
  @moduledoc """
  **main** (query)

  Get the service-specific admin status of a subject (account, record, or blob).
  """

  @type input :: any()
  @type output :: any()
end
