# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetTaggedSuggestions.Main do
  @moduledoc """
  **main** (query)

  Get a list of suggestions (feeds and users) tagged with categories
  """

  @type input :: any()
  @type output :: any()
end
