# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetTaggedSuggestions.Suggestion do
  @moduledoc """
  **suggestion** (object/record)

  No description.
  """

  @enforce_keys [:tag, :subjectType, :subject]
  defstruct subject: nil, subjectType: nil, tag: nil

  @type t :: %__MODULE__{
          subject: String.t(),
          subjectType: :actor | :feed,
          tag: String.t()
        }
end
