# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateAccountPassword.Main do
  @moduledoc """
  **main** (procedure)

  Update the password for a user account as an administrator.
  """

  @type input :: any()
  @type output :: any()
end
