# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetAccountInfos.Main do
  @moduledoc """
  **main** (query)

  Get details about some accounts.
  """

  @type input :: any()
  @type output :: any()
end
