# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.UpdateEmail.Main do
  @moduledoc """
  **main** (procedure)

  Update an account's email.
  """

  @type input :: any()
  @type output :: any()
end
