# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.RecordWithMedia.View do
  @moduledoc """
  Generated schema for view

  **Description**: No description provided.
  """

  @enforce_keys [:record, :media]
  defstruct media: nil, record: nil

  @type t :: %__MODULE__{
          media:
            ProtoRune.App.Bsky.Embed.Images.View.t()
            | ProtoRune.App.Bsky.Embed.Video.View.t()
            | ProtoRune.App.Bsky.Embed.External.View.t(),
          record: ProtoRune.App.Bsky.Embed.Record.View.t()
        }
end
