# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetLatestCommit.Main do
  @moduledoc """
  **main** (query)

  Get the current commit CID & revision of the specified repo. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
