# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetBlob.Main do
  @moduledoc """
  **main** (query)

  Get a blob associated with a given account. Returns the full blob as originally uploaded. Does not require auth; implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
