# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetRelationships.Main do
  @moduledoc """
  **main** (query)

  Enumerates public relationships between one account, and a list of other accounts. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
