# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.Defs.SkeletonSearchActor do
  @moduledoc """
  **skeletonSearchActor** (object/record)

  No description.
  """

  @enforce_keys [:did]
  defstruct did: nil

  @type t :: %__MODULE__{
          did: String.t()
        }
end
