# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.Defs.SkeletonSearchPost do
  @moduledoc """
  **skeletonSearchPost** (object/record)

  No description.
  """

  @enforce_keys [:uri]
  defstruct uri: nil

  @type t :: %__MODULE__{
          uri: String.t()
        }
end
