# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.Defs.TrendingTopic do
  @moduledoc """
  **trendingTopic** (object/record)

  No description.
  """

  @enforce_keys [:topic, :link]
  defstruct description: nil, displayName: nil, link: nil, topic: nil

  @type t :: %__MODULE__{
          description: String.t(),
          displayName: String.t(),
          link: String.t(),
          topic: String.t()
        }
end
