# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.AddValues.Main do
  @moduledoc """
  **main** (procedure)

  Add values to a specific set. Attempting to add values to a set that does not exist will result in an error.
  """

  @type input :: any()
  @type output :: any()
end
