# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.SendMessageBatch.BatchItem do
  @moduledoc """
  Generated schema for batchItem

  **Description**: No description provided.
  """

  @enforce_keys [:convo_id, :message]
  defstruct convo_id: nil, message: nil

  @type t :: %__MODULE__{
          convo_id: String.t(),
          message: ProtoRune.Chat.Bsky.Convo.Defs.MessageInput.t()
        }
end
