# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.Defs.Member do
  @moduledoc """
  Generated schema for member

  **Description**: No description provided.
  """

  @enforce_keys [:did, :role]
  defstruct created_at: nil,
            did: nil,
            disabled: nil,
            last_updated_by: nil,
            profile: nil,
            role: nil,
            updated_at: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          did: String.t(),
          disabled: boolean(),
          last_updated_by: String.t(),
          profile: ProtoRune.App.Bsky.Actor.Defs.ProfileViewDetailed.t(),
          role: :"#roleAdmin" | :"#roleModerator" | :"#roleTriage",
          updated_at: String.t()
        }
end
