# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.Defs.RoleAdmin do
  @moduledoc """
  Token type for roleAdmin

  **Description**: Admin role. Highest level of access, can perform all actions.
  """

  @type t :: atom()
end
