# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.Defs.RoleModerator do
  @moduledoc """
  Token type for roleModerator

  **Description**: Moderator role. Can perform most actions.
  """

  @type t :: atom()
end
