# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.Defs.RoleTriage do
  @moduledoc """
  Token type for roleTriage

  **Description**: Triage role. Mostly intended for monitoring and escalating issues.
  """

  @type t :: atom()
end
