# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetFollowers.Main do
  @moduledoc """
  **main** (query)

  Enumerates accounts which follow a specified account (actor).
  """

  @type input :: any()
  @type output :: any()
end
