# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.DescribeRepo.Main do
  @moduledoc """
  **main** (query)

  Get information about an account and repository, including the list of collections. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
