# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetActorFeeds.Main do
  @moduledoc """
  **main** (query)

  Get a list of feeds (feed generator records) created by the actor (in the actor's repo).
  """

  @type input :: any()
  @type output :: any()
end
