# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Lexicon.Schema.Main do
  @moduledoc """
  **main** (object/record)

  Representation of Lexicon schemas themselves, when published as atproto records. Note that the schema language is not defined in Lexicon; this meta schema currently only includes a single version field ('lexicon'). See the atproto specifications for description of the other expected top-level fields ('id', 'defs', etc).
  """

  defstruct []

  @type t :: %__MODULE__{}
end
