# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Repost.Main do
  @moduledoc """
  **main** (object/record)

  Record representing a 'repost' of an existing Bluesky post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
