# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.PutRecord.Main do
  @moduledoc """
  **main** (procedure)

  Write a repository record, creating or updating it as needed. Requires auth, implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
