# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.UnmuteActorList.Main do
  @moduledoc """
  **main** (procedure)

  Unmutes the specified list of accounts. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
