# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetSuggestionsSkeleton do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          cursor: String.t(),
          limit: integer(),
          relative_to_did: String.t(),
          viewer: String.t()
        }
end
