# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.SearchActorsSkeleton do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          cursor: String.t(),
          limit: integer(),
          q: String.t(),
          typeahead: boolean(),
          viewer: String.t()
        }
end
