# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ListRecords.Main do
  @moduledoc """
  **main** (query)

  List a range of records in a repository, matching a specific collection. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
