# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ListRecords.Record do
  @moduledoc """
  **record** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :value]
  defstruct cid: nil, uri: nil, value: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          uri: String.t(),
          value: any()
        }
end
