# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.MuteThread.Main do
  @moduledoc """
  **main** (procedure)

  Mutes a thread preventing notifications from the thread and any of its children. Mutes are private in Bluesky. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
