# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.GetJobStatus do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{job_id: String.t()}
end
