# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.GetUploadLimits do
  @moduledoc """
  Generated query module for main

  **Description**: Get video upload limits for the authenticated user.
  """

  @type output :: %{
          can_upload: boolean(),
          error: String.t(),
          message: String.t(),
          remaining_daily_bytes: integer(),
          remaining_daily_videos: integer()
        }
end
