# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.UploadVideo do
  @moduledoc """
  Generated procedure module for main

  **Description**: Upload a video to be processed then stored on the PDS.
  """

  @type output :: %{job_status: ProtoRune.App.Bsky.Video.Defs.JobStatus.t()}
  @type input :: any()
end
