# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ConfirmEmail.Main do
  @moduledoc """
  **main** (procedure)

  Confirm an email using a token from com.atproto.server.requestEmailConfirmation.
  """

  @type input :: any()
  @type output :: any()
end
