# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetRecord.Main do
  @moduledoc """
  **main** (query)

  Get data blocks needed to prove the existence or non-existence of record in the current version of repo. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
