# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.Defs.SkeletonSearchPost do
  @moduledoc """
  Generated schema for skeletonSearchPost

  **Description**: No description provided.
  """

  @enforce_keys [:uri]
  defstruct uri: nil

  @type t :: %__MODULE__{
          uri: String.t()
        }
end
