# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.Defs.SkeletonSearchActor do
  @moduledoc """
  Generated schema for skeletonSearchActor

  **Description**: No description provided.
  """

  @enforce_keys [:did]
  defstruct did: nil

  @type t :: %__MODULE__{
          did: String.t()
        }
end
