# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Actor.Declaration do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:allow_incoming]
  defstruct allow_incoming: nil

  @type t :: %__MODULE__{
          allow_incoming: :all | :none | :following
        }
end
