# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Actor.DeleteAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: No description provided.
  """

  @type output :: %{}
end
