# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Actor.ExportAccountData do
  @moduledoc """
  Generated query module for main

  **Description**: No description provided.
  """

  @type output :: any()
end
