# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetFeed.Main do
  @moduledoc """
  **main** (query)

  Get a hydrated feed from an actor's selected feed generator. Implemented by App View.
  """

  @type input :: any()
  @type output :: any()
end
