# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetFeedSkeleton.Main do
  @moduledoc """
  **main** (query)

  Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service.
  """

  @type input :: any()
  @type output :: any()
end
