# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRepos.Main do
  @moduledoc """
  **main** (query)

  Get details about some repositories.
  """

  @type input :: any()
  @type output :: any()
end
