# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.StrongRef.Main do
  @moduledoc """
  **main** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid]
  defstruct cid: nil, uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          uri: String.t()
        }
end
