# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Listitem.Main do
  @moduledoc """
  **main** (object/record)

  Record representing an account's inclusion on a specific list. The AppView will ignore duplicate listitem records.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
