# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetSession.Main do
  @moduledoc """
  **main** (query)

  Get information about the current auth session. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
