# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateInviteCodes.AccountCodes do
  @moduledoc """
  Generated schema for accountCodes

  **Description**: No description provided.
  """

  @enforce_keys [:account, :codes]
  defstruct account: nil, codes: nil

  @type t :: %__MODULE__{
          account: String.t(),
          codes: list(String.t())
        }
end
