# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Richtext.Facet.ByteSlice do
  @moduledoc """
  Generated schema for byteSlice

  **Description**: Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets.
  """

  @enforce_keys [:byte_start, :byte_end]
  defstruct byte_end: nil, byte_start: nil

  @type t :: %__MODULE__{
          byte_end: integer(),
          byte_start: integer()
        }
end
