# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Server.GetConfig.ServiceConfig do
  @moduledoc """
  Generated schema for serviceConfig

  **Description**: No description provided.
  """

  defstruct url: nil

  @type t :: %__MODULE__{
          url: String.t()
        }
end
