# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Server.GetConfig.ViewerConfig do
  @moduledoc """
  Generated schema for viewerConfig

  **Description**: No description provided.
  """

  defstruct role: nil

  @type t :: %__MODULE__{
          role:
            :"tools.ozone.team.defs#roleAdmin"
            | :"tools.ozone.team.defs#roleModerator"
            | :"tools.ozone.team.defs#roleTriage"
        }
end
