# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DescribeServer.Contact do
  @moduledoc """
  Generated schema for contact

  **Description**: No description provided.
  """

  defstruct email: nil

  @type t :: %__MODULE__{
          email: String.t()
        }
end
