# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetLikes.Main do
  @moduledoc """
  **main** (query)

  Get like records which reference a subject (by AT-URI and CID).
  """

  @type input :: any()
  @type output :: any()
end
