# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.PutPreferences.Main do
  @moduledoc """
  **main** (procedure)

  Set notification-related preferences for an account. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
