# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images.Main do
  @moduledoc """
  **main** (object/record)

  No description.
  """

  @enforce_keys [:images]
  defstruct images: nil

  @type t :: %__MODULE__{
          images: list(ProtoRune.App.Bsky.Embed.Images.Image.t())
        }
end
