# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images.ViewImage do
  @moduledoc """
  **viewImage** (object/record)

  No description.
  """

  @enforce_keys [:thumb, :fullsize, :alt]
  defstruct alt: nil, aspectRatio: nil, fullsize: nil, thumb: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspectRatio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          fullsize: String.t(),
          thumb: String.t()
        }
end
