# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images.View do
  @moduledoc """
  **view** (object/record)

  No description.
  """

  @enforce_keys [:images]
  defstruct images: nil

  @type t :: %__MODULE__{
          images: list(ProtoRune.App.Bsky.Embed.Images.ViewImage.t())
        }
end
