# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.ResolveHandle.Main do
  @moduledoc """
  **main** (query)

  Resolves a handle (domain name) to a DID.
  """

  @type input :: any()
  @type output :: any()
end
