# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.Defs.TemplateView do
  @moduledoc """
  Generated schema for templateView

  **Description**: No description provided.
  """

  @enforce_keys [
    :id,
    :name,
    :content_markdown,
    :disabled,
    :last_updated_by,
    :created_at,
    :updated_at
  ]
  defstruct content_markdown: nil,
            created_at: nil,
            disabled: nil,
            id: nil,
            lang: nil,
            last_updated_by: nil,
            name: nil,
            subject: nil,
            updated_at: nil

  @type t :: %__MODULE__{
          content_markdown: String.t(),
          created_at: String.t(),
          disabled: boolean(),
          id: String.t(),
          lang: String.t(),
          last_updated_by: String.t(),
          name: String.t(),
          subject: String.t(),
          updated_at: String.t()
        }
end
