# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.RecordWithMedia.Main do
  @moduledoc """
  **main** (object/record)

  No description.
  """

  @enforce_keys [:record, :media]
  defstruct media: nil, record: nil

  @type t :: %__MODULE__{
          media:
            ProtoRune.App.Bsky.Embed.Images.Main.t()
            | ProtoRune.App.Bsky.Embed.Video.Main.t()
            | ProtoRune.App.Bsky.Embed.External.Main.t(),
          record: ProtoRune.App.Bsky.Embed.Record.Main.t()
        }
end
