# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.EmitEvent.Main do
  @moduledoc """
  **main** (procedure)

  Take a moderation action on an actor.
  """

  @type input :: any()
  @type output :: any()
end
