# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.GetUnreadCount do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{priority: boolean(), seen_at: String.t()}
end
