# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.ListNotifications do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cursor: String.t(), limit: integer(), priority: boolean(), seen_at: String.t()}
end
