# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.PutPreferences do
  @moduledoc """
  Generated procedure module for main

  **Description**: Set notification-related preferences for an account. Requires auth.
  """

  @type input :: %{priority: boolean()}
end
