# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.RegisterPush do
  @moduledoc """
  Generated procedure module for main

  **Description**: Register to receive push notifications, via a specified service, for the requesting account. Requires auth.
  """

  @type input :: %{
          app_id: String.t(),
          platform: :ios | :android | :web,
          service_did: String.t(),
          token: String.t()
        }
end
