# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.UpdateSeen do
  @moduledoc """
  Generated procedure module for main

  **Description**: Notify server that the requesting account has seen notifications. Requires auth.
  """

  @type input :: %{seen_at: String.t()}
end
