# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RefreshSession.Main do
  @moduledoc """
  **main** (procedure)

  Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
  """

  @type input :: any()
  @type output :: any()
end
