# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.ListMembers.Main do
  @moduledoc """
  **main** (query)

  List all members with access to the ozone service.
  """

  @type input :: any()
  @type output :: any()
end
