# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.DeleteRecord.Main do
  @moduledoc """
  **main** (procedure)

  Delete a repository record, or ensure it doesn't exist. Requires auth, implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
