# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.QueryStatuses.Main do
  @moduledoc """
  **main** (query)

  View moderation statuses of subjects (record or repo).
  """

  @type input :: any()
  @type output :: any()
end
