# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.RegisterPush.Main do
  @moduledoc """
  **main** (procedure)

  Register to receive push notifications, via a specified service, for the requesting account. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
