# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.External do
  @moduledoc """
  Generated schema for main

  **Description**: A representation of some externally linked content (eg, a URL and 'card'), embedded in a Bluesky record (eg, a post).
  """

  @enforce_keys [:external]
  defstruct external: nil

  @type t :: %__MODULE__{
          external: ProtoRune.App.Bsky.Embed.External.External.t()
        }
end
