# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:images]
  defstruct images: nil

  @type t :: %__MODULE__{
          images: list(ProtoRune.App.Bsky.Embed.Images.Image.t())
        }
end
