# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Record do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:record]
  defstruct record: nil

  @type t :: %__MODULE__{
          record: ProtoRune.Com.Atproto.Repo.StrongRef.t()
        }
end
