# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.RecordWithMedia do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:record, :media]
  defstruct media: nil, record: nil

  @type t :: %__MODULE__{
          media:
            ProtoRune.App.Bsky.Embed.Images.t()
            | ProtoRune.App.Bsky.Embed.Video.t()
            | ProtoRune.App.Bsky.Embed.External.t(),
          record: ProtoRune.App.Bsky.Embed.Record.t()
        }
end
