# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Video do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:video]
  defstruct alt: nil, aspect_ratio: nil, captions: nil, video: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspect_ratio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          captions: list(ProtoRune.App.Bsky.Embed.Video.Caption.t()),
          video: binary()
        }
end
