# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.SignPlcOperation.Main do
  @moduledoc """
  **main** (procedure)

  Signs a PLC operation to update some value(s) in the requesting DID's document.
  """

  @type input :: any()
  @type output :: any()
end
