# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.DescribeFeedGenerator.Links do
  @moduledoc """
  Generated schema for links

  **Description**: No description provided.
  """

  defstruct privacy_policy: nil, terms_of_service: nil

  @type t :: %__MODULE__{
          privacy_policy: String.t(),
          terms_of_service: String.t()
        }
end
