# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Postgate.DisableRule do
  @moduledoc """
  **disableRule** (object/record)

  Disables embedding of this post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
