# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Postgate.Main do
  @moduledoc """
  **main** (object/record)

  Record defining interaction rules for a post. The record key (rkey) of the postgate record must match the record key of the post, and that record must be in the same repository.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
