# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.SearchActorsSkeleton.Main do
  @moduledoc """
  **main** (query)

  Backend Actors (profile) search, returns only skeleton.
  """

  @type input :: any()
  @type output :: any()
end
