# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeleteAccount.Main do
  @moduledoc """
  **main** (procedure)

  Delete an actor's account with a token and password. Can only be called after requesting a deletion token. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
