# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.LabelValue do
  @moduledoc """
  Generated schema for labelValue

  **Description**: No description provided.
  """

  @type t ::
          :"!hide"
          | :"!no-promote"
          | :"!warn"
          | :"!no-unauthenticated"
          | :"dmca-violation"
          | :doxxing
          | :porn
          | :sexual
          | :nudity
          | :nsfl
          | :gore
end
