# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinition do
  @moduledoc """
  Generated schema for labelValueDefinition

  **Description**: Declares a label value and its expected interpretations and behaviors.
  """

  @enforce_keys [:identifier, :severity, :blurs, :locales]
  defstruct adult_only: nil,
            blurs: nil,
            default_setting: nil,
            identifier: nil,
            locales: nil,
            severity: nil

  @type t :: %__MODULE__{
          adult_only: boolean(),
          blurs: :content | :media | :none,
          default_setting: :ignore | :warn | :hide,
          identifier: String.t(),
          locales: list(ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinitionStrings.t()),
          severity: :inform | :alert | :none
        }
end
