# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinitionStrings do
  @moduledoc """
  Generated schema for labelValueDefinitionStrings

  **Description**: Strings which describe the label in the UI, localized into a specific language.
  """

  @enforce_keys [:lang, :name, :description]
  defstruct description: nil, lang: nil, name: nil

  @type t :: %__MODULE__{
          description: String.t(),
          lang: String.t(),
          name: String.t()
        }
end
