# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Signature.FindRelatedAccounts.Main do
  @moduledoc """
  **main** (query)

  Get accounts that share some matching threat signatures with the root account.
  """

  @type input :: any()
  @type output :: any()
end
