# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Signature.FindRelatedAccounts.RelatedAccount do
  @moduledoc """
  **relatedAccount** (object/record)

  No description.
  """

  @enforce_keys [:account]
  defstruct account: nil, similarities: nil

  @type t :: %__MODULE__{
          account: ProtoRune.Com.Atproto.Admin.Defs.AccountView.t(),
          similarities: list(ProtoRune.Tools.Ozone.Signature.Defs.SigDetail.t())
        }
end
