# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.SearchActorsTypeahead.Main do
  @moduledoc """
  **main** (query)

  Find actor suggestions for a prefix search term. Expected use is for auto-completion during text field entry. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
