# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetActorStarterPacks.Main do
  @moduledoc """
  **main** (query)

  Get a list of starter packs created by the actor.
  """

  @type input :: any()
  @type output :: any()
end
