# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.EnableAccountInvites.Main do
  @moduledoc """
  **main** (procedure)

  Re-enable an account's ability to receive invite codes.
  """

  @type input :: any()
  @type output :: any()
end
