# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images.Image do
  @moduledoc """
  Generated schema for image

  **Description**: No description provided.
  """

  @enforce_keys [:image, :alt]
  defstruct alt: nil, aspect_ratio: nil, image: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspect_ratio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          image: binary()
        }
end
