# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Images.ViewImage do
  @moduledoc """
  Generated schema for viewImage

  **Description**: No description provided.
  """

  @enforce_keys [:thumb, :fullsize, :alt]
  defstruct alt: nil, aspect_ratio: nil, fullsize: nil, thumb: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspect_ratio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          fullsize: String.t(),
          thumb: String.t()
        }
end
