# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetPopularFeedGenerators.Main do
  @moduledoc """
  **main** (query)

  An unspecced view of globally popular feed generators.
  """

  @type input :: any()
  @type output :: any()
end
