# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.DeleteTemplate do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete a communication template.
  """

  @type input :: %{id: String.t()}
end
