# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.ListTemplates do
  @moduledoc """
  Generated query module for main

  **Description**: Get list of all communication templates.
  """

  @type output :: %{
          communication_templates: list(ProtoRune.Tools.Ozone.Communication.Defs.TemplateView.t())
        }
end
