# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.UpdateTemplate do
  @moduledoc """
  Generated procedure module for main

  **Description**: Administrative action to update an existing communication template. Allows passing partial fields to patch specific fields only.
  """

  @type output :: ProtoRune.Tools.Ozone.Communication.Defs.TemplateView.t()
  @type input :: %{
          content_markdown: String.t(),
          disabled: boolean(),
          id: String.t(),
          lang: String.t(),
          name: String.t(),
          subject: String.t(),
          updated_by: String.t()
        }
  @type error ::
          ProtoRune.Tools.Ozone.Communication.UpdateTemplate.MainErrorDuplicateTemplateName.t()
end
