# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.AddMember.MainErrorMemberAlreadyExists do
  @moduledoc """
  Generated schema for mainErrorMemberAlreadyExists

  **Description**: No description provided.
  """

  @type t :: any()
end
