# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Signature.FindCorrelation.Main do
  @moduledoc """
  **main** (query)

  Find all correlated threat signatures between 2 or more accounts.
  """

  @type input :: any()
  @type output :: any()
end
