# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetStarterPacks do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{uris: list(String.t())}
end
