# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetSuggestedFollowsByActor do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{actor: String.t()}
end
