# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetStarterPack do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{starter_pack: String.t()}
end
