# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetRelationships do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{actor: String.t(), others: list(String.t())}
end
