# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Listitem do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:subject, :list, :created_at]
  defstruct created_at: nil, list: nil, subject: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          list: String.t(),
          subject: String.t()
        }
end
