# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.MuteThread do
  @moduledoc """
  Generated procedure module for main

  **Description**: Mutes a thread preventing notifications from the thread and any of its children. Mutes are private in Bluesky. Requires auth.
  """

  @type input :: %{root: String.t()}
end
