# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.MuteActor do
  @moduledoc """
  Generated procedure module for main

  **Description**: Creates a mute relationship for the specified account. Mutes are private in Bluesky. Requires auth.
  """

  @type input :: %{actor: String.t()}
end
