# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.MuteActorList do
  @moduledoc """
  Generated procedure module for main

  **Description**: Creates a mute relationship for the specified list of accounts. Mutes are private in Bluesky. Requires auth.
  """

  @type input :: %{list: String.t()}
end
