# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Starterpack do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:name, :list, :created_at]
  defstruct created_at: nil,
            description: nil,
            description_facets: nil,
            feeds: nil,
            list: nil,
            name: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          description: String.t(),
          description_facets: list(ProtoRune.App.Bsky.Richtext.Facet.t()),
          feeds: list(ProtoRune.App.Bsky.Graph.Starterpack.FeedItem.t()),
          list: String.t(),
          name: String.t()
        }
end
