# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.UnmuteActor do
  @moduledoc """
  Generated procedure module for main

  **Description**: Unmutes the specified account. Requires auth.
  """

  @type input :: %{actor: String.t()}
end
