# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.UnmuteActorList do
  @moduledoc """
  Generated procedure module for main

  **Description**: Unmutes the specified list of accounts. Requires auth.
  """

  @type input :: %{list: String.t()}
end
