# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.UnmuteThread do
  @moduledoc """
  Generated procedure module for main

  **Description**: Unmutes the specified thread. Requires auth.
  """

  @type input :: %{root: String.t()}
end
