# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.QueryLabels.Main do
  @moduledoc """
  **main** (query)

  Find labels relevant to the provided AT-URI patterns. Public endpoint for moderation services, though may return different or additional results with auth.
  """

  @type input :: any()
  @type output :: any()
end
