# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Richtext.Facet.Link do
  @moduledoc """
  **link** (object/record)

  Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL.
  """

  @enforce_keys [:uri]
  defstruct uri: nil

  @type t :: %__MODULE__{
          uri: String.t()
        }
end
