# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Richtext.Facet.Tag do
  @moduledoc """
  **tag** (object/record)

  Facet feature for a hashtag. The text usually includes a '#' prefix, but the facet reference should not (except in the case of 'double hash tags').
  """

  @enforce_keys [:tag]
  defstruct tag: nil

  @type t :: %__MODULE__{
          tag: String.t()
        }
end
