# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetBlocks.Main do
  @moduledoc """
  **main** (query)

  Get data blocks from a given repo, by CID. For example, intermediate MST nodes, or records. Does not require auth; implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
