# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate.FollowingRule do
  @moduledoc """
  **followingRule** (object/record)

  Allow replies from actors you follow.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
