# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate.Main do
  @moduledoc """
  **main** (object/record)

  Record defining interaction gating rules for a thread (aka, reply controls). The record key (rkey) of the threadgate record must match the record key of the thread's root post, and that record must be in the same repository.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
