# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate.MentionRule do
  @moduledoc """
  **mentionRule** (object/record)

  Allow replies from actors mentioned in your post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
