# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.DeleteValues.Main do
  @moduledoc """
  **main** (procedure)

  Delete values from a specific set. Attempting to delete values that are not in the set will not result in an error
  """

  @type input :: any()
  @type output :: any()
end
