# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateSession.Main do
  @moduledoc """
  **main** (procedure)

  Create an authentication session.
  """

  @type input :: any()
  @type output :: any()
end
