# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.Defs.InviteCode do
  @moduledoc """
  Generated schema for inviteCode

  **Description**: No description provided.
  """

  @enforce_keys [:code, :available, :disabled, :for_account, :created_by, :created_at, :uses]
  defstruct available: nil,
            code: nil,
            created_at: nil,
            created_by: nil,
            disabled: nil,
            for_account: nil,
            uses: nil

  @type t :: %__MODULE__{
          available: integer(),
          code: String.t(),
          created_at: String.t(),
          created_by: String.t(),
          disabled: boolean(),
          for_account: String.t(),
          uses: list(ProtoRune.Com.Atproto.Server.Defs.InviteCodeUse.t())
        }
end
