# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.Defs.InviteCodeUse do
  @moduledoc """
  Generated schema for inviteCodeUse

  **Description**: No description provided.
  """

  @enforce_keys [:used_by, :used_at]
  defstruct used_at: nil, used_by: nil

  @type t :: %__MODULE__{
          used_at: String.t(),
          used_by: String.t()
        }
end
