# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Server.GetConfig.Main do
  @moduledoc """
  **main** (query)

  Get details about ozone's server configuration.
  """

  @type input :: any()
  @type output :: any()
end
