# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Server.GetConfig.ServiceConfig do
  @moduledoc """
  **serviceConfig** (object/record)

  No description.
  """

  defstruct url: nil

  @type t :: %__MODULE__{
          url: String.t()
        }
end
