# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.Entity do
  @moduledoc """
  Generated schema for entity

  **Description**: No description provided.
  """

  @type t :: String.t()
end
