# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.ReplyRef do
  @moduledoc """
  Generated schema for replyRef

  **Description**: No description provided.
  """

  @enforce_keys [:root, :parent]
  defstruct parent: nil, root: nil

  @type t :: %__MODULE__{
          parent: ProtoRune.Com.Atproto.Repo.StrongRef.t(),
          root: ProtoRune.Com.Atproto.Repo.StrongRef.t()
        }
end
