# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.TextSlice do
  @moduledoc """
  Generated schema for textSlice

  **Description**: Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.
  """

  @enforce_keys [:start, :end]
  defstruct end: nil, start: nil

  @type t :: %__MODULE__{
          end: integer(),
          start: integer()
        }
end
