# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Like.Main do
  @moduledoc """
  **main** (object/record)

  Record declaring a 'like' of a piece of subject content.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
