# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Setting.ListOptions.Main do
  @moduledoc """
  **main** (query)

  List settings with optional filtering
  """

  @type input :: any()
  @type output :: any()
end
