# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.GetRecommendedDidCredentials do
  @moduledoc """
  Generated query module for main

  **Description**: Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
  """

  @type output :: %{
          also_known_as: list(String.t()),
          rotation_keys: list(String.t()),
          services: any(),
          verification_methods: any()
        }
end
