# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.RequestPlcOperationSignature do
  @moduledoc """
  Generated procedure module for main

  **Description**: Request an email with a code to in order to request a signed PLC operation. Requires Auth.
  """
end
