# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.ResolveHandle do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{handle: String.t()}
end
