# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.SignPlcOperation do
  @moduledoc """
  Generated procedure module for main

  **Description**: Signs a PLC operation to update some value(s) in the requesting DID's document.
  """

  @type output :: %{operation: any()}
  @type input :: %{
          also_known_as: list(String.t()),
          rotation_keys: list(String.t()),
          services: any(),
          token: String.t(),
          verification_methods: any()
        }
end
