# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.UpdateHandle do
  @moduledoc """
  Generated procedure module for main

  **Description**: Updates the current account's handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
  """

  @type input :: %{handle: String.t()}
end
