# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Generator.Main do
  @moduledoc """
  **main** (object/record)

  Record declaring of the existence of a feed generator, and containing metadata about it. The record can exist in any repository.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
