# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.Defs.StatusAttr do
  @moduledoc """
  **statusAttr** (object/record)

  No description.
  """

  @enforce_keys [:applied]
  defstruct applied: nil, ref: nil

  @type t :: %__MODULE__{
          applied: boolean(),
          ref: String.t()
        }
end
