# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.Defs.ThreatSignature do
  @moduledoc """
  **threatSignature** (object/record)

  No description.
  """

  @enforce_keys [:property, :value]
  defstruct property: nil, value: nil

  @type t :: %__MODULE__{
          property: String.t(),
          value: String.t()
        }
end
