# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Signature.SearchAccounts.Main do
  @moduledoc """
  **main** (query)

  Search for accounts that match one or more threat signature values.
  """

  @type input :: any()
  @type output :: any()
end
