# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestPasswordReset.Main do
  @moduledoc """
  **main** (procedure)

  Initiate a user account password reset via email.
  """

  @type input :: any()
  @type output :: any()
end
