# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.UnmuteThread.Main do
  @moduledoc """
  **main** (procedure)

  Unmutes the specified thread. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
