# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DeleteAccount do
  @moduledoc """
  Generated procedure module for main

  **Description**: Delete a user account as an administrator.
  """

  @type input :: %{did: String.t()}
end
