# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DisableAccountInvites do
  @moduledoc """
  Generated procedure module for main

  **Description**: Disable an account from receiving new invite codes, but does not invalidate existing codes.
  """

  @type input :: %{account: String.t(), note: String.t()}
end
