# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DisableInviteCodes do
  @moduledoc """
  Generated procedure module for main

  **Description**: Disable some set of codes and/or all codes associated with a set of users.
  """

  @type input :: %{accounts: list(String.t()), codes: list(String.t())}
end
