# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.EnableAccountInvites do
  @moduledoc """
  Generated procedure module for main

  **Description**: Re-enable an account's ability to receive invite codes.
  """

  @type input :: %{account: String.t(), note: String.t()}
end
