# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetAccountInfos do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{dids: list(String.t())}
end
