# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetSubjectStatus do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{blob: String.t(), did: String.t(), uri: String.t()}
end
