# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetAccountInfo do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{did: String.t()}
end
