# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.SendEmail do
  @moduledoc """
  Generated procedure module for main

  **Description**: Send email to a user's account email address.
  """

  @type output :: %{sent: boolean()}
  @type input :: %{
          comment: String.t(),
          content: String.t(),
          recipient_did: String.t(),
          sender_did: String.t(),
          subject: String.t()
        }
end
