# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateAccountPassword do
  @moduledoc """
  Generated procedure module for main

  **Description**: Update the password for a user account as an administrator.
  """

  @type input :: %{did: String.t(), password: String.t()}
end
