# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateAccountHandle do
  @moduledoc """
  Generated procedure module for main

  **Description**: Administrative action to update an account's handle.
  """

  @type input :: %{did: String.t(), handle: String.t()}
end
