# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateAccountEmail do
  @moduledoc """
  Generated procedure module for main

  **Description**: Administrative action to update an account's email.
  """

  @type input :: %{account: String.t(), email: String.t()}
end
