# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateSubjectStatus do
  @moduledoc """
  Generated procedure module for main

  **Description**: Update the service-specific admin status of a subject (account, record, or blob).
  """

  @type output :: %{
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t()
            | ProtoRune.Com.Atproto.Admin.Defs.RepoBlobRef.t(),
          takedown: ProtoRune.Com.Atproto.Admin.Defs.StatusAttr.t()
        }
  @type input :: %{
          deactivated: ProtoRune.Com.Atproto.Admin.Defs.StatusAttr.t(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t()
            | ProtoRune.Com.Atproto.Admin.Defs.RepoBlobRef.t(),
          takedown: ProtoRune.Com.Atproto.Admin.Defs.StatusAttr.t()
        }
end
