# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetAccountInviteCodes.Main do
  @moduledoc """
  **main** (query)

  Get all invite codes for the current account. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
