# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.List.Main do
  @moduledoc """
  **main** (object/record)

  Record representing a list of accounts (actors). Scope includes both moderation-oriented lists and curration-oriented lists.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
