# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.EmitEvent do
  @moduledoc """
  Generated procedure module for main

  **Description**: Take a moderation action on an actor.
  """

  @type output :: ProtoRune.Tools.Ozone.Moderation.Defs.ModEventView.t()
  @type input :: %{
          created_by: String.t(),
          event:
            ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEscalate.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventComment.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReverseTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTag.t(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t(),
          subject_blob_cids: list(String.t())
        }
  @type error :: ProtoRune.Tools.Ozone.Moderation.EmitEvent.MainErrorSubjectHasAction.t()
end
