# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetEvent do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{id: integer()}
end
