# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRecord do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cid: String.t(), uri: String.t()}
end
