# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRepo do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{did: String.t()}
end
