# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.QueryEvents do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          added_labels: list(String.t()),
          added_tags: list(String.t()),
          comment: String.t(),
          created_after: String.t(),
          created_before: String.t(),
          created_by: String.t(),
          cursor: String.t(),
          has_comment: boolean(),
          include_all_user_records: boolean(),
          limit: integer(),
          removed_labels: list(String.t()),
          removed_tags: list(String.t()),
          report_types: list(String.t()),
          sort_direction: :asc | :desc,
          subject: String.t(),
          types: list(String.t())
        }
end
