# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.QueryStatuses do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          appealed: boolean(),
          comment: String.t(),
          cursor: String.t(),
          exclude_tags: list(String.t()),
          ignore_subjects: list(String.t()),
          include_all_user_records: boolean(),
          include_muted: boolean(),
          last_reviewed_by: String.t(),
          limit: integer(),
          only_muted: boolean(),
          reported_after: String.t(),
          reported_before: String.t(),
          review_state: String.t(),
          reviewed_after: String.t(),
          reviewed_before: String.t(),
          sort_direction: :asc | :desc,
          sort_field: :lastReviewedAt | :lastReportedAt,
          subject: String.t(),
          tags: list(String.t()),
          takendown: boolean()
        }
end
