# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Postgate.DisableRule do
  @moduledoc """
  Generated schema for disableRule

  **Description**: Disables embedding of this post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
