# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Profile.Main do
  @moduledoc """
  **main** (object/record)

  A declaration of a Bluesky account profile.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
