# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.FetchLabels.Main do
  @moduledoc """
  **main** (query)

  DEPRECATED: use queryLabels or subscribeLabels instead -- Fetch all labels from a labeler created after a certain date.
  """

  @type input :: any()
  @type output :: any()
end
