# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.Defs.RepoBlobRef do
  @moduledoc """
  Generated schema for repoBlobRef

  **Description**: No description provided.
  """

  @enforce_keys [:did, :cid]
  defstruct cid: nil, did: nil, record_uri: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          did: String.t(),
          record_uri: String.t()
        }
end
