# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.Defs.StatusAttr do
  @moduledoc """
  Generated schema for statusAttr

  **Description**: No description provided.
  """

  @enforce_keys [:applied]
  defstruct applied: nil, ref: nil

  @type t :: %__MODULE__{
          applied: boolean(),
          ref: String.t()
        }
end
