# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.DeleteMember.Main do
  @moduledoc """
  **main** (procedure)

  Delete a member from ozone team. Requires admin role.
  """

  @type input :: any()
  @type output :: any()
end
