# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.GetRecommendedDidCredentials.Main do
  @moduledoc """
  **main** (query)

  Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
  """

  @type input :: any()
  @type output :: any()
end
