# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.Entity do
  @moduledoc """
  **entity** (object/record)

  Deprecated: use facets instead.
  """

  @enforce_keys [:index, :type, :value]
  defstruct index: nil, type: nil, value: nil

  @type t :: %__MODULE__{
          index: ProtoRune.App.Bsky.Feed.Post.TextSlice.t(),
          type: String.t(),
          value: String.t()
        }
end
