# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.Main do
  @moduledoc """
  **main** (object/record)

  Record containing a Bluesky post.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
