# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.ReplyRef do
  @moduledoc """
  **replyRef** (object/record)

  No description.
  """

  @enforce_keys [:root, :parent]
  defstruct parent: nil, root: nil

  @type t :: %__MODULE__{
          parent: ProtoRune.Com.Atproto.Repo.StrongRef.Main.t(),
          root: ProtoRune.Com.Atproto.Repo.StrongRef.Main.t()
        }
end
