# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post.ReplyRef do
  @moduledoc """
  **replyRef** (object/record)

  No description.
  """

  alias ProtoRune.Com.Atproto.Repo.StrongRef.Main

  @enforce_keys [:root, :parent]
  defstruct parent: nil, root: nil

  @type t :: %__MODULE__{
          parent: Main.t(),
          root: Main.t()
        }
end
