# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.Follow.Main do
  @moduledoc """
  **main** (object/record)

  Record declaring a social 'follow' relationship of another account. Duplicate follows will be ignored by the AppView.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
