# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateInviteCodes.AccountCodes do
  @moduledoc """
  **accountCodes** (object/record)

  No description.
  """

  @enforce_keys [:account, :codes]
  defstruct account: nil, codes: nil

  @type t :: %__MODULE__{
          account: String.t(),
          codes: list(String.t())
        }
end
