# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateInviteCodes.Main do
  @moduledoc """
  **main** (procedure)

  Create invite codes.
  """

  @type input :: any()
  @type output :: any()
end
