# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRecords.Main do
  @moduledoc """
  **main** (query)

  Get details about some records.
  """

  @type input :: any()
  @type output :: any()
end
