# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeleteAccount.MainErrorExpiredToken do
  @moduledoc """
  Generated schema for mainErrorExpiredToken

  **Description**: No description provided.
  """

  @type t :: any()
end
