# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ReserveSigningKey.Main do
  @moduledoc """
  **main** (procedure)

  Reserve a repo signing key, for use with account creation. Necessary so that a DID PLC update operation can be constructed during an account migraiton. Public and does not require auth; implemented by PDS. NOTE: this endpoint may change when full account migration is implemented.
  """

  @type input :: any()
  @type output :: any()
end
