# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.UpdateMember.Main do
  @moduledoc """
  **main** (procedure)

  Update a member in the ozone service. Requires admin role.
  """

  @type input :: any()
  @type output :: any()
end
