# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetSuggestedFeeds.Main do
  @moduledoc """
  **main** (query)

  Get a list of suggested feeds (feed generators) for the requesting account.
  """

  @type input :: any()
  @type output :: any()
end
