# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorAccountNotFound do
  @moduledoc """
  Generated schema for mainErrorAccountNotFound

  **Description**: No description provided.
  """

  @type t :: any()
end
