# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorInvalidEmail do
  @moduledoc """
  Generated schema for mainErrorInvalidEmail

  **Description**: No description provided.
  """

  @type t :: any()
end
