# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ConfirmEmail.MainErrorInvalidToken do
  @moduledoc """
  Generated schema for mainErrorInvalidToken

  **Description**: No description provided.
  """

  @type t :: any()
end
