# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetLikes.Like do
  @moduledoc """
  Generated schema for like

  **Description**: No description provided.
  """

  @enforce_keys [:indexed_at, :created_at, :actor]
  defstruct actor: nil, created_at: nil, indexed_at: nil

  @type t :: %__MODULE__{
          actor: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          created_at: String.t(),
          indexed_at: String.t()
        }
end
