# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.BlockedPost do
  @moduledoc """
  Generated schema for blockedPost

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :blocked, :author]
  defstruct author: nil, blocked: nil, uri: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Feed.Defs.BlockedAuthor.t(),
          blocked: boolean(),
          uri: String.t()
        }
end
