# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.BlockedAuthor do
  @moduledoc """
  Generated schema for blockedAuthor

  **Description**: No description provided.
  """

  @enforce_keys [:did]
  defstruct did: nil, viewer: nil

  @type t :: %__MODULE__{
          did: String.t(),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
