# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ClickthroughReposter do
  @moduledoc """
  Token type for clickthroughReposter

  **Description**: User clicked through to the reposter of the feed item
  """

  @type t :: atom()
end
