# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ClickthroughItem do
  @moduledoc """
  Token type for clickthroughItem

  **Description**: User clicked through to the feed item
  """

  @type t :: atom()
end
