# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ClickthroughAuthor do
  @moduledoc """
  Token type for clickthroughAuthor

  **Description**: User clicked through to the author of the feed item
  """

  @type t :: atom()
end
