# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ClickthroughEmbed do
  @moduledoc """
  Token type for clickthroughEmbed

  **Description**: User clicked through to the embedded content of the feed item
  """

  @type t :: atom()
end
