# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.FeedViewPost do
  @moduledoc """
  Generated schema for feedViewPost

  **Description**: No description provided.
  """

  @enforce_keys [:post]
  defstruct feed_context: nil, post: nil, reason: nil, reply: nil

  @type t :: %__MODULE__{
          feed_context: String.t(),
          post: ProtoRune.App.Bsky.Feed.Defs.PostView.t(),
          reason: ProtoRune.App.Bsky.Feed.Defs.ReasonRepost.t(),
          reply: ProtoRune.App.Bsky.Feed.Defs.ReplyRef.t()
        }
end
