# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.GeneratorView do
  @moduledoc """
  Generated schema for generatorView

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :cid, :did, :creator, :display_name, :indexed_at]
  defstruct accepts_interactions: nil,
            avatar: nil,
            cid: nil,
            creator: nil,
            description: nil,
            description_facets: nil,
            did: nil,
            display_name: nil,
            indexed_at: nil,
            labels: nil,
            like_count: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          accepts_interactions: boolean(),
          avatar: String.t(),
          cid: String.t(),
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          description: String.t(),
          description_facets: list(ProtoRune.App.Bsky.Richtext.Facet.t()),
          did: String.t(),
          display_name: String.t(),
          indexed_at: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          like_count: integer(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Feed.Defs.GeneratorViewerState.t()
        }
end
