# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.GeneratorViewerState do
  @moduledoc """
  Generated schema for generatorViewerState

  **Description**: No description provided.
  """

  defstruct like: nil

  @type t :: %__MODULE__{
          like: String.t()
        }
end
