# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionRepost do
  @moduledoc """
  Token type for interactionRepost

  **Description**: User reposted the feed item
  """

  @type t :: atom()
end
