# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionSeen do
  @moduledoc """
  Token type for interactionSeen

  **Description**: Feed item was seen by user
  """

  @type t :: atom()
end
