# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionQuote do
  @moduledoc """
  Token type for interactionQuote

  **Description**: User quoted the feed item
  """

  @type t :: atom()
end
