# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionReply do
  @moduledoc """
  Token type for interactionReply

  **Description**: User replied to the feed item
  """

  @type t :: atom()
end
