# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionLike do
  @moduledoc """
  Token type for interactionLike

  **Description**: User liked the feed item
  """

  @type t :: atom()
end
