# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.InteractionShare do
  @moduledoc """
  Token type for interactionShare

  **Description**: User shared the feed item
  """

  @type t :: atom()
end
