# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.PostView do
  @moduledoc """
  Generated schema for postView

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :cid, :author, :record, :indexed_at]
  defstruct author: nil,
            cid: nil,
            embed: nil,
            indexed_at: nil,
            labels: nil,
            like_count: nil,
            quote_count: nil,
            record: nil,
            reply_count: nil,
            repost_count: nil,
            threadgate: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          cid: String.t(),
          embed:
            ProtoRune.App.Bsky.Embed.Images.View.t()
            | ProtoRune.App.Bsky.Embed.Video.View.t()
            | ProtoRune.App.Bsky.Embed.External.View.t()
            | ProtoRune.App.Bsky.Embed.Record.View.t()
            | ProtoRune.App.Bsky.Embed.RecordWithMedia.View.t(),
          indexed_at: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          like_count: integer(),
          quote_count: integer(),
          record: any(),
          reply_count: integer(),
          repost_count: integer(),
          threadgate: ProtoRune.App.Bsky.Feed.Defs.ThreadgateView.t(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Feed.Defs.ViewerState.t()
        }
end
