# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ReplyRef do
  @moduledoc """
  Generated schema for replyRef

  **Description**: No description provided.
  """

  @enforce_keys [:root, :parent]
  defstruct grandparent_author: nil, parent: nil, root: nil

  @type t :: %__MODULE__{
          grandparent_author: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          parent:
            ProtoRune.App.Bsky.Feed.Defs.PostView.t()
            | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t(),
          root:
            ProtoRune.App.Bsky.Feed.Defs.PostView.t()
            | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t()
        }
end
