# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.RequestMore do
  @moduledoc """
  Token type for requestMore

  **Description**: Request that more content like the given feed item be shown in the feed
  """

  @type t :: atom()
end
