# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.RequestLess do
  @moduledoc """
  Token type for requestLess

  **Description**: Request that less content like the given feed item be shown in the feed
  """

  @type t :: atom()
end
