# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonRepost do
  @moduledoc """
  Generated schema for skeletonReasonRepost

  **Description**: No description provided.
  """

  @enforce_keys [:repost]
  defstruct repost: nil

  @type t :: %__MODULE__{
          repost: String.t()
        }
end
