# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.SkeletonFeedPost do
  @moduledoc """
  Generated schema for skeletonFeedPost

  **Description**: No description provided.
  """

  @enforce_keys [:post]
  defstruct feed_context: nil, post: nil, reason: nil

  @type t :: %__MODULE__{
          feed_context: String.t(),
          post: String.t(),
          reason: ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonRepost.t()
        }
end
