# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ViewerState do
  @moduledoc """
  Generated schema for viewerState

  **Description**: Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.
  """

  defstruct embedding_disabled: nil,
            like: nil,
            reply_disabled: nil,
            repost: nil,
            thread_muted: nil

  @type t :: %__MODULE__{
          embedding_disabled: boolean(),
          like: String.t(),
          reply_disabled: boolean(),
          repost: String.t(),
          thread_muted: boolean()
        }
end
