# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Identity.SubmitPlcOperation.Main do
  @moduledoc """
  **main** (procedure)

  Validates a PLC operation to ensure that it doesn't violate a service's constraints or get the identity into a bad state, then submits it to the PLC registry
  """

  @type input :: any()
  @type output :: any()
end
