# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetProfiles.Main do
  @moduledoc """
  **main** (query)

  Get detailed profile views of multiple actors.
  """

  @type input :: any()
  @type output :: any()
end
