# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DisableInviteCodes.Main do
  @moduledoc """
  **main** (procedure)

  Disable some set of codes and/or all codes associated with a set of users.
  """

  @type input :: any()
  @type output :: any()
end
