# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DeleteAccount.Main do
  @moduledoc """
  **main** (procedure)

  Delete a user account as an administrator.
  """

  @type input :: any()
  @type output :: any()
end
