# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Video.View do
  @moduledoc """
  Generated schema for view

  **Description**: No description provided.
  """

  @enforce_keys [:cid, :playlist]
  defstruct alt: nil, aspect_ratio: nil, cid: nil, playlist: nil, thumbnail: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspect_ratio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          cid: String.t(),
          playlist: String.t(),
          thumbnail: String.t()
        }
end
