# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRepo.Main do
  @moduledoc """
  **main** (query)

  Get details about a repository.
  """

  @type input :: any()
  @type output :: any()
end
