# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetAccountInfo.Main do
  @moduledoc """
  **main** (query)

  Get details about an account.
  """

  @type input :: any()
  @type output :: any()
end
