# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.ConvoView do
  @moduledoc """
  Generated schema for convoView

  **Description**: No description provided.
  """

  @enforce_keys [:id, :rev, :members, :muted, :unread_count]
  defstruct id: nil, last_message: nil, members: nil, muted: nil, rev: nil, unread_count: nil

  @type t :: %__MODULE__{
          id: String.t(),
          last_message:
            ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView.t(),
          members: list(ProtoRune.Chat.Bsky.Actor.Defs.ProfileViewBasic.t()),
          muted: boolean(),
          rev: String.t(),
          unread_count: integer()
        }
end
