# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView do
  @moduledoc """
  Generated schema for deletedMessageView

  **Description**: No description provided.
  """

  @enforce_keys [:id, :rev, :sender, :sent_at]
  defstruct id: nil, rev: nil, sender: nil, sent_at: nil

  @type t :: %__MODULE__{
          id: String.t(),
          rev: String.t(),
          sender: ProtoRune.Chat.Bsky.Convo.Defs.MessageViewSender.t(),
          sent_at: String.t()
        }
end
