# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.LogCreateMessage do
  @moduledoc """
  Generated schema for logCreateMessage

  **Description**: No description provided.
  """

  @enforce_keys [:rev, :convo_id, :message]
  defstruct convo_id: nil, message: nil, rev: nil

  @type t :: %__MODULE__{
          convo_id: String.t(),
          message:
            ProtoRune.Chat.Bsky.Convo.Defs.MessageView.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.DeletedMessageView.t(),
          rev: String.t()
        }
end
