# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageView do
  @moduledoc """
  Generated schema for messageView

  **Description**: No description provided.
  """

  @enforce_keys [:id, :rev, :text, :sender, :sent_at]
  defstruct embed: nil, facets: nil, id: nil, rev: nil, sender: nil, sent_at: nil, text: nil

  @type t :: %__MODULE__{
          embed: ProtoRune.App.Bsky.Embed.Record.View.t(),
          facets: list(ProtoRune.App.Bsky.Richtext.Facet.t()),
          id: String.t(),
          rev: String.t(),
          sender: ProtoRune.Chat.Bsky.Convo.Defs.MessageViewSender.t(),
          sent_at: String.t(),
          text: String.t()
        }
end
