# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageRef do
  @moduledoc """
  Generated schema for messageRef

  **Description**: No description provided.
  """

  @enforce_keys [:did, :message_id, :convo_id]
  defstruct convo_id: nil, did: nil, message_id: nil

  @type t :: %__MODULE__{
          convo_id: String.t(),
          did: String.t(),
          message_id: String.t()
        }
end
