# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Chat.Bsky.Convo.Defs.MessageInput do
  @moduledoc """
  Generated schema for messageInput

  **Description**: No description provided.
  """

  @enforce_keys [:text]
  defstruct embed: nil, facets: nil, text: nil

  @type t :: %__MODULE__{
          embed: ProtoRune.App.Bsky.Embed.Record.t(),
          facets: list(ProtoRune.App.Bsky.Richtext.Facet.t()),
          text: String.t()
        }
end
