# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.Defs.Member do
  @moduledoc """
  **member** (object/record)

  No description.
  """

  @enforce_keys [:did, :role]
  defstruct createdAt: nil,
            did: nil,
            disabled: nil,
            lastUpdatedBy: nil,
            profile: nil,
            role: nil,
            updatedAt: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          did: String.t(),
          disabled: boolean(),
          lastUpdatedBy: String.t(),
          profile: ProtoRune.App.Bsky.Actor.Defs.ProfileViewDetailed.t(),
          role: :"#roleAdmin" | :"#roleModerator" | :"#roleTriage",
          updatedAt: String.t()
        }
end
