# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.DeleteMember.MainErrorCannotDeleteSelf do
  @moduledoc """
  Generated schema for mainErrorCannotDeleteSelf

  **Description**: No description provided.
  """

  @type t :: any()
end
