# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Team.DeleteMember.MainErrorMemberNotFound do
  @moduledoc """
  Generated schema for mainErrorMemberNotFound

  **Description**: No description provided.
  """

  @type t :: any()
end
