# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Repo.ImportRepo.Main do
  @moduledoc """
  **main** (procedure)

  Import a repo in the form of a CAR file. Requires Content-Length HTTP header to be set.
  """

  @type input :: any()
  @type output :: any()
end
