# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.GetJobStatus.Main do
  @moduledoc """
  **main** (query)

  Get status details for a video processing job.
  """

  @type input :: any()
  @type output :: any()
end
