# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.QueryLabels do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          cursor: String.t(),
          limit: integer(),
          sources: list(String.t()),
          uri_patterns: list(String.t())
        }
end
