# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.SubscribeLabels do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cursor: integer()}
end
