# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.BlobView do
  @moduledoc """
  Generated schema for blobView

  **Description**: No description provided.
  """

  @enforce_keys [:cid, :mime_type, :size, :created_at]
  defstruct cid: nil, created_at: nil, details: nil, mime_type: nil, moderation: nil, size: nil

  @type t :: %__MODULE__{
          cid: String.t(),
          created_at: String.t(),
          details:
            ProtoRune.Tools.Ozone.Moderation.Defs.ImageDetails.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.VideoDetails.t(),
          mime_type: String.t(),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.Moderation.t(),
          size: integer()
        }
end
