# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter do
  @moduledoc """
  Generated schema for modEventUnmuteReporter

  **Description**: Unmute incoming reports from an account
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
