# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge do
  @moduledoc """
  Generated schema for modEventAcknowledge

  **Description**: No description provided.
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
