# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmute do
  @moduledoc """
  Generated schema for modEventUnmute

  **Description**: Unmute action on a subject
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
