# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventView do
  @moduledoc """
  Generated schema for modEventView

  **Description**: No description provided.
  """

  @enforce_keys [:id, :event, :subject, :subject_blob_cids, :created_by, :created_at]
  defstruct created_at: nil,
            created_by: nil,
            creator_handle: nil,
            event: nil,
            id: nil,
            subject: nil,
            subject_blob_cids: nil,
            subject_handle: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          created_by: String.t(),
          creator_handle: String.t(),
          event:
            ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReverseTakedown.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventComment.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventAcknowledge.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEscalate.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmute.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventMuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventUnmuteReporter.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventDivert.t()
            | ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTag.t(),
          id: integer(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t()
            | ProtoRune.Chat.Bsky.Convo.Defs.MessageRef.t(),
          subject_blob_cids: list(String.t()),
          subject_handle: String.t()
        }
end
