# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventLabel do
  @moduledoc """
  Generated schema for modEventLabel

  **Description**: Apply/Negate labels on a subject
  """

  @enforce_keys [:create_label_vals, :negate_label_vals]
  defstruct comment: nil, create_label_vals: nil, negate_label_vals: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          create_label_vals: list(String.t()),
          negate_label_vals: list(String.t())
        }
end
