# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventComment do
  @moduledoc """
  Generated schema for modEventComment

  **Description**: Add a comment to a subject
  """

  @enforce_keys [:comment]
  defstruct comment: nil, sticky: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          sticky: boolean()
        }
end
