# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventEmail do
  @moduledoc """
  Generated schema for modEventEmail

  **Description**: Keep a log of outgoing email to a user
  """

  @enforce_keys [:subject_line]
  defstruct comment: nil, content: nil, subject_line: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          content: String.t(),
          subject_line: String.t()
        }
end
