# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTag do
  @moduledoc """
  Generated schema for modEventTag

  **Description**: Add/Remove a tag on a subject
  """

  @enforce_keys [:add, :remove]
  defstruct add: nil, comment: nil, remove: nil

  @type t :: %__MODULE__{
          add: list(String.t()),
          comment: String.t(),
          remove: list(String.t())
        }
end
