# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReport do
  @moduledoc """
  Generated schema for modEventReport

  **Description**: Report a subject
  """

  @enforce_keys [:report_type]
  defstruct comment: nil, is_reporter_muted: nil, report_type: nil

  @type t :: %__MODULE__{
          comment: String.t(),
          is_reporter_muted: boolean(),
          report_type: ProtoRune.Com.Atproto.Moderation.Defs.ReasonType.t()
        }
end
