# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventReverseTakedown do
  @moduledoc """
  Generated schema for modEventReverseTakedown

  **Description**: Revert take down action on a subject
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
