# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventTakedown do
  @moduledoc """
  Generated schema for modEventTakedown

  **Description**: Take down a subject permanently or temporarily
  """

  defstruct acknowledge_account_subjects: nil, comment: nil, duration_in_hours: nil

  @type t :: %__MODULE__{
          acknowledge_account_subjects: boolean(),
          comment: String.t(),
          duration_in_hours: integer()
        }
end
