# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModEventResolveAppeal do
  @moduledoc """
  Generated schema for modEventResolveAppeal

  **Description**: Resolve appeal on a subject
  """

  defstruct comment: nil

  @type t :: %__MODULE__{
          comment: String.t()
        }
end
