# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ModerationDetail do
  @moduledoc """
  Generated schema for moderationDetail

  **Description**: No description provided.
  """

  defstruct subject_status: nil

  @type t :: %__MODULE__{
          subject_status: ProtoRune.Tools.Ozone.Moderation.Defs.SubjectStatusView.t()
        }
end
