# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RecordView do
  @moduledoc """
  Generated schema for recordView

  **Description**: No description provided.
  """

  @enforce_keys [:uri, :cid, :value, :blob_cids, :indexed_at, :moderation, :repo]
  defstruct blob_cids: nil,
            cid: nil,
            indexed_at: nil,
            moderation: nil,
            repo: nil,
            uri: nil,
            value: nil

  @type t :: %__MODULE__{
          blob_cids: list(String.t()),
          cid: String.t(),
          indexed_at: String.t(),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.Moderation.t(),
          repo: ProtoRune.Tools.Ozone.Moderation.Defs.RepoView.t(),
          uri: String.t(),
          value: any()
        }
end
