# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RepoViewDetail do
  @moduledoc """
  Generated schema for repoViewDetail

  **Description**: No description provided.
  """

  @enforce_keys [:did, :handle, :related_records, :indexed_at, :moderation]
  defstruct deactivated_at: nil,
            did: nil,
            email: nil,
            email_confirmed_at: nil,
            handle: nil,
            indexed_at: nil,
            invite_note: nil,
            invited_by: nil,
            invites: nil,
            invites_disabled: nil,
            labels: nil,
            moderation: nil,
            related_records: nil

  @type t :: %__MODULE__{
          deactivated_at: String.t(),
          did: String.t(),
          email: String.t(),
          email_confirmed_at: String.t(),
          handle: String.t(),
          indexed_at: String.t(),
          invite_note: String.t(),
          invited_by: ProtoRune.Com.Atproto.Server.Defs.InviteCode.t(),
          invites: list(ProtoRune.Com.Atproto.Server.Defs.InviteCode.t()),
          invites_disabled: boolean(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          moderation: ProtoRune.Tools.Ozone.Moderation.Defs.ModerationDetail.t(),
          related_records: list(any())
        }
end
