# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.RepoViewNotFound do
  @moduledoc """
  Generated schema for repoViewNotFound

  **Description**: No description provided.
  """

  @enforce_keys [:did]
  defstruct did: nil

  @type t :: %__MODULE__{
          did: String.t()
        }
end
