# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ReviewOpen do
  @moduledoc """
  Token type for reviewOpen

  **Description**: Moderator review status of a subject: Open. Indicates that the subject needs to be reviewed by a moderator
  """

  @type t :: atom()
end
