# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ReviewEscalated do
  @moduledoc """
  Token type for reviewEscalated

  **Description**: Moderator review status of a subject: Escalated. Indicates that the subject was escalated for review by a moderator
  """

  @type t :: atom()
end
