# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.ReviewClosed do
  @moduledoc """
  Token type for reviewClosed

  **Description**: Moderator review status of a subject: Closed. Indicates that the subject was already reviewed and resolved by a moderator
  """

  @type t :: atom()
end
