# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.SubjectStatusView do
  @moduledoc """
  Generated schema for subjectStatusView

  **Description**: No description provided.
  """

  @enforce_keys [:id, :subject, :created_at, :updated_at, :review_state]
  defstruct appealed: nil,
            comment: nil,
            created_at: nil,
            id: nil,
            last_appealed_at: nil,
            last_reported_at: nil,
            last_reviewed_at: nil,
            last_reviewed_by: nil,
            mute_reporting_until: nil,
            mute_until: nil,
            review_state: nil,
            subject: nil,
            subject_blob_cids: nil,
            subject_repo_handle: nil,
            suspend_until: nil,
            tags: nil,
            takendown: nil,
            updated_at: nil

  @type t :: %__MODULE__{
          appealed: boolean(),
          comment: String.t(),
          created_at: String.t(),
          id: integer(),
          last_appealed_at: String.t(),
          last_reported_at: String.t(),
          last_reviewed_at: String.t(),
          last_reviewed_by: String.t(),
          mute_reporting_until: String.t(),
          mute_until: String.t(),
          review_state: ProtoRune.Tools.Ozone.Moderation.Defs.SubjectReviewState.t(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t(),
          subject_blob_cids: list(String.t()),
          subject_repo_handle: String.t(),
          suspend_until: String.t(),
          tags: list(String.t()),
          takendown: boolean(),
          updated_at: String.t()
        }
end
