# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.SubjectReviewState do
  @moduledoc """
  Generated schema for subjectReviewState

  **Description**: No description provided.
  """

  @type t :: :"#reviewOpen" | :"#reviewEscalated" | :"#reviewClosed" | :"#reviewNone"
end
