# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.Defs.VideoDetails do
  @moduledoc """
  Generated schema for videoDetails

  **Description**: No description provided.
  """

  @enforce_keys [:width, :height, :length]
  defstruct height: nil, length: nil, width: nil

  @type t :: %__MODULE__{
          height: integer(),
          length: integer(),
          width: integer()
        }
end
