# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.Defs.JobStatus do
  @moduledoc """
  Generated schema for jobStatus

  **Description**: No description provided.
  """

  @enforce_keys [:job_id, :did, :state]
  defstruct blob: nil, did: nil, error: nil, job_id: nil, message: nil, progress: nil, state: nil

  @type t :: %__MODULE__{
          blob: binary(),
          did: String.t(),
          error: String.t(),
          job_id: String.t(),
          message: String.t(),
          progress: integer(),
          state: :JOB_STATE_COMPLETED | :JOB_STATE_FAILED
        }
end
