# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.ListRepos.Repo do
  @moduledoc """
  Generated schema for repo

  **Description**: No description provided.
  """

  @enforce_keys [:did, :head, :rev]
  defstruct active: nil, did: nil, head: nil, rev: nil, status: nil

  @type t :: %__MODULE__{
          active: boolean(),
          did: String.t(),
          head: String.t(),
          rev: String.t(),
          status: :takendown | :suspended | :deactivated
        }
end
