# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Temp.AddReservedHandle.Main do
  @moduledoc """
  **main** (procedure)

  Add a handle to the set of reserved handles.
  """

  @type input :: any()
  @type output :: any()
end
