# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.CreateReport.Main do
  @moduledoc """
  **main** (procedure)

  Submit a moderation report regarding an atproto account or record. Implemented by moderation services (with PDS proxying), and requires auth.
  """

  @type input :: any()
  @type output :: any()
end
