# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.GetServices do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{detailed: boolean(), dids: list(String.t())}
end
