# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Service do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:policies, :created_at]
  defstruct created_at: nil, labels: nil, policies: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          labels: ProtoRune.Com.Atproto.Label.Defs.SelfLabels.t(),
          policies: ProtoRune.App.Bsky.Labeler.Defs.LabelerPolicies.t()
        }
end
