# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Moderation.CreateReport do
  @moduledoc """
  Generated procedure module for main

  **Description**: Submit a moderation report regarding an atproto account or record. Implemented by moderation services (with PDS proxying), and requires auth.
  """

  @type output :: %{
          created_at: String.t(),
          id: integer(),
          reason: String.t(),
          reason_type: ProtoRune.Com.Atproto.Moderation.Defs.ReasonType.t(),
          reported_by: String.t(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t()
        }
  @type input :: %{
          reason: String.t(),
          reason_type: ProtoRune.Com.Atproto.Moderation.Defs.ReasonType.t(),
          subject:
            ProtoRune.Com.Atproto.Admin.Defs.RepoRef.t()
            | ProtoRune.Com.Atproto.Repo.StrongRef.t()
        }
end
