# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.Defs.Set do
  @moduledoc """
  **set** (object/record)

  No description.
  """

  @enforce_keys [:name]
  defstruct description: nil, name: nil

  @type t :: %__MODULE__{
          description: String.t(),
          name: String.t()
        }
end
