# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.Defs.SetView do
  @moduledoc """
  **setView** (object/record)

  No description.
  """

  @enforce_keys [:name, :setSize, :createdAt, :updatedAt]
  defstruct createdAt: nil, description: nil, name: nil, setSize: nil, updatedAt: nil

  @type t :: %__MODULE__{
          createdAt: String.t(),
          description: String.t(),
          name: String.t(),
          setSize: integer(),
          updatedAt: String.t()
        }
end
