# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.DisableAccountInvites.Main do
  @moduledoc """
  **main** (procedure)

  Disable an account from receiving new invite codes, but does not invalidate existing codes.
  """

  @type input :: any()
  @type output :: any()
end
