# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.GetRecord.Main do
  @moduledoc """
  **main** (query)

  Get details about a record.
  """

  @type input :: any()
  @type output :: any()
end
