# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.SearchStarterPacksSkeleton.Main do
  @moduledoc """
  **main** (query)

  Backend Starter Pack search, returns only skeleton.
  """

  @type input :: any()
  @type output :: any()
end
