# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.BlockedAuthor do
  @moduledoc """
  **blockedAuthor** (object/record)

  No description.
  """

  @enforce_keys [:did]
  defstruct did: nil, viewer: nil

  @type t :: %__MODULE__{
          did: String.t(),
          viewer: ProtoRune.App.Bsky.Actor.Defs.ViewerState.t()
        }
end
