# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.GeneratorViewerState do
  @moduledoc """
  **generatorViewerState** (object/record)

  No description.
  """

  defstruct like: nil

  @type t :: %__MODULE__{
          like: String.t()
        }
end
