# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.GeneratorView do
  @moduledoc """
  **generatorView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :did, :creator, :displayName, :indexedAt]
  defstruct acceptsInteractions: nil,
            avatar: nil,
            cid: nil,
            contentMode: nil,
            creator: nil,
            description: nil,
            descriptionFacets: nil,
            did: nil,
            displayName: nil,
            indexedAt: nil,
            labels: nil,
            likeCount: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          acceptsInteractions: boolean(),
          avatar: String.t(),
          cid: String.t(),
          contentMode: :"app.bsky.feed.defs#contentModeUnspecified" | :"app.bsky.feed.defs#contentModeVideo",
          creator: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          description: String.t(),
          descriptionFacets: list(ProtoRune.App.Bsky.Richtext.Facet.Main.t()),
          did: String.t(),
          displayName: String.t(),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          likeCount: integer(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Feed.Defs.GeneratorViewerState.t()
        }
end
