# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.Interaction do
  @moduledoc """
  **interaction** (object/record)

  No description.
  """

  defstruct event: nil, feedContext: nil, item: nil

  @type t :: %__MODULE__{
          event:
            :"app.bsky.feed.defs#requestLess"
            | :"app.bsky.feed.defs#requestMore"
            | :"app.bsky.feed.defs#clickthroughItem"
            | :"app.bsky.feed.defs#clickthroughAuthor"
            | :"app.bsky.feed.defs#clickthroughReposter"
            | :"app.bsky.feed.defs#clickthroughEmbed"
            | :"app.bsky.feed.defs#interactionSeen"
            | :"app.bsky.feed.defs#interactionLike"
            | :"app.bsky.feed.defs#interactionRepost"
            | :"app.bsky.feed.defs#interactionReply"
            | :"app.bsky.feed.defs#interactionQuote"
            | :"app.bsky.feed.defs#interactionShare",
          feedContext: String.t(),
          item: String.t()
        }
end
