# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.PostView do
  @moduledoc """
  **postView** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :author, :record, :indexedAt]
  defstruct author: nil,
            cid: nil,
            embed: nil,
            indexedAt: nil,
            labels: nil,
            likeCount: nil,
            quoteCount: nil,
            record: nil,
            replyCount: nil,
            repostCount: nil,
            threadgate: nil,
            uri: nil,
            viewer: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          cid: String.t(),
          embed:
            ProtoRune.App.Bsky.Embed.Images.View.t()
            | ProtoRune.App.Bsky.Embed.Video.View.t()
            | ProtoRune.App.Bsky.Embed.External.View.t()
            | ProtoRune.App.Bsky.Embed.Record.View.t()
            | ProtoRune.App.Bsky.Embed.RecordWithMedia.View.t(),
          indexedAt: String.t(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          likeCount: integer(),
          quoteCount: integer(),
          record: any(),
          replyCount: integer(),
          repostCount: integer(),
          threadgate: ProtoRune.App.Bsky.Feed.Defs.ThreadgateView.t(),
          uri: String.t(),
          viewer: ProtoRune.App.Bsky.Feed.Defs.ViewerState.t()
        }
end
