# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ReasonRepost do
  @moduledoc """
  **reasonRepost** (object/record)

  No description.
  """

  @enforce_keys [:by, :indexedAt]
  defstruct by: nil, indexedAt: nil

  @type t :: %__MODULE__{
          by: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          indexedAt: String.t()
        }
end
