# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ReasonPin do
  @moduledoc """
  **reasonPin** (object/record)

  No description.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
