# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ReplyRef do
  @moduledoc """
  **replyRef** (object/record)

  No description.
  """

  alias ProtoRune.App.Bsky.Feed.Defs.BlockedPost
  alias ProtoRune.App.Bsky.Feed.Defs.NotFoundPost
  alias ProtoRune.App.Bsky.Feed.Defs.PostView

  @enforce_keys [:root, :parent]
  defstruct grandparentAuthor: nil, parent: nil, root: nil

  @type t :: %__MODULE__{
          grandparentAuthor: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          parent:
            PostView.t()
            | NotFoundPost.t()
            | BlockedPost.t(),
          root:
            PostView.t()
            | NotFoundPost.t()
            | BlockedPost.t()
        }
end
