# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ReplyRef do
  @moduledoc """
  **replyRef** (object/record)

  No description.
  """

  @enforce_keys [:root, :parent]
  defstruct grandparentAuthor: nil, parent: nil, root: nil

  @type t :: %__MODULE__{
          grandparentAuthor: ProtoRune.App.Bsky.Actor.Defs.ProfileViewBasic.t(),
          parent:
            ProtoRune.App.Bsky.Feed.Defs.PostView.t()
            | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t(),
          root:
            ProtoRune.App.Bsky.Feed.Defs.PostView.t()
            | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t()
        }
end
