# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonRepost do
  @moduledoc """
  **skeletonReasonRepost** (object/record)

  No description.
  """

  @enforce_keys [:repost]
  defstruct repost: nil

  @type t :: %__MODULE__{
          repost: String.t()
        }
end
