# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonPin do
  @moduledoc """
  **skeletonReasonPin** (object/record)

  No description.
  """

  defstruct []

  @type t :: %__MODULE__{}
end
