# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.SkeletonFeedPost do
  @moduledoc """
  **skeletonFeedPost** (object/record)

  No description.
  """

  @enforce_keys [:post]
  defstruct feedContext: nil, post: nil, reason: nil

  @type t :: %__MODULE__{
          feedContext: String.t(),
          post: String.t(),
          reason:
            ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonRepost.t()
            | ProtoRune.App.Bsky.Feed.Defs.SkeletonReasonPin.t()
        }
end
