# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ThreadViewPost do
  @moduledoc """
  **threadViewPost** (object/record)

  No description.
  """

  alias ProtoRune.App.Bsky.Feed.Defs.BlockedPost
  alias ProtoRune.App.Bsky.Feed.Defs.NotFoundPost
  alias ProtoRune.App.Bsky.Feed.Defs.ThreadViewPost

  @enforce_keys [:post]
  defstruct parent: nil, post: nil, replies: nil, threadContext: nil

  @type t :: %__MODULE__{
          parent:
            ThreadViewPost.t()
            | NotFoundPost.t()
            | BlockedPost.t(),
          post: ProtoRune.App.Bsky.Feed.Defs.PostView.t(),
          replies:
            list(
              ThreadViewPost.t()
              | NotFoundPost.t()
              | BlockedPost.t()
            ),
          threadContext: ProtoRune.App.Bsky.Feed.Defs.ThreadContext.t()
        }
end
