# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ThreadViewPost do
  @moduledoc """
  **threadViewPost** (object/record)

  No description.
  """

  @enforce_keys [:post]
  defstruct parent: nil, post: nil, replies: nil, threadContext: nil

  @type t :: %__MODULE__{
          parent:
            ProtoRune.App.Bsky.Feed.Defs.ThreadViewPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
            | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t(),
          post: ProtoRune.App.Bsky.Feed.Defs.PostView.t(),
          replies:
            list(
              ProtoRune.App.Bsky.Feed.Defs.ThreadViewPost.t()
              | ProtoRune.App.Bsky.Feed.Defs.NotFoundPost.t()
              | ProtoRune.App.Bsky.Feed.Defs.BlockedPost.t()
            ),
          threadContext: ProtoRune.App.Bsky.Feed.Defs.ThreadContext.t()
        }
end
