# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ThreadContext do
  @moduledoc """
  **threadContext** (object/record)

  Metadata about this post within the context of the thread it is in.
  """

  defstruct rootAuthorLike: nil

  @type t :: %__MODULE__{
          rootAuthorLike: String.t()
        }
end
