# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Defs.ViewerState do
  @moduledoc """
  **viewerState** (object/record)

  Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.
  """

  defstruct embeddingDisabled: nil,
            like: nil,
            pinned: nil,
            replyDisabled: nil,
            repost: nil,
            threadMuted: nil

  @type t :: %__MODULE__{
          embeddingDisabled: boolean(),
          like: String.t(),
          pinned: boolean(),
          replyDisabled: boolean(),
          repost: String.t(),
          threadMuted: boolean()
        }
end
