# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.RequestCrawl.Main do
  @moduledoc """
  **main** (procedure)

  Request a service to persistently crawl hosted repos. Expected use is new PDS instances declaring their existence to Relays. Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
