# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.RequestEmailUpdate.Main do
  @moduledoc """
  **main** (procedure)

  Request a token in order to update email.
  """

  @type input :: any()
  @type output :: any()
end
