# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.CreateInviteCode.Main do
  @moduledoc """
  **main** (procedure)

  Create an invite code.
  """

  @type input :: any()
  @type output :: any()
end
