# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Defs.LabelerPolicies do
  @moduledoc """
  Generated schema for labelerPolicies

  **Description**: No description provided.
  """

  @enforce_keys [:label_values]
  defstruct label_value_definitions: nil, label_values: nil

  @type t :: %__MODULE__{
          label_value_definitions:
            list(ProtoRune.Com.Atproto.Label.Defs.LabelValueDefinition.t()),
          label_values: list(ProtoRune.Com.Atproto.Label.Defs.LabelValue.t())
        }
end
