# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Labeler.Defs.LabelerViewerState do
  @moduledoc """
  Generated schema for labelerViewerState

  **Description**: No description provided.
  """

  defstruct like: nil

  @type t :: %__MODULE__{
          like: String.t()
        }
end
