# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.DescribeFeedGenerator do
  @moduledoc """
  Generated query module for main

  **Description**: Get information about a feed generator, including policies and offered feed URIs. Does not require auth; implemented by Feed Generator services (not App View).
  """

  @type output :: %{
          did: String.t(),
          feeds: list(ProtoRune.App.Bsky.Feed.DescribeFeedGenerator.Feed.t()),
          links: ProtoRune.App.Bsky.Feed.DescribeFeedGenerator.Links.t()
        }
end
