# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetFeedGenerator do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{feed: String.t()}
end
