# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetRepostedBy do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cid: String.t(), cursor: String.t(), limit: integer(), uri: String.t()}
end
