# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetPostThread do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{depth: integer(), parent_height: integer(), uri: String.t()}
end
