# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetTimeline do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{algorithm: String.t(), cursor: String.t(), limit: integer()}
end
