# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetAuthorFeed do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{
          actor: String.t(),
          cursor: String.t(),
          filter:
            :posts_with_replies
            | :posts_no_replies
            | :posts_with_media
            | :posts_and_author_threads,
          limit: integer()
        }
end
