# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetPosts do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{uris: list(String.t())}
end
