# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetSuggestedFeeds do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{cursor: String.t(), limit: integer()}
end
