# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Like do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:subject, :created_at]
  defstruct created_at: nil, subject: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          subject: ProtoRune.Com.Atproto.Repo.StrongRef.t()
        }
end
