# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Post do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:text, :created_at]
  defstruct created_at: nil,
            embed: nil,
            entities: nil,
            facets: nil,
            labels: nil,
            langs: nil,
            reply: nil,
            tags: nil,
            text: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          embed:
            ProtoRune.App.Bsky.Embed.Images.t()
            | ProtoRune.App.Bsky.Embed.Video.t()
            | ProtoRune.App.Bsky.Embed.External.t()
            | ProtoRune.App.Bsky.Embed.Record.t()
            | ProtoRune.App.Bsky.Embed.RecordWithMedia.t(),
          entities: list(ProtoRune.App.Bsky.Feed.Post.Entity.t()),
          facets: list(ProtoRune.App.Bsky.Richtext.Facet.t()),
          labels: ProtoRune.Com.Atproto.Label.Defs.SelfLabels.t(),
          langs: list(String.t()),
          reply: ProtoRune.App.Bsky.Feed.Post.ReplyRef.t(),
          tags: list(String.t()),
          text: String.t()
        }
end
