# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Postgate do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:post, :created_at]
  defstruct created_at: nil, detached_embedding_uris: nil, embedding_rules: nil, post: nil

  @type t :: %__MODULE__{
          created_at: String.t(),
          detached_embedding_uris: list(String.t()),
          embedding_rules: list(ProtoRune.App.Bsky.Feed.Postgate.DisableRule.t()),
          post: String.t()
        }
end
