# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.SendInteractions do
  @moduledoc """
  Generated procedure module for main

  **Description**: Send information about interactions with feed items back to the feed generator that served them.
  """

  @type output :: %{}
  @type input :: %{interactions: list(ProtoRune.App.Bsky.Feed.Defs.Interaction.t())}
end
