# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.Threadgate do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @enforce_keys [:post, :created_at]
  defstruct allow: nil, created_at: nil, hidden_replies: nil, post: nil

  @type t :: %__MODULE__{
          allow:
            list(
              ProtoRune.App.Bsky.Feed.Threadgate.MentionRule.t()
              | ProtoRune.App.Bsky.Feed.Threadgate.FollowingRule.t()
              | ProtoRune.App.Bsky.Feed.Threadgate.ListRule.t()
            ),
          created_at: String.t(),
          hidden_replies: list(String.t()),
          post: String.t()
        }
end
