# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetSuggestions.Main do
  @moduledoc """
  **main** (query)

  Get a list of suggested actors. Expected use is discovery of accounts to follow during new account onboarding.
  """

  @type input :: any()
  @type output :: any()
end
