# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetList.Main do
  @moduledoc """
  **main** (query)

  Gets a 'view' (with additional context) of a specified list.
  """

  @type input :: any()
  @type output :: any()
end
