# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetListBlocks.Main do
  @moduledoc """
  **main** (query)

  Get mod lists that the requesting account (actor) is blocking. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
