# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.SendEmail.Main do
  @moduledoc """
  **main** (procedure)

  Send email to a user's account email address.
  """

  @type input :: any()
  @type output :: any()
end
