# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.PutPreferences.Main do
  @moduledoc """
  **main** (procedure)

  Set the private preferences attached to the account.
  """

  @type input :: any()
  @type output :: any()
end
