# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Video.Caption do
  @moduledoc """
  **caption** (object/record)

  No description.
  """

  @enforce_keys [:lang, :file]
  defstruct file: nil, lang: nil

  @type t :: %__MODULE__{
          file: binary(),
          lang: String.t()
        }
end
