# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Video.Main do
  @moduledoc """
  **main** (object/record)

  No description.
  """

  @enforce_keys [:video]
  defstruct alt: nil, aspectRatio: nil, captions: nil, video: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspectRatio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          captions: list(ProtoRune.App.Bsky.Embed.Video.Caption.t()),
          video: binary()
        }
end
