# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Video.View do
  @moduledoc """
  **view** (object/record)

  No description.
  """

  @enforce_keys [:cid, :playlist]
  defstruct alt: nil, aspectRatio: nil, cid: nil, playlist: nil, thumbnail: nil

  @type t :: %__MODULE__{
          alt: String.t(),
          aspectRatio: ProtoRune.App.Bsky.Embed.Defs.AspectRatio.t(),
          cid: String.t(),
          playlist: String.t(),
          thumbnail: String.t()
        }
end
