# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.Account do
  @moduledoc """
  Generated schema for account

  **Description**: Represents a change to an account's status on a host (eg, PDS or Relay). The semantics of this event are that the status is at the host which emitted the event, not necessarily that at the currently active PDS. Eg, a Relay takedown would emit a takedown with active=false, even if the PDS is still active.
  """

  @enforce_keys [:seq, :did, :time, :active]
  defstruct active: nil, did: nil, seq: nil, status: nil, time: nil

  @type t :: %__MODULE__{
          active: boolean(),
          did: String.t(),
          seq: integer(),
          status: :takendown | :suspended | :deleted | :deactivated,
          time: String.t()
        }
end
