# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.Commit do
  @moduledoc """
  Generated schema for commit

  **Description**: Represents an update of repository state. Note that empty commits are allowed, which include no repo data changes, but an update to rev and signature.
  """

  @enforce_keys [
    :seq,
    :rebase,
    :too_big,
    :repo,
    :commit,
    :rev,
    :since,
    :blocks,
    :ops,
    :blobs,
    :time
  ]
  defstruct blobs: nil,
            blocks: nil,
            commit: nil,
            ops: nil,
            prev: nil,
            rebase: nil,
            repo: nil,
            rev: nil,
            seq: nil,
            since: nil,
            time: nil,
            too_big: nil

  @type t :: %__MODULE__{
          blobs: list(binary()),
          blocks: binary(),
          commit: binary(),
          ops: list(ProtoRune.Com.Atproto.Sync.SubscribeRepos.RepoOp.t()),
          prev: binary() | nil,
          rebase: boolean(),
          repo: String.t(),
          rev: String.t(),
          seq: integer(),
          since: String.t() | nil,
          time: String.t(),
          too_big: boolean()
        }
end
