# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.Handle do
  @moduledoc """
  Generated schema for handle

  **Description**: DEPRECATED -- Use #identity event instead
  """

  @enforce_keys [:seq, :did, :handle, :time]
  defstruct did: nil, handle: nil, seq: nil, time: nil

  @type t :: %__MODULE__{
          did: String.t(),
          handle: String.t(),
          seq: integer(),
          time: String.t()
        }
end
