# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.Migrate do
  @moduledoc """
  Generated schema for migrate

  **Description**: DEPRECATED -- Use #account event instead
  """

  @enforce_keys [:seq, :did, :migrate_to, :time]
  defstruct did: nil, migrate_to: nil, seq: nil, time: nil

  @type t :: %__MODULE__{
          did: String.t(),
          migrate_to: String.t() | nil,
          seq: integer(),
          time: String.t()
        }
end
