# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.SubscribeRepos.RepoOp do
  @moduledoc """
  Generated schema for repoOp

  **Description**: A repo operation, ie a mutation of a single record.
  """

  @enforce_keys [:action, :path, :cid]
  defstruct action: nil, cid: nil, path: nil

  @type t :: %__MODULE__{
          action: :create | :update | :delete,
          cid: binary() | nil,
          path: String.t()
        }
end
