# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetHead.Main do
  @moduledoc """
  **main** (query)

  DEPRECATED - please use com.atproto.sync.getLatestCommit instead
  """

  @type input :: any()
  @type output :: any()
end
