# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetTimeline.Main do
  @moduledoc """
  **main** (query)

  Get a view of the requesting account's home timeline. This is expected to be some form of reverse-chronological feed.
  """

  @type input :: any()
  @type output :: any()
end
