# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetConfig.Main do
  @moduledoc """
  **main** (query)

  Get miscellaneous runtime configuration.
  """

  @type input :: any()
  @type output :: any()
end
