# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetStarterPack.Main do
  @moduledoc """
  **main** (query)

  Gets a view of a starter pack.
  """

  @type input :: any()
  @type output :: any()
end
