# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.ListBlobs.Main do
  @moduledoc """
  **main** (query)

  List blob CIDs for an account, since some repo revision. Does not require auth; implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
