# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Unspecced.GetTaggedSuggestions.Suggestion do
  @moduledoc """
  Generated schema for suggestion

  **Description**: No description provided.
  """

  @enforce_keys [:tag, :subject_type, :subject]
  defstruct subject: nil, subject_type: nil, tag: nil

  @type t :: %__MODULE__{
          subject: String.t(),
          subject_type: :actor | :feed,
          tag: String.t()
        }
end
