# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Communication.Defs.TemplateView do
  @moduledoc """
  **templateView** (object/record)

  No description.
  """

  @enforce_keys [:id, :name, :contentMarkdown, :disabled, :lastUpdatedBy, :createdAt, :updatedAt]
  defstruct contentMarkdown: nil,
            createdAt: nil,
            disabled: nil,
            id: nil,
            lang: nil,
            lastUpdatedBy: nil,
            name: nil,
            subject: nil,
            updatedAt: nil

  @type t :: %__MODULE__{
          contentMarkdown: String.t(),
          createdAt: String.t(),
          disabled: boolean(),
          id: String.t(),
          lang: String.t(),
          lastUpdatedBy: String.t(),
          name: String.t(),
          subject: String.t(),
          updatedAt: String.t()
        }
end
