# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetActorLikes.Main do
  @moduledoc """
  **main** (query)

  Get a list of posts liked by an actor. Requires auth, actor must be the requesting account.
  """

  @type input :: any()
  @type output :: any()
end
