# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Sync.GetRepo.Main do
  @moduledoc """
  **main** (query)

  Download a repository export as CAR file. Optionally only a 'diff' since a previous revision. Does not require auth; implemented by PDS.
  """

  @type input :: any()
  @type output :: any()
end
