# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeactivateAccount.Main do
  @moduledoc """
  **main** (procedure)

  Deactivates a currently active account. Stops serving of repo, and future writes to repo until reactivated. Used to finalize account migration with the old host after the account has been activated on the new host.
  """

  @type input :: any()
  @type output :: any()
end
