# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.GetServiceAuth.Main do
  @moduledoc """
  **main** (query)

  Get a signed token on behalf of the requesting DID for the requested service.
  """

  @type input :: any()
  @type output :: any()
end
