# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Embed.Defs.AspectRatio do
  @moduledoc """
  **aspectRatio** (object/record)

  width:height represents an aspect ratio. It may be approximate, and may not correspond to absolute dimensions in any given unit.
  """

  @enforce_keys [:width, :height]
  defstruct height: nil, width: nil

  @type t :: %__MODULE__{
          height: integer(),
          width: integer()
        }
end
