# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateSubjectStatus.Main do
  @moduledoc """
  **main** (procedure)

  Update the service-specific admin status of a subject (account, record, or blob).
  """

  @type input :: any()
  @type output :: any()
end
