# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.UpdateAccountHandle.Main do
  @moduledoc """
  **main** (procedure)

  Administrative action to update an account's handle.
  """

  @type input :: any()
  @type output :: any()
end
