# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetLists.Main do
  @moduledoc """
  **main** (query)

  Enumerates the lists created by a specified account (actor).
  """

  @type input :: any()
  @type output :: any()
end
