# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Admin.GetInviteCodes.Main do
  @moduledoc """
  **main** (query)

  Get an admin view of invite codes.
  """

  @type input :: any()
  @type output :: any()
end
