# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetStarterPacks.Main do
  @moduledoc """
  **main** (query)

  Get views for a list of starter packs.
  """

  @type input :: any()
  @type output :: any()
end
