# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.DeleteSession.Main do
  @moduledoc """
  **main** (procedure)

  Delete the current session. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
