# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.SubscribeLabels.Info do
  @moduledoc """
  **info** (object/record)

  No description.
  """

  @enforce_keys [:name]
  defstruct message: nil, name: nil

  @type t :: %__MODULE__{
          message: String.t(),
          name: :OutdatedCursor
        }
end
