# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Label.SubscribeLabels.Labels do
  @moduledoc """
  **labels** (object/record)

  No description.
  """

  @enforce_keys [:seq, :labels]
  defstruct labels: nil, seq: nil

  @type t :: %__MODULE__{
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          seq: integer()
        }
end
