# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Com.Atproto.Server.ResetPassword.Main do
  @moduledoc """
  **main** (procedure)

  Reset a user account password using a token.
  """

  @type input :: any()
  @type output :: any()
end
