# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetPreferences do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{}
end
