# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.GetProfiles do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{actors: list(String.t())}
end
