# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.Profile do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  defstruct avatar: nil,
            banner: nil,
            created_at: nil,
            description: nil,
            display_name: nil,
            joined_via_starter_pack: nil,
            labels: nil

  @type t :: %__MODULE__{
          avatar: binary(),
          banner: binary(),
          created_at: String.t(),
          description: String.t(),
          display_name: String.t(),
          joined_via_starter_pack: ProtoRune.Com.Atproto.Repo.StrongRef.t(),
          labels: ProtoRune.Com.Atproto.Label.Defs.SelfLabels.t()
        }
end
