# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.PutPreferences do
  @moduledoc """
  Generated procedure module for main

  **Description**: Set the private preferences attached to the account.
  """

  @type input :: %{preferences: ProtoRune.App.Bsky.Actor.Defs.Preferences.t()}
end
