# This module was generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Actor.SearchActorsTypeahead do
  @moduledoc """
  Generated schema for main

  **Description**: No description provided.
  """

  @type t :: %{limit: integer(), q: String.t(), term: String.t()}
end
