# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.DeleteSet.Main do
  @moduledoc """
  **main** (procedure)

  Delete an entire set. Attempting to delete a set that does not exist will result in an error.
  """

  @type input :: any()
  @type output :: any()
end
