# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Graph.GetMutes.Main do
  @moduledoc """
  **main** (query)

  Enumerates accounts that the requesting account (actor) currently has muted. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
