# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Video.GetUploadLimits.Main do
  @moduledoc """
  **main** (query)

  Get video upload limits for the authenticated user.
  """

  @type input :: any()
  @type output :: any()
end
