# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Feed.GetListFeed.Main do
  @moduledoc """
  **main** (query)

  Get a feed of recent posts from a list (posts and reposts from any actors on the list). Does not require auth.
  """

  @type input :: any()
  @type output :: any()
end
