# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Set.GetValues.Main do
  @moduledoc """
  **main** (query)

  Get a specific set and its values
  """

  @type input :: any()
  @type output :: any()
end
