# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.Tools.Ozone.Moderation.QueryEvents.Main do
  @moduledoc """
  **main** (query)

  List moderation events related to a subject.
  """

  @type input :: any()
  @type output :: any()
end
