# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.ListNotifications.Main do
  @moduledoc """
  **main** (query)

  Enumerate notifications for the requesting account. Requires auth.
  """

  @type input :: any()
  @type output :: any()
end
