# Generated by Mix.Tasks.GenSchemas
defmodule ProtoRune.App.Bsky.Notification.ListNotifications.Notification do
  @moduledoc """
  **notification** (object/record)

  No description.
  """

  @enforce_keys [:uri, :cid, :author, :reason, :record, :isRead, :indexedAt]
  defstruct author: nil,
            cid: nil,
            indexedAt: nil,
            isRead: nil,
            labels: nil,
            reason: nil,
            reasonSubject: nil,
            record: nil,
            uri: nil

  @type t :: %__MODULE__{
          author: ProtoRune.App.Bsky.Actor.Defs.ProfileView.t(),
          cid: String.t(),
          indexedAt: String.t(),
          isRead: boolean(),
          labels: list(ProtoRune.Com.Atproto.Label.Defs.Label.t()),
          reason: :like | :repost | :follow | :mention | :reply | :quote | :"starterpack-joined",
          reasonSubject: String.t(),
          record: any(),
          uri: String.t()
        }
end
